### ISSUE TITLE
Add Cloudflare Access Policies Support

### ISSUE THREAD

**Issue by AshleyPoole** [terraform-providers/terraform-provider-cloudflare#100]
Hi there,

It would be good if the Cloudflare Terraform resource supported Cloudflare Access, including the new IP policy options as well.

Terraform Version
$ terraform -v
Terraform v0.11.7

Affected Resource(s)
New resource(s) needed for Cloudflare Access.

Expected Behavior
Terraform provisions a Cloudflare Access policy resource.

Actual Behavior
Not supported yet.

References
https://developers.cloudflare.com/access/setting-up-access/securing-applications/

**Comment by garrettgalow** [comment]
Access hasn't exposed public client APIs yet, so this won't be possible until that happens unfortunately.

**Comment by AshleyPoole** [comment]
Ah, are the public APIs for Access part of the Q3 roadmap?

**Comment by garrettgalow** [comment]
From our Access PM, no hard date, but on the short term roadmap. Would be helpful to understand how you are using TF, and how you plan to integrate Access management once its available. Can you reach out to me: gg at cloudflare.com if you don't mind.

**Comment by jamfish** [comment]
@garrettgalow my team saw this ticket and also wondered if we could reach out, as we're interested in this feature as well.

**Comment by AustinCorridor** [comment]
Hi everyone,

This is Sam on the Access team. We published our public APIs recently. You can find them here
https://api.cloudflare.com/#access-applications-properties

We'd be happy to discuss your specific use case, feel free to reach out to me: srhea at cloudflare.com

Sam

**Comment by jacobbednarz** [comment]
As a FYI, I have a branch locally that adds Access support to the Terraform provider however it's pending https://github.com/cloudflare/cloudflare-go/pull/233 for the actual API calls. Once that lands, I'll push up the branch so that we don't have two in progress branches that are depending on each other.

**Comment by jacobbednarz** [comment]
I've opened #145 which adds Access support. Some design thoughts and considerations included there so would appreciate some 👀 if you're interested in using it.
