### ISSUE TITLE
Multiple dns zones with identical names defaults to first zone in the list

### ISSUE THREAD

**Issue by holms** [terraform-providers/terraform-provider-cloudflare#109]
### Terraform Version
```
holms@debian ~/D/c/l/a/p/terraform> terraform -v
Terraform v0.11.7
+ provider.ansible v0.0.4
+ provider.aws v1.33.0
+ provider.cloudflare v1.2.0
+ provider.digitalocean v0.1.3
+ provider.mysql v1.1.0
```

### Affected Resource(s)
- cloudflare_record

### Terraform Configuration Files
```hcl
resource "cloudflare_record" "swarm-lb" {
  domain = "whatever.io"
  name   = "*"
  value  = "${digitalocean_loadbalancer.public.ip}"
  type   = "A"
  ttl    = 1600
}
```

### Expected Behavior
My case is when I'm included as a member of another account which has a dns zone with name "whatever.io" with status moved. I've added same zone in my account and initialized name server changes on that domain. I've left old zone on another account because I wanted to have a backup of all dns records, because when moving domain CF doesn't find all records automatically so wanted to have backup just in case.

After creating this record, I've noticed that nothing happened on  my account `whatever.io` zone. I've expected to get wildcard record in there. Actually I've expected that records will be added on the zone which is active, not the one which is marked as "moved"

### Actual Behavior
When launched `terraform show` it appears to be zone_id is from old account. All records appeared under old account dns zone. You seems to be didn't except to have multiple same named dns zones in CF did you :)?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create 2 accounts on CF
2. Add domain for the first one
3. Add domain for the second one with same name
4. Make second account member of the first one
5.  `terraform apply`
6. Watch how your records appears on acc 1 rather than on acc 2

**Comment by garrettgalow** [comment]
Terraform defaults to your personal account by default unless you set the org_id parameter in the provider config. If you are a member of multiple accounts I believe you will need to set the org_id to the account tag of the other account to make changes there.

**Comment by holms** [comment]
Well for me it was easier just to remove that backup. But thanks if this by
design is how you expect it to have, would be nice to refer this in docs.

**Comment by garrettgalow** [comment]
Its documented albeit not very well on the provider configuration in the docs. We are moving to having more resources take a zone_id as a param to alleviate this issue. This will also allow users to manage many zones across many accounts in their TF files much mor easily.
