### ISSUE TITLE
Feature Request: Support for managing worker scripts

### ISSUE THREAD

**Issue by derekargueta** [terraform-providers/terraform-provider-cloudflare#110]
From [the documentation](https://www.terraform.io/docs/providers/cloudflare/index.html) it doesn't seem that Worker JS files can be managed via Terraform. It'd be awesome if uploading/deleting/managing worker code and routes could be done through Terraform.

Worker API documentation: https://api.cloudflare.com/#worker-script-properties

**Comment by patryk** [comment]
Duplicate of #50. Closing.
