### ISSUE TITLE
Allow to disable SSL cert verification for cloudflare_load_balancer_monitor

### ISSUE THREAD

**Issue by jakubgs** [terraform-providers/terraform-provider-cloudflare#113]
Right now I see no option to disable SSL verification for HTTPS endoints.

I also find it weird that the healthcheck fails despite my HTTPS endpoint using a CloudFlare Origin certificate. I'd expect that to work.

**Comment by jacobbednarz** [comment]
Once cloudflare/cloudflare-go#218 lands, we can add support to the Terraform provider.

**Comment by l13t** [comment]
Found this issue. Had same problems with setting up `cloudflare_load_balancer_monitor` [in August](https://github.com/terraform-providers/terraform-provider-cloudflare/issues/49#issuecomment-415690311).

**Comment by jacobbednarz** [comment]
@jakubgs @l13t this should now be solved with #205. Feel free to pull it down and test it out before we merge it.

**Comment by l13t** [comment]
Hi @jacobbednarz
sorry, i'm already in a different company and can't check this - we don't have CF LB's in our setup at the moment. I'd try to contact my ex-colleagues to test.

**Comment by jacobbednarz** [comment]
All good @l13t - It was just to make sure your particular case was covered. If you don't need it anymore, I'm happy to rely on the test suite instead.
