### ISSUE TITLE
Import multi-script worker route problem

### ISSUE THREAD

**Issue by amogozov** [terraform-providers/terraform-provider-cloudflare#123]
Importing `cloudflare_worker_route` always imports it as if it is single-script worker filter even `CLOUDFLARE_ORG_ID` is set. 
What is the correct way to import multi-script worker route?

### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
cloudflare_worker_route

### Terraform Configuration Files
```hcl
terraform {
  required_version = "0.11.7"
}

resource "cloudflare_worker_route" "route" {
  zone = ""
  pattern = ""
  script_name = "${cloudflare_worker_script.script.name}"
}

resource "cloudflare_worker_script" "script" {
  name = "my_script"
  content = "${file("./scripts/my_script")}"
}
```

### Expected Behavior
Resource imported as multi-script route

### Actual Behavior
Resource imported as single-script filter

### Steps to Reproduce
CLOUDFLARE_ORG_ID=xxx terraform import cloudflare_worker_route.route zone/route_id

### References
#111

**Comment by jacobbednarz** [comment]
@amogozov worker routes are defined on a per site basis (see the [API docs](https://developers.cloudflare.com/workers/api/config-api-for-enterprise/#create-a-route)). From your configuration above, you're omitting the `zone` key [which is needed as well as the organisation ID](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/e334b5a7e4159b3d1d580fe154601f8e4a532bd3/vendor/github.com/cloudflare/cloudflare-go/workers.go#L215-L237). Could you try that and report back?

**Comment by amogozov** [comment]
@jacobbednarz I hid zone on purpose, I have it in my real config file

**Comment by amogozov** [comment]
@jacobbednarz yes, 100%, your command works and creates new worker in multi-script org and binds it to a route.
My case is a bit different. I already have existing workers in Cloudflare, and I am terraforming them now, so I'm trying to use `terraform import` command which does not produce expected behavior. It imports worker as if it is single-script
```
...
                        "attributes": {
                            "enabled": "true",
                            "id": "x",
                            "multi_script": "false",
                            "pattern": "x",
                            "zone": "x",
                            "zone_id": "x"
                        },
...
```

so subsequent plan suggests the change:

```json
  ~ cloudflare_worker_route.route
      enabled:     "true" => "false"
      script_name: "" => "script"
```

Maybe this change is totally safe to apply, but it is not changing `multi_script` attribute and I don't want to break my existing Cloudflare configuration applying this.

**Comment by jacobbednarz** [comment]
Apologies @amogozov - I completely missed the _actual_ issue here.

Diving into this seems to pin the blame at https://github.com/terraform-providers/terraform-provider-cloudflare/blob/d5cc209e8366a65c96a315923083275866d36d38/cloudflare/resource_cloudflare_worker_route.go#L197

Everything up until this point, seems to be working as expected. I'll have a further dig here but the good news is that I can replicate it.

**Comment by amogozov** [comment]
@jacobbednarz thanks for looking into this 👍 
 Hope it will be resolved soon

**Comment by amogozov** [comment]
@jacobbednarz looking at the code I think it should solve the problem. Is there any way I can build your branch and test it locally?

**Comment by jacobbednarz** [comment]
Yep, there some instructions at https://www.terraform.io/docs/extend/writing-custom-providers.html. You'll mainly be interested in setting up your go dev env and building the provider. Once it's built, you can update your `~./terraformrc` file to point at the locally built version and run your import like you normally would.

**Comment by amogozov** [comment]
@jacobbednarz your patch worked for me, thanks ! Is there any chance to publish updated provider to hashicorp?
