### ISSUE TITLE
cloudflare_record: unable to specify ttl

### ISSUE THREAD

**Issue by mrparkers** [terraform-providers/terraform-provider-cloudflare#126]
### Terraform Version
```
Terraform v0.11.8
+ provider.cloudflare v1.7.0
```
### Affected Resource(s)
- cloudflare_record

### Terraform Configuration Files
```hcl
resource "cloudflare_record" "example" {
  domain  = "example.com"
  name    = "foo.example.com"
  value   = "35.35.35.35"
  type    = "A"
  ttl     = 300
  proxied = true
}
```

### Expected Behavior
`terraform plan` should be clean, and the TTL for that record should be 5 minutes in the Cloudflare Dashboard.

### Actual Behavior
`terraform plan` results in the following output after applying:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ cloudflare_record.example
      ttl: "1" => "300"
```

The Cloudflare dashboard shows a TTL of "Automatic", despite the resource definition specifying a TTL of 5 minutes.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
1. `terraform plan`

**Comment by patryk** [comment]
You cannot specify `ttl` if `proxied=true`. It's not actually Terraform specific behaviour. It's how Cloudflare API works.

**Comment by mrparkers** [comment]
Thank you for the explanation, although I still believe that this is an issue that should be addressed in the provider, since constantly seeing a plan diff is definitely confusing for the end user.

Would you accept a PR that adds validation to ensure that `ttl` is not set if `proxied` is `true`?

**Comment by patryk** [comment]
Yeah, absolutely. You're right that we could make sure that Terraform plugin will stop unsupported setting instead of silently dropping it.
