### ISSUE TITLE
resource cloudflare_record accept zone_id

### ISSUE THREAD

**Issue by chasebolt** [terraform-providers/terraform-provider-cloudflare#131]
currently we have to add `depends_on` property to all of our records to setup dependencies. now that `cloudflare_zone` has been added and outputs `cloudflare_zone.id`, we could use that in the resources to tie dependency.

```tf
provider "cloudflare" {
  email  = "${var.email}"
  token  = "${var.token}"
  org_id = "${var.org_id}"
}

locals = {
  domains = ["${split("\n",trimspace(file("domains")))}"]
}

resource "cloudflare_zone" "default" {
  count = "${length(local.domains)}"
  zone  = "${element(local.domains, count.index)}"
}

# current scenario
resource "cloudflare_record" "apex" {
  count   = "${length(local.domains)}"
  domain  = "${element(local.domains, count.index)}"
  name    = "@"
  value   = "domain.com"
  type    = "CNAME"
  ttl     = 1
  proxied = true

  depends_on = ["cloudflare_zone.default"]
}

# ideal scenario
resource "cloudflare_record" "www" {
  count    = "${length(local.domains)}"
  zone_id  = "${cloudflare_zone.default.id}"
  name     = "www" 
  value    = "${element(local.domains, count.index)}"
  type     = "CNAME"
  ttl      = 1 
  proxied  = true
}
```

**Comment by chasebolt** [comment]
was this closed because it has been resolved in a recent version?

**Comment by jacobbednarz** [comment]
@chasebolt I can't see a question in this issue and it has sat for months without activity. Are you able to follow the [issue template](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/.github/ISSUE_TEMPLATE.md) so we can better understand your issue and whether it requires changes?

**Comment by chasebolt** [comment]
@jacobbednarz `cloudflare_record` only accepts `domain` as the literal domain name `example.com`. `cloudflare_zone` only outputs the domain's zone `id`. this makes it impossible to tie the `cloudflare_zone` and `cloudflare_record` together in the dependency graph. am i missing something on how to tie these resources together?

**Comment by jacobbednarz** [comment]
At the moment the `cloudflare_zone` data source only returns the ID. I can't recall if going forward we are swapping everything to `zone_id` or `zone_name` (I'm suspecting the former to prevent duplication of domains but will confirm with @patryk's thinking) and all resources will be updated to support that but for now there is a mismatch between some of them. We are able to add the attribute to the other resources at the moment to support the reuse here.

Are you able to open an issue (following the [issue template](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/.github/ISSUE_TEMPLATE.md)) and expand on how you'd like to see this working? Even with your comment above, the code sample and your original issue are still quite confusing to understand so let's iron that out before we move any further with this.

**Comment by chasebolt** [comment]
sounds good i can do that
