### ISSUE TITLE
error creating load balancer monitor: interval is not in range [60, 3600]

### ISSUE THREAD

**Issue by puckey** [terraform-providers/terraform-provider-cloudflare#133]
According to the example usage at https://www.terraform.io/docs/providers/cloudflare/r/load_balancer_monitor.html `55` should be a valid value for 'interval` – but when using this example code, I see the following error:

```
cloudflare_load_balancer_monitor.test: error creating load balancer monitor: error from makeRequest: HTTP status 400: content "{\n  \"result\": null,\n  \"success\": false,\n  \"errors\": [\n    {\n      \"code\": 1002,\n      \"message\": \"interval is not in range [60, 3600]: validation failed\"\n    }\n  ],\n  \"messages\": []\n}\n"
* module.swarm-ams.cloudflare_load_balancer_monitor.test: 1 error(s) occurred:
```

### Terraform Version
v0.11.10

### Affected Resource(s)
- cloudflare_load_balancer_monitor

### Terraform Configuration Files
```hcl
resource "cloudflare_load_balancer_monitor" "test" {
  expected_body = "alive"
  expected_codes = "2xx"
  method = "GET"
  timeout = 7
  path = "/health"
  interval = 55
  retries = 5
  description = "example load balancer"
}
```

### Expected Behavior
What should have happened?

According to the example usage at https://www.terraform.io/docs/providers/cloudflare/r/load_balancer_monitor.html `55` should be a valid value for 'interval`

### Actual Behavior
The error states that the value should be between `60` and `3600`

**Comment by jacobbednarz** [comment]
Thanks for the bug report @puckey! I've addressed this in #136 which will update the documentation and provide some stricter schema validation to get a faster feedback loop should you provide an `interval` value outside that which is expected.

**Comment by SteveGoldthorpe-Work** [comment]
Where did the minimum of 60 come from?  With my enterprise account I can (and do) set the interval to 20 seconds (timeout=5 retries2).
This has now broken my config.

**Comment by jacobbednarz** [comment]
This was tested from the original issue reporter as well as my personal and
an enterprise account for verification based on the public documentation.
In both testing instances (cURL + terraform), I received an API validation
error when using a value less than 60 and greater than 3600.

Do you have additional entitlements in your Cloudflare contract or anything
that varies from the general offering that would be a factor here?

**Comment by SteveGoldthorpe-Work** [comment]
_additional entitlements_
Quite possible - Just done a test with silly lower limits with plugin 1.7.0 and got:
`* cloudflare_load_balancer_monitor.mon_api_test: error creating load balancer monitor: error from makeRequest: HTTP status 400: content "{\n  \"result\": null,\n  \"success\": false,\n  \"errors\": [\n    {\n      \"code\": 1002,\n      \"message\": \"interval is not in range [10, 3600]: validation failed\"\n    }\n  ],\n  \"messages\": []\n}\n"`

However, if the limits can vary by account, shouldn't we let the API itself validate the lower boundary rather than enforce an arbitrary one?  Maybe we shouldn't bother with the code check at all and put something in the documentation (i.e. the lower limit is dependent on your account).

**Comment by jacobbednarz** [comment]
If the entitlements can be altered then we might need to remove the schema
validation.

I don't think we can rely on the API error for validation as that occurs
too late in the feedback cycle to be useful. The developer will already
have the HTTP error in front of them by that point. The idea of using
schema validation is that errors are caught before any resource or API
interactions are made.

Happy to remove the validation but when the PR is raised, let's ensure we
make it very clear why it's not possible with some links back to this
discussion to prevent a regression. I can do this next week if someone
doesn't look at it before then.
