### ISSUE TITLE
Improve 'Building the provider' instructions

### ISSUE THREAD

**Issue by puckey** [terraform-providers/terraform-provider-cloudflare#142]
The __Building the provider__ section of the README states that `{GOPATH}` is not evaluated, but using `${GOPATH}` works for me.

Also the condiguration example above it has a mistake in its path.

Working version:
```
providers {
  cloudflare = "${GOPATH}/src/github.com/terraform-providers/terraform-provider-cloudflare/terraform-provider-cloudflare"
}
```

**Comment by patryk** [comment]
Thanks, didn't know it actually worked here.

**Comment by jacobbednarz** [comment]
Oh cool! Thanks for the update!
