### ISSUE TITLE
Add support for load balancer dynamic steering

### ISSUE THREAD

**Issue by pietermees** [terraform-providers/terraform-provider-cloudflare#146]
There does not seem to be any support for the "dynamic steering" feature for load balancers.

**Comment by jacobbednarz** [comment]
👋 @pietermees . Thanks for the report! I've opened #147 which should address this issue. Would you mind pulling it locally, building the provider and confirming this works as you expect it to?

**Comment by pietermees** [comment]
@jacobbednarz awesome, thanks for the quick response!
I currently don't have a working setup, I encountered this while looking to migrate an existing manual setup to TF. Therefore, I might not be the best person to provide a test in the short term. If the PR is still open when we have it up and running, I'll loop back with confirmation!
