### ISSUE TITLE
Allow `credentials` field in provider block for loading JSON credentials

### ISSUE THREAD

**Issue by RyanSquared** [terraform-providers/terraform-provider-cloudflare#16]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please 
upgrade because your issue may have already been fixed.

```sh
$ terraform -v
Terraform v0.10.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance
- opc_storage_volume

It's not a resource, it's the provider config.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

# The current version
provider "cloudflare" {
  email = "test@example.com"
  token = "this is obviously fake"
}

# My preferred version
provider "cloudflare" {
  credentials = {
    email = "test@example.com"
    token = "this is obviously fake"
  }
}

# What I want in my config
provider "cloudflare" {
  credentials = "${file('~/.config/cloudflare/credentials.json')}"
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

I'd like to be able to have dynamic CloudFlare credentials. So far, loading them via reading a file
has not worked, as it appends a "\n" to the end of the strings on systems/editors that do such.

### Actual Behavior
What actually happened?

Not relevant.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

Not relevant.

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

No.

**Comment by RyanSquared** [comment]
Kinda left it out, but this would mean deprecating the `email` and `token` value - or alternatively having it so that either `email` and `token` can exist, `credentials` can exist, but never both at the same time.

**Comment by jleclanche** [comment]
Can you load the file into a variable and then access yourvar.email / yourvar.token?

**Comment by RyanSquared** [comment]
@jleclanche how would I go about doing that? I suppose it is possible but I'd much rather have something built-in as I've seen other systems use.

**Comment by jacobbednarz** [comment]
Closing this off as there hasn't been any further interest in progressing this and it hasn't been updated in over a year.
