### ISSUE TITLE
Add new zone data source

### ISSUE THREAD

**Issue by ewilde** [terraform-providers/terraform-provider-cloudflare#163]
## Summary
Introduce new data source `cloudflare_zone`

# cloudflare_zone

Use this data source to look up a [Zone][1] record.

## Example Usage

```hcl
data "cloudflare_zone" "test" {
  zone = "example.com"
}

resource "cloudflare_spectrum_application" "ssh" {
  zone_id  = "${data.cloudflare_zone.test.id}"
  protocol = "tcp/22"

  dns = {
    type = "CNAME"
    name = "ssh.${data.cloudflare_zone.test.zone}"
  }

  origin_direct = ["tcp://81.120.102.10:23"]
  origin_port   = 22
}
```

## Argument Reference

- `zone` - (Required) The name of the zone to match.

## Attributes Reference

- `id`           - Id of the zone
- `status`       - Zone status. Valid values: active, pending, initializing, moved, deleted, deactivated and read only
- `name_servers` - List of name servers
- `type`         - Zone type. Valid values: full or partial

[1]: https://api.cloudflare.com/#zone-properties

I will start a PR for this feature

**Comment by patryk** [comment]
Being worked on in #168.

**Comment by patryk** [comment]
Done.
