### ISSUE TITLE
cloudflare_firewall_rule import issue - zone not set

### ISSUE THREAD

**Issue by SteveGoldthorpe-Work** [terraform-providers/terraform-provider-cloudflare#165]
terraform import for cloudflare_firewall_rule resource forces a new resource on next apply as zone is not added up on import.
`zone: "" => "domain.name" (forces new resource)`

Similar to #161

provider.cloudflare 1.9

**Comment by jacobbednarz** [comment]
Pending direction in #162. Once that is 👍 , I'll port the changes to this resource.

**Comment by jacobbednarz** [comment]
#174 is applying the fix mentioned from #162 for the `cloudflare_firewall_rule` resource.
