### ISSUE TITLE
cloudflare_access_rule import issue - zone not set

### ISSUE THREAD

**Issue by SteveGoldthorpe-Work** [terraform-providers/terraform-provider-cloudflare#166]
importing a zone based access rule doesn't set zone forcing a new resource next plan/apply.

```
terraform import cloudflare_access_rule.whitelist_mywhitelist zone/85e6c246febfda393702006b823326ab/e9536f2f59b330327d3292c23b508ea9
Import successful!
```

on next plan
`      zone:                 "" => "domain.name" (forces new resource)`

Similar to #161 and #165 

provider.cloudflare 1.9

**Comment by SteveGoldthorpe-Work** [comment]
As with all these zone import issues, workaround is to pull the state after import, add the missing zone definition manually and push the state back.

**Comment by jacobbednarz** [comment]
Pending direction in #162. Once that is 👍 , I'll port the changes to this resource.
