### ISSUE TITLE
Changing a Page Rule's zone doesn't force recreation

### ISSUE THREAD

**Issue by shosti** [terraform-providers/terraform-provider-cloudflare#180]
### Terraform Version
```
Terraform v0.11.8
+ provider.cloudflare v1.10.0
```

### Affected Resource(s)
- cloudflare_page_rule

### Terraform Configuration Files
```hcl
variable "cloudflare_api_key" {
  type = "string"
}

variable "cloudflare_email" {
  type = "string"
}

provider "cloudflare" {
  version = "~> 1.10.0"
  email   = "${var.cloudflare_email}"
  token   = "${var.cloudflare_api_key}"
}

variable "domain" {
  type = "string"
}

resource "cloudflare_page_rule" "strict_ssl" {
  zone   = "${var.domain}"
  target = "https://foobar.${var.domain}/"

  actions = {
    ssl = "strict"
  }
}
```

### Expected Behavior
When the Page Rule zone has changed, it should destroy the Page Rule in the old zone and create a new one in the new zone.

### Actual Behavior
It tries to modify the Page Rule in place, which leads to an error message from the Cloudflare API similar to the following:

```
* cloudflare_page_rule.strict_ssl: Failed to update Cloudflare Page Rule: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1004,\"message\":\"Page Rule validation failed: See messages for details.\"}],\"messages\":[{\"code\":1,\"message\":\".targets[0]: Your URL should reference the domain '<thedomain>' in some way.\",\"type\":null}],\"result\":null}"
```

### Steps to Reproduce
Prerequisites:
- The above configuration
- `cloudflare_email` and `cloudflare_api_key` in `terraform.tfvars`
- 2 domains in a Cloudflare account (in this example, `domain1.com` and `domain2.com`)

Steps:
1. `terraform init`
2. `terraform apply -var 'domain=domain1.com'`
2. `terraform apply -var 'domain=domain2.com'`

**Comment by jacobbednarz** [comment]
What does your Terraform state file look like? There isn't anything specifically to support the `count` meta parameter and creation/updating page rules so I'm not sure how this is intended to work as is.

**Comment by shosti** [comment]
@jacobbednarz this has nothing to do with the `count`; it shows up in singular resources as well. To help debug I updated the instructions to have a minimal reproduction.

**Comment by jacobbednarz** [comment]
Thanks for the updated test case and filling out the other information! It's helped me take a look further into the issue.

With a local state file using two different domains, it's treating them as the same resource due to the resource identifier being the same and attempting to just update in-place instead of create a new resource. In order to achieve what you're after here, can update the `zone` attribute to have `ForceNew` which will ensure an updated domain (in your case) also means a new rule. I'll PR this shortly.

**Comment by jacobbednarz** [comment]
#183 should address this issue. Please pull it locally and let me know if you have any other issues!
