### ISSUE TITLE
PageRule documentation for priority

### ISSUE THREAD

**Issue by inge4pres** [terraform-providers/terraform-provider-cloudflare#181]
Hi 👋🏻

we are starting to work with Cloudflare PageRules and found the documentation not easy to use with regards to the `priority` attribute.

The API docs says the higher the number the higher the priority, but the website UI show a lower number for a higher priority.
Maybe we can explicitly enrich the `cloudflare_page_rule` resource documentation to avoid confusion around this topic.

### References
https://www.terraform.io/docs/providers/cloudflare/r/page_rule.html#priority
https://api.cloudflare.com/#page-rules-for-a-zone-create-page-rule

**Comment by mbrowne** [comment]
There may be an additional issue here...I just tried deleting all my page rules and recreating them entirely via Terraform, but the `priority` values from the `pagerules` API call (`ListPageRules()` method if using the Go API) don't match what's configured in Terraform. The rule with priority 15 in my .tf file is now priority 20, priority 18 is now 19, etc. I'm guessing it's more likely an issue with the Cloudflare API than with this Terraform provider though...

**Comment by inge4pres** [comment]
Hi @mbrowne can you please share your config? Would be glad to see how you configured the page rule and possibly help

**Comment by mbrowne** [comment]
Hi @inge4pres, assuming it's not necessary to share the entire config, here are a few of our page rules...

```
resource "cloudflare_page_rule" "19" {
  priority = 19
  zone     = "${var.zone}"
  target   = "*portal.${var.zone}/*"
  status   = "active"

  actions = {
    resolve_override = "portal.${var.zone}"
  }
}

resource "cloudflare_page_rule" "18" {
  priority = 18
  zone     = "${var.zone}"
  target   = "https://*${var.zone}/galleries/*"
  status   = "disabled"

  actions "forwarding_url" {
    status_code = 301
    url         = "http://www${var.zone}/galleries/$2"
  }
}

resource "cloudflare_page_rule" "17" {
  priority = 17
  zone     = "${var.zone}"
  target   = "*${var.zone}/*-for-sale*"
  status   = "active"

  actions = {
    resolve_override = "${var.zone}"
  }
}

resource "cloudflare_page_rule" "16" {
  priority = 16
  zone     = "${var.zone}"
  target   = "*${var.zone}/galleries/fine-art/*"
  status   = "active"

  actions = {
    resolve_override = "${var.zone}"
  }
}
```

The priorities are in descending order going all the way down to 1, to match the results I got from the API for the pre-existing rules in Cloudflare before we ever ran `terraform apply`.

**Comment by inge4pres** [comment]
What's a `terraform plan` showing when this resources don't yet exist in API?

**Comment by mbrowne** [comment]
It said it was going to add all the rules (i.e. all additions, no modifications or deletions), so I don't think that was the issue in my case.

**Comment by jacobbednarz** [comment]
@mbrowne Are you able to open a new issue following the provided [issue template](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/.github/ISSUE_TEMPLATE.md)? This issue is for discussion related to the documentation and I think it's better served in it's own issue so we can keep them separate.

**Comment by mbrowne** [comment]
New issue created here: #187

**Comment by jacobbednarz** [comment]
@patryk This one is good to close as #182 has landed.
