### ISSUE TITLE
Data Provider For Zone

### ISSUE THREAD

**Issue by AshleyPoole** [terraform-providers/terraform-provider-cloudflare#190]
### Affected Resource(s)
- data.cloudflare_zone (new)

### Expected Behavior
A new data resource for being able to access a zone using it's domain name. This is useful for resources that require the zone ID. At the moment, no resource exists, and using import isn't feasible when using the zone for multiple environment references.

**Comment by jacobbednarz** [comment]
This is already being discussed in #168. I'd recommend following along there for details to keep up to date with the development.

**Comment by patryk** [comment]
#168 is merged, so I consider this issue done. Thanks.
