### ISSUE TITLE
plan Enterprise Website not found amongst the available plans

### ISSUE THREAD

**Issue by lifeofguenter** [terraform-providers/terraform-provider-cloudflare#191]
I can not create a zone with "enterprise" plan:

```
plan Enterprise Website not found amongst the available plans
```

It will create it as "free". If I re-run terraform I get:

```
* cloudflare_zone.xxx: Error updating zone_id "": error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1022,\"message\":\"Zone is already unpaused\"}],\"messages\":[],\"result\":null}"
```

I was able to switch it manually over the admin-panel though.

**Comment by jacobbednarz** [comment]
@lifeofguenter Are you able to please update your issue to match the [ISSUE TEMPLATE](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/.github/ISSUE_TEMPLATE.md)? The information you've provided isn't enough to help troubleshoot the issue.
