### ISSUE TITLE
Failed to create page rule: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1001,\"message\":\"Invalid zone identifier\"}],\"messages\":[],\"result\":null}"

### ISSUE THREAD

**Issue by sirkjohannsen** [terraform-providers/terraform-provider-cloudflare#192]
### Terraform Version
```
Terraform v0.11.11
+ provider.aws v1.42.0
+ provider.cloudflare v1.10.0
+ provider.google v1.20.0
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.random v1.3.1
+ provider.template v1.0.0
+ provider.vault v1.1.0
```

### Affected Resource(s)
- cloudflare_page_rule

### Terraform Configuration Files
```hcl
resource "cloudflare_page_rule" "example_com_host_header_override" {
  count = 2
  zone = "example.com"
  target = "${element(list("http","https"),count.index)}://www-staging.example.com/*"
  priority = "${count.index + 1}"

  actions = {
    host_header_override = "www-stg.example.com"
  }
}
```

used example.com here but it is of course a different domain owned by our account.

### Debug Output
```
* cloudflare_page_rule.example_com_host_header_override.1: Failed to create page rule: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1001,\"message\":\"Invalid zone identifier\"}],\"messages\":[],\"result\":null}"

* cloudflare_page_rule.example_com_host_header_override.0: Failed to create page rule: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1001,\"message\":\"Invalid zone identifier\"}],\"messages\":[],\"result\":null}"
```
### Expected Behavior
create page rule

### Actual Behavior
above error message

### Steps to Reproduce
1. `terraform apply`

### further information
we also use `cloudflare_record` and that resource works just fine.

**Comment by patryk** [comment]
Just to be sure, please update to v1.10.0 and see whether the bug is still there.

**Comment by sirkjohannsen** [comment]
cloudflare provider is v.1.10.0: `provider.cloudflare v1.10.0`

**Comment by patryk** [comment]
Ops, sorry, I meant 1.11 released on 11th January.

**Comment by sirkjohannsen** [comment]
:) okay. Just tried `v1.11`:
```
$ terraform -v
Terraform v0.11.11
+ provider.aws v1.42.0
+ provider.cloudflare v1.11.0
+ provider.google v1.20.0
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.random v1.3.1
+ provider.template v1.0.0
+ provider.vault v1.1.0
```
still the same issue:
```
* cloudflare_page_rule.example_com_forwarding_url: Failed to create page rule: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1001,\"message\":\"Invalid zone identifier\"}],\"messages\":[],\"result\":null}"
```

**Comment by jacobbednarz** [comment]
@sirkjohannsen do you mind running the `terraform apply` command with `TF_LOG=DEBUG` environment variable set? This will provide further debugging output to help track down why the zone name isn't finding the correct ID.

**Comment by sirkjohannsen** [comment]
Hello :) 
I just discovered something really interesting.
If I run the `terraform apply` with the specific `cloudflare_page_rule` targets only - it works. 
e.g.: `terraform apply -target=cloudflare_page_rule.example_com_host_header_override`

If I run the complete terraform project it fails as stated above. 
Sadly the Debug-Output of the complete project includes too many secrets and credentials and therefore I can not post it here completely.
But I found the following in the debug log:
 
```

2 error(s) occurred:

* module.cf_page_rules.cloudflare_page_rule.example_com_forwarding_url[1]: 1 error(s) occurred:

* cloudflare_page_rule.example_com_forwarding_url.1: Failed to create page rule: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1001,\"message\":\"Invalid zone identifier\"}],\"messages\":[],\"result\":null}"
* module.cf_page_rules.cloudflare_page_rule.example_com_forwarding_url[0]: 1 error(s) occurred:

* cloudflare_page_rule.example_com_forwarding_url.0: Failed to create page rule: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1001,\"message\":\"Invalid zone identifier\"}],\"messages\":[],\"result\":null}"

2019-01-16T14:06:04.931+0100 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4: 2019/01/16 14:06:04 [ERR] plugin: plugin server: accept unix /tmp/plugin975879760: use of closed network connection
2019-01-16T14:06:04.931+0100 [DEBUG] plugin.terraform: local-exec-provisioner (internal) 2019/01/16 14:06:04 [ERR] plugin: plugin server: accept unix /tmp/plugin382513181: use of closed network connection
2019-01-16T14:06:04.931+0100 [DEBUG] plugin.terraform: local-exec-provisioner (internal) 2019/01/16 14:06:04 [DEBUG] plugin: waiting for all plugin processes to complete...
Terraform does not automatically rollback in the face of errors.
2019-01-16T14:06:04.931+0100 [DEBUG] plugin.terraform: remote-exec-provisioner (internal) 2019/01/16 14:06:04 [ERR] plugin: plugin server: accept unix /tmp/plugin307797477: use of closed network connection
2019-01-16T14:06:04.931+0100 [DEBUG] plugin.terraform: remote-exec-provisioner (internal) 2019/01/16 14:06:04 [DEBUG] plugin: waiting for all plugin processes to complete...
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.^[[0m

^[[0m^[[0m^[[0m
2019-01-16T14:06:04.931+0100 [DEBUG] plugin.terraform-provider-aws_v1.42.0_x4: 2019/01/16 14:06:04 [ERR] plugin: plugin server: accept unix /tmp/plugin046565609: use of closed network connection
2019-01-16T14:06:04.931+0100 [DEBUG] plugin.terraform-provider-cloudflare_v1.11.0_x4: 2019/01/16 14:06:04 [ERR] plugin: plugin server: accept unix /tmp/plugin878623400: use of closed network connection
2019-01-16T14:06:04.931+0100 [DEBUG] plugin: plugin process exited: path=/home/sirk/repos/simplesurance/devops/terraform/sisu-unified/.terraform/plugins/linux_amd64/terraform-provider-null_v1.0.0_x4
2019-01-16T14:06:04.932+0100 [DEBUG] plugin: plugin process exited: path=/home/sirk/repos/simplesurance/devops/terraform/sisu-unified/.terraform/plugins/linux_amd64/terraform-provider-vault_v1.1.0_x4
2019-01-16T14:06:04.932+0100 [DEBUG] plugin: plugin process exited: path=/home/sirk/repos/simplesurance/devops/terraform/sisu-unified/.terraform/plugins/linux_amd64/terraform-provider-random_v1.3.1_x4
2019-01-16T14:06:04.933+0100 [DEBUG] plugin: plugin process exited: path=/usr/local/bin/terraform
2019-01-16T14:06:04.933+0100 [DEBUG] plugin: plugin process exited: path=/home/sirk/repos/simplesurance/devops/terraform/sisu-unified/.terraform/plugins/linux_amd64/terraform-provider-local_v1.1.0_x4
2019-01-16T14:06:04.933+0100 [DEBUG] plugin: plugin process exited: path=/home/sirk/repos/simplesurance/devops/terraform/sisu-unified/.terraform/plugins/linux_amd64/terraform-provider-template_v1.0.0_x4
2019-01-16T14:06:04.934+0100 [DEBUG] plugin: plugin process exited: path=/home/sirk/repos/simplesurance/devops/terraform/sisu-unified/.terraform/plugins/linux_amd64/terraform-provider-cloudflare_v1.11.0_x4
2019-01-16T14:06:04.934+0100 [DEBUG] plugin: plugin process exited: path=/home/sirk/repos/simplesurance/devops/terraform/sisu-unified/.terraform/plugins/linux_amd64/terraform-provider-google_v1.20.0_x4
2019-01-16T14:06:04.934+0100 [DEBUG] plugin: plugin process exited: path=/usr/local/bin/terraform
2019-01-16T14:06:04.935+0100 [DEBUG] plugin: plugin process exited: path=/home/sirk/repos/simplesurance/devops/terraform/sisu-unified/.terraform/plugins/linux_amd64/terraform-provider-aws_v1.42.0_x4
```

all `zone_id`'s are properly calculated in the DEBUG output so maybe the error is something else ? Too many API requests maybe ? Since we use a lot of cloudflare resources in this project.

**Comment by jacobbednarz** [comment]
> Sadly the Debug-Output of the complete project includes too many secrets and credentials and therefore I can not post it here completely.

Would you be able to scrub the full log of these details? I think it would be useful to see the full log.

> Too many API requests maybe ?

I don't think so. Cloudflare retrurns HTTP 429 when any rate limit thresholds are crossed and here we're getting a 400.

As you were able to isolate this resource and apply it successfully, that leads me to believe there is an issue with the `zone` value getting set. Are you using a variable in your template for the zone name at all?

Something I often do when encountering this type of issue is setup a MITM proxy (like [Charles Proxy](https://www.charlesproxy.com/)) and send the terraform requests through it to inspect the traffic in both directions. This will give you a better idea of what values are being sent and might provide a breadcrumb trail to find the issue.

**Comment by patryk** [comment]
We're checking what happened.

**Comment by sirkjohannsen** [comment]
Here is a scrambled TF_LOG=debug output:
https://s3-eu-west-1.amazonaws.com/sisu-resources/public/sisu/debug/debug_output.log
sadly it was to large for a gist. 
I was unable to capture the traffic to the cloudflare api since there was no way to decode the SSL traffic and terraform would not accept the proxies SSL certificate.

**Comment by jacobbednarz** [comment]
Wow, that's quite some verbose output! Would you mind running the following to see what the `zone_id` is being set as for that particular output?

- Get all the cloudflare resources 
  `terraform state list | grep -i cloudflare`
- Inspect the resource in question for the zone ID
  `terraform state show cloudflare_page_rule.<resource name here> | grep -i zone_id`

From there, you might get a breadcrumb trail as to why the zone ID isn't being found in your account.

>  was unable to capture the traffic to the cloudflare api since there was no way to decode the SSL traffic and terraform would not accept the proxies SSL certificate.

Side note, this is definitely possible as I do it quite a bit when writing new resources or functionality for anything that relies on internal HTTP functionality. Check out the SSL proxying guide (it can be a little fiddley) but definitely works when you get it going.

**Comment by sirkjohannsen** [comment]
since the resource was never created its also no available in the terraform state.

**Comment by jacobbednarz** [comment]
Bugger, I was worried that would be the case 😞 Without inspecting the traffic, I'm not sure what else we can do here. We're running close to 1k of page rules across our production domains and don't see this error so I think it's related to your setup.

**Comment by jacobbednarz** [comment]
Just an update here, I seen this happen internally this week when the user applying the changes didn't have the correct permissions. Are you able to sanity check that for me? It's a bizarre error message but updating the permissions fixed it.

**Comment by kisamoto** [comment]
Came looking as also having the same problem here with the following versions:

```
Terraform v0.12.5
+ provider.cloudflare v1.16.1
```

Doing a simple `terraform plan` gives me multiple errors matching:

```
Error: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1000,\"message\":\"Invalid zone identifier\"}],\"messages\":[],\"result\":null}"
```

However I'm unable to identify the specific resources causing this issue. 

Not sure how I can check permissions? We have an account where nothing has changed (except an update of terraform and the plugin - maybe that's a problem?) since the last run a couple of months ago but now unable to manage our ~300 Cloudflare resources.

**Comment by nrvale0** [comment]
> permission

Can you elaborate as to the correct permissions?

**Comment by vxnick** [comment]
I'm experiencing the same problem with v2.5.0 of this provider.

I generated a new API token with Edit access to all resources in case my existing token was missing something, but this continues to fail.

I wondered if it was failing because the page rule had been manually created before, so I deleted this from the Cloudflare Dashboard and re-ran, but the same error.

Log data from `TF_LOG=debug` can be found [here](https://gist.github.com/vxnick/fe6616840250d950d0973fd251752025) - I've extracted what I think are the relevant bits.

**Comment by jacobbednarz** [comment]
@vxnik the URL it is building has `/zones/example.com` when it should be the `zone_id` following in that route. Be sure to check the [documentation](https://www.terraform.io/docs/providers/cloudflare/r/page_rule.html) for full usage. If you’re still having issues, please open a new issue following the provided template.
