### ISSUE TITLE
Cloudflare Provider: plan Enterprise Website not found amongst the available plans

### ISSUE THREAD

**Issue by dfi69** [terraform-providers/terraform-provider-cloudflare#193]
### Terraform Version
beady$ terraform -v
Terraform v0.11.11
+ provider.cloudflare v1.11.0

### Affected Resource(s)
Please list the resources as a list, for example:
cloudflare_zone

### Terraform Configuration Files
```hcl
variable "cloudflare_email"{
    type = "string"
}
variable "cloudflare_token"{
    type = "string"
}

variable "domain" {
    type = "string"
    default = "mynewdomain.com"
}

provider "cloudflare" {
    email = "${var.cloudflare_email}"
    token = "${var.cloudflare_token}"
    use_org_from_zone = "existingdomain.com"
}
resource "cloudflare_zone" "mynewdomain" {
  zone = "${var.domain}"
  plan = "enterprise"
}
```
### Expected Behavior
Terraform should have provisioned the zone in our Enterprise Cloudflare plan (which we have 1600+ licenses for currently. 

### Actual Behavior
Error: Error applying plan:

1 error(s) occurred:

* cloudflare_zone.mynewdomain: 1 error(s) occurred:

* cloudflare_zone.mynewdomain: Error fetching plans enterprise for zone "REDACTED": plan Enterprise Website not found amongst the available plans

### Steps to Reproduce
1. `terraform apply`

### References
https://github.com/terraform-providers/terraform-provider-cloudflare/issues/191

**Comment by jacobbednarz** [comment]
@dfi69 Are you able to run terraform with the `TF_LOG=DEBUG` environment variable set? This will provide more verbose debugging information for inspection.

**Comment by patryk** [comment]
@dfi69 I believe I've fixed it. Give it a go and let me know.

**Comment by jimbobjim123** [comment]
Tested building the latest dev version of the plugin locally and was able to add a zone to my account on the enterprise plan successfully.
