### ISSUE TITLE
create zone with shared account

### ISSUE THREAD

**Issue by falood** [terraform-providers/terraform-provider-cloudflare#194]
### Terraform Version
v0.10.8

### Affected Resource(s)
Please list the resources as a list, for example:
- cloudflare_zone

### Issue
I'm using such terraform codes to create a zone.

```
resource "cloudflare_zone" "my-zone" {
  zone = "${var.zone_name}"
}
```

My question is I'm using a shared account, I want to create zone for another account.
I checked the cloudflare API https://api.cloudflare.com/#zone-create-zone
the parameter `account` is used for this, but I can't find the way to do it with terraform.

Thanks.

**Comment by jacobbednarz** [comment]
The [`org_id`](https://www.terraform.io/docs/providers/cloudflare/#org_id) parameter allows to you define with account you wish to apply the operations to.

**Comment by falood** [comment]
it works for me
Thanks @jacobbednarz

**Comment by gstotts** [comment]
Is there a way to get the `org_id` as a variable to use?

**Comment by jacobbednarz** [comment]
@gstotts [`OrganizationID`](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/vendor/github.com/cloudflare/cloudflare-go/cloudflare.go#L37) is exported on the [`API`](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/vendor/github.com/cloudflare/cloudflare-go/cloudflare.go#L32) struct. It can be seen in action at places like https://github.com/terraform-providers/terraform-provider-cloudflare/blob/739e4b884bc20cf1355473526d1782b34d18586f/cloudflare/resource_cloudflare_worker_route.go#L195
