### ISSUE TITLE
Use/Allow for CF_API_KEY instead of CLOUDFLARE_TOKEN

### ISSUE THREAD

**Issue by jleclanche** [terraform-providers/terraform-provider-cloudflare#20]
This is a very minor issue and I wouldn't blame you if you decided to close it outright, but one minor issue I've had with this provider is that using `CLOUDFLARE_TOKEN` as the environment variable clashes with my other cloudflare-dependent apps which all use `CLOUDFLARE_API_KEY`.

The `lego` library also uses `CLOUDFLARE_EMAIL` and `CLOUDFLARE_API_KEY`: 
https://github.com/xenolf/lego/blob/82ac43327b01319544c050d5d78a4edeff9565d2/providers/dns/cloudflare/cloudflare.go#L28-L34

**Comment by radeksimko** [comment]
Hi @jleclanche 
Can you mention the other cloudflare-dependent apps (besides lego), so we have more examples? If there's any CloudFlare "standard/convention" (proposed by any official CloudFlare source/library) then we should follow that, but deferring to broad convention used by most 3rd party libraries is 👌  too.

In terms of implementation it sounds like a fairly easy change. We already have providers which accept configuration from multiple ENV variables, see https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/kubernetes/provider.go#L67-L72 for example - contributions are welcomed. 😉

**Comment by elithrar** [comment]
The official Cloudflare library doesn't directly use any env variables, but
references "CF_API_KEY and "CF_API_EMAIL" in the README example -
https://github.com/cloudflare/cloudflare-go#getting-started

**Comment by jleclanche** [comment]
Ah yeah, I just saw flarectl. Although I suspect lego is used a lot more than it.

I don't think there is a standard anywhere, just chance that multiple things use the API_KEY format. I think it'd be nice to settle on one :)

**Comment by jleclanche** [comment]
https://github.com/cloudflare/python-cloudflare also uses CF_API_EMAIL and CF_API_KEY. Maybe this is the standard cloudflare settled on. Should we follow it?

**Comment by jacobbednarz** [comment]
Closing due necromancy and not enough support of the change. Do ping me if someone still wants this would like to take a pass at this one.
