### ISSUE TITLE
Enhancement security configuration. WAF.

### ISSUE THREAD

**Issue by Aleksii** [terraform-providers/terraform-provider-cloudflare#201]
Hi,

Would like to put in a request for create resources which can update Sensitive(off, low, medium, high) and Action(challenge, simulate, block) for package: OWASP ModSecurity Core Rule Set. 
Because if you use waf="on" attacker also can attacked web services.  
When you turn on waf="on" always sensitive configuration  level equals Off and for start defence need to at least have low level. 

### API Cloudflare for change Sensitive and Action
PATCH  Edit Firewall Package
PATCH zones/:zone_identifier/firewall/waf/packages/:identifier

### Version Terraform
Terraform v0.11.11
+ provider.cloudflare v1.11.0

Also I know that default value for sensitivity must be high. But I see that all Off.

**Comment by AshleyPoole** [comment]
I'd also like to see this ability too as it would be useful.

**Comment by Workshop2** [comment]
Also package group would be ideal

**Comment by jacobbednarz** [comment]
This has been fixed via #475 and #476 will cover WAF groups.
