### ISSUE TITLE
resource "cloudflare_load_balancer" has no `enabled` field

### ISSUE THREAD

**Issue by SteveGoldthorpe-Work** [terraform-providers/terraform-provider-cloudflare#208]
### Terraform Version
Terraform v0.11.11
+ provider.cloudflare v1.11.0

### Affected Resource(s)
Please list the resources as a list, for example:
- cloudflare_load_balancer

Although not documented in the API docs, there is a parameter "enabled" which can have the value true or false.  This has the effect of enabling or disabling the load balancer.  The lack of this parameter means we turn the load balancer on or off or ensure it's in a given state.

**Comment by SteveGoldthorpe-Work** [comment]
I think this needs an update in cloudflare-go first.

**Comment by SteveGoldthorpe-Work** [comment]
Raised issue:
https://github.com/cloudflare/cloudflare-go/issues/272

**Comment by jacobbednarz** [comment]
Awesome! Once this lands in `cloudflare-go` we can add it to Terraform. Until then, let's park this.

**Comment by jacobbednarz** [comment]
This had landed upstream so if you want to add it, I'd happily review a PR for it. If not, I can take a look in the coming days.

**Comment by SteveGoldthorpe-Work** [comment]
I've already got the code stashed, will update and create PR tomorrow.

**Comment by jallentech** [comment]
Thanks, this is a really useful piece of work. I was just wondering whether it will be available in the next release and when the next release is likely to happen?

**Comment by jacobbednarz** [comment]
It will be in the next release but no ETA yet on when it will be cut. Shouldn't be too far away though.

**Comment by jallentech** [comment]
That's great, thanks for the update

**Comment by jacobbednarz** [comment]
This was released in [1.13.0](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/CHANGELOG.md#1130-april-12-2019)
