### ISSUE TITLE
'terraform plan' crashes due to the rate limit in the CloudFlare API (1200 requests per 300 seconds)

### ISSUE THREAD

**Issue by drbachler** [terraform-providers/terraform-provider-cloudflare#21]
Hello,
I am having an issue with this terraform provider, due to the rate limit in the CloudFlare API.

CloudFlare limits API requests to 1200 requests in 300 seconds.
https://support.cloudflare.com/hc/en-us/articles/200171456-How-many-API-calls-can-I-make-

```
grep resource foo.bar.tf | wc -l
615
```

### Terraform Version
```
$ terraform -v
Terraform v0.10.7
```
### Panic Output
```
* cloudflare_record.foo: cloudflare_record.foo: Error finding zone "foo.bar": ListZones command 
failed: error from makeRequest: HTTP status 429: content "{\"success\":false,\"errors\":[{\"code\":10100,\"message\":\"More than 1200 requests per 300 seconds
 reached. Please wait and consider throttling your request speed\"}],\"messages\":[],\"result\":null}"
```

### Expected Behavior
`terraform plan` should not crash

### Actual Behavior
`terraform plan` crashes due to the rate limit in the CloudFlare API

### Steps to Reproduce
`terraform plan` 

### References
https://support.cloudflare.com/hc/en-us/articles/200171456-How-many-API-calls-can-I-make-

**Comment by jaygorrell** [comment]
I hit similar issues with the Github provider. Would it be possible in cases like this to use a `list` API endpoint to initialize the provider and check resources against that instead of querying each one individually? It'd be a nice pattern to follow for many providers, really... I'm just not sure how feasible that is.

**Comment by EpiqSty** [comment]
We have the same issue actually,  with only 300 resources, we can't make plan twice after short check and adjustments but have to wait for next 5 minutes, what is really annoying.
The only question - why with 1200 requests for 5 minutes limit we are reaching such threshold on the second run?
Looks like for each resource, terraform plan creates at least 2 API calls, right?
