### ISSUE TITLE
Cloudflare zones datasource is not fetching all zones & doesn't return zone id

### ISSUE THREAD

**Issue by shiftie** [terraform-providers/terraform-provider-cloudflare#211]
### Affected Resource(s)
- cloudflare_zones data source

### Expected Behavior
Should return all zones or at least give more configuration (as API permits: https://api.cloudflare.com/#zone-list-zones), like passing `page`, `per_page`....
Also returned data should provide more information about each zone (e.g.: zone ID) instead just returning the zone name.

### Actual Behavior
If there're more than 20 zones, only the first 20 are returned (I guess because of the default value). 
Each returned zone is just the zone name (no ID).

### Steps to Reproduce
1. Create more than 20 zones in Cloudflare.
1. 
```
data "cloudflare_zones" "test" {
  filter {}
}

output "zones" {
  value = "${data.cloudflare_zones.test.zones}"
}
```

### Important Factoids
This prevents using this data source to dynamically get zone IDs & forces zone ID hard coding.

### References
- [Cloudflare Zones API documentation](https://api.cloudflare.com/#zone-list-zones)

**Comment by jacobbednarz** [comment]
This is a bit of a pain. We don't automatically paginate this response as the underlying `ListZones` function doesn't currently handle pagination buuuuut there is a [TODO to make it paginate](https://github.com/cloudflare/cloudflare-go/blob/master/zone.go#L345-L347) if that's any consolation 😄 . I think there are a couple of stages we can fix this.

The first is a short term. We could up the `per_page` query parameter to always be 1000 and that will get most of the users out of trouble.

```diff
diff --git a/zone.go b/zone.go
@@ -345,7 +345,7 @@ func (api *API) ListZones(z ...string) ([]Zone, error) {
                // TODO: Paginate here. We only grab the first page of results.
                // Could do this concurrently after the first request by creating a
                // sync.WaitGroup or just a channel + workers.
-               res, err = api.makeRequest("GET", "/zones", nil)
+               res, err = api.makeRequest("GET", "/zones?per_page=1000", nil)
                if err != nil {
                        return []Zone{}, errors.Wrap(err, errMakeRequestError)
                }
```

I'm not sure how Cloudflare would feel about accepting this as it would essentially meant that every request that didn't pass in a zone would be requesting all the zones at once and 

The second (and my preferred way) is to introduce pagination and just paginate through all the pages as needed.

I'll have a play with this over the next couple of days and see if I can get a feel for whether the short term is viable for Cloudflare or whether we need to skip straight to the proper fix.

**Comment by shiftie** [comment]
Thx for responding!
Could you just add a `per_page` attribute to `filter` that would be used in the request at first?

**Comment by jacobbednarz** [comment]
I'm afraid that is going to put us in the same position whereby eventually someone is going to hit the `per_page` limit and we'll be advising them to just request more per page and eventually back to solving this.

I'm still leaning towards solving this with pagination in the library itself as it will then future proof this for all users instead of the majority of them.

**Comment by jacobbednarz** [comment]
I'm afraid that is going to put us in the same position whereby eventually someone is going to hit the `per_page` limit and we'll be advising them to just request more per page and eventually back to solving this.

I'm still leaning towards solving this with pagination in the library itself as it will then future proof this for all users instead of some of them. I'm probably being a little greedy here too as we're likely to be closer to that 1000 per page limit than most 😄

**Comment by shiftie** [comment]
If the limit of `per_page` is 1000, I doubt that many people have more than 1000 zones :)

**Comment by jacobbednarz** [comment]
I've introduced pagination upstream in `cloudflare-go` via cloudflare/cloudflare-go#288. Once that lands, we can fix this in the Terraform provider.

**Comment by jacobbednarz** [comment]
@shiftie #275 (which adds the ID + name to the exported attributes to the `cloudflare_zones`) is now up for review. Do you want to check it out and let me know if it solves your use case?

The upstream change to enable pagination of zones has also been merged so you should also get all of your zones without manually paginating.

**Comment by shiftie** [comment]
thx, all seems good for me. 👍

**Comment by shiftie** [comment]
hi, i've recompiled https://github.com/terraform-providers/terraform-provider-cloudflare/commit/06ec05562a5cab929726cb776210c5a970f7dc8f to use it along with TF 0.12 & this still returning a list (not a map) of 20 items (i have more than 20 zones in CF):

```hcl
data "cloudflare_zones" "test" {
  filter {}
}

output "tmp" {
  value = data.cloudflare_zones.test.zones
}
```

**Comment by jacobbednarz** [comment]
Ok, that leads me to believe the newly compiled provider isn’t getting
picked up correctly. Even if the functionality didn’t work, you should be
getting at least 50 zones back as the per_page query parameter was changed.
Can you double check you’re using the new version? A good indicator that
the provider has changed is that you’ll need to perform `terraform init`
again.

**Comment by shiftie** [comment]
Here is what I've done:
- cloned this repo
- ran:
  - `export GO111MODULE=on`
  - `go get github.com/hashicorp/terraform@26c1e40ad` (26c1e40ad was HEAD Thu Apr 4) (note I'm not using  `-u` since in that case, the command was failing on some dependency)
  - `go build`
- copied the produced binary to `~/.terraform.d/plugins`
- removed `.terraform` folder in my Terraform project folder
- ran `terraform init`

**Comment by jacobbednarz** [comment]
I haven't started playing with 0.12 so I don't know what dragons are present there yet. Have you tried running this with `TF_LOG=DEBUG` on? The HTTP transactions will be there and you can confirm the page parameters are getting set.
