### ISSUE TITLE
Support for Argo Smart Routing & Tiered Caching

### ISSUE THREAD

**Issue by martijngonlag** [terraform-providers/terraform-provider-cloudflare#219]
Argo's Smart Routing is a simple toggle on-off type feature, but it would be nice to have this manageable via Terraform nonetheless. 

This is configured via two `PATCH` calls:

1. `PATCH` against `/zones/:zone_id/argo/tiered_caching` 
2. `PATCH` against `/zones/:zone_id/argo/smart_routing` 

In both cases, the payload should be `{"value":"off"}` or `{"value":"on"}`.

**Comment by jacobbednarz** [comment]
Thanks for this! Would you like to take a crack at adding support for this? It will need to be added upstream first though.

**Comment by jacobbednarz** [comment]
I've just checked the API docs for this and can't see anything publicly available so I don't think this is something we can add just yet. I don't want to make a habit of building in functionality that isn't documented publicly as the API is then open to breaking changes without notification.

Let's park this for now and I'll see what Cloudflare say about API support.

**Comment by martijngonlag** [comment]
@jacobbednarz That's fair. I do not know why we (I work at Cloudflare) haven't yet documented this particular API endpoint publicly. I suspect that it's because pretty much everyone usually controls this via the dashboard only. Will check and report back.

**Comment by jacobbednarz** [comment]
Awesome! Sing out if you want me to bug people via email or support tickets 😁

**Comment by jbergstroem** [comment]
Looks like there's at least a stub there now: https://api.cloudflare.com/#argo-smart-routing-patch-argo-smart-routing-setting

Lacks tiered caching info though.

**Comment by jacobbednarz** [comment]
Looks like the PATCH endpoint is missing the payload so it is still no good 😞

**Comment by martijngonlag** [comment]
Looks like we forgot to add the payload, we will get that updated soon. In the meantime, here's the payload: `{"value":"on"}` or `{"value":"off"}`

**Comment by jacobbednarz** [comment]
Upstream support is getting added via cloudflare/cloudflare-go#289

**Comment by jacobbednarz** [comment]
@martijngonlag Support has been added to the provider via #304. Please take a look and let me know if there is anything missing you'd like to see there.
