### ISSUE TITLE
Suport for 'auto' ttl, or documentation thereof

### ISSUE THREAD

**Issue by blaggacao** [terraform-providers/terraform-provider-cloudflare#22]
Without further knowledge and looking at the 'ttl' type ('int') I assume that auto 'ttl' (as in the UI) is not supported, unless it's '0'. It would be nice, would it be either implemented or documented, as in the latter case, it's not obvious.

**Comment by elithrar** [comment]
https://api.cloudflare.com/#dns-records-for-a-zone-create-dns-record

> ttl
> number
> Time to live for DNS record. Value of 1 is 'automatic'
