### ISSUE TITLE
Support respect strong etag in Page Rules

### ISSUE THREAD

**Issue by martijngonlag** [terraform-providers/terraform-provider-cloudflare#223]
Respect Strong Etag is an Enterprise-only functionality that can be enabled or disabled within a Page Rule. I used Cloudflare's cf-terraforming to export my personal configuration. While trying to initialize what I had exported I ran into the following error:

```
Error: Error parsing bossco_page_rule.tf: At:5: Unknown token: 11:5 IDENT respect_strong_etag
```

It looks like respect_strong_etag is not currently listed as a supported parameter under Page Rules (for Terraform). Here are the specific details:

```
{"id":"respect_strong_etag","properties":[{"name":"value","type":"toggle"}]}
```

FWIW: A `GET` against `/zones/:zone_id/pagerules/settings` will return a list of all available parameters and their properties.

**Comment by jacobbednarz** [comment]
👋 @martijngonlag. Looks like there is support for [`respect_strong_etag`](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/cloudflare/resource_cloudflare_page_rule.go#L111-L115) however it is missing from the page rule documentation. Are you able to check if using it with a "on"/"off" value works for your use case? Should be something like this:

```hcl
resource "cloudflare_page_rule" "foobar" {
  zone = "${var.cloudflare_zone}"
  target = "${var.cloudflare_zone}/page"
  priority = 1

  actions = {
    respect_strong_etag = "on"
  }
}
```

**Comment by jacobbednarz** [comment]
Here is a list of the actions that are supported by the provider but not documentated.

**On/off**
- cache_by_device_type
- cache_deception_armor
- origin_error_page_pass_thru
- sort_query_string_for_cache
- respect_strong_etag
- response_buffering
- true_client_ip_header

**String**
- cache_on_cookie

I'll PR these into the documentation shortly.

**Comment by jacobbednarz** [comment]
Documentation updated for these missing actions in #228
