### ISSUE TITLE
Email and token arguments should not be 'required'

### ISSUE THREAD

**Issue by lxop** [terraform-providers/terraform-provider-cloudflare#229]
### Terraform Version
```
Terraform v0.11.10
+ provider.cloudflare v1.7.0
```

### Affected Resource(s)
Provider documentation

### Expected Behavior
The `email` and `token` arguments to the provider should be marked as Optional, with a note that they must be provided, but could also come from environment variables. See the description of the `access_key` and `secret_key` arguments for the AWS provider for an example.

### Actual Behavior
The `email` and `token` arguments are marked as Required.

### References
https://www.terraform.io/docs/providers/aws/index.html

**Comment by jacobbednarz** [comment]
I think we need to clarify some stuff here as the Cloudflare provider doesn't operate in the same way that the AWS provider does for sourcing credentials or configuration.

Under the hood, the AWS SDK has a defined hierarchy where to look which is mainly ignored by the provider and offloaded to the SDK itself. The AWS provider also doesn't do the same sort of configuration in the provider definition either, it's all left to the SDK to manage.

However, in the Cloudflare provider, the arguments are in fact required to interact with the provider and the underlying SDK however, they can be defined in environment variables (which is already noted in the arguments section).

Does this clarify things a bit better?

**Comment by alex-aire** [comment]
Somewhat, I suppose it's a question of what 'required' means. If it means that the information must be supplied in some capacity, then the current documentation makes sense, but if it means that these variables must be supplied to the provider block, then the docs are not quite correct. I have taken the latter interpretation, but it sounds like the former is how the docs are intended?

**Comment by jacobbednarz** [comment]
Correct, the documentation is intended to convey that the details are required in some way and it covers setting it either by the provider configuration or environment variables mentioned. Is there a way you'd word the existing documentation to better communicate this?

**Comment by lxop** [comment]
No, I think how the current docs are reasonable. I simply misinterpreted them.
Thanks
