### ISSUE TITLE
Page Rules for Cloudflare

### ISSUE THREAD

**Issue by lczxpplnzeey** [terraform-providers/terraform-provider-cloudflare#24]
Any possibility that the functionality to setup page rules could be implemented.

**Comment by bronislav** [comment]
@lczxpplnzeey There is open PR for this. Some time ago there were blocking dependencies, but it seems that dependencies have been updated since. Hope page rules will be implemented soon.

**Comment by mwarkentin** [comment]
This was added in 1.0 right?

**Comment by simpsora** [comment]
Lots of progress lately on page rules, most functionality is supported now.

**Comment by patryk** [comment]
Hi, Page Rules are already implemented. Please give it a go and if something is not right, open a new Issue. Thanks!
