### ISSUE TITLE
advanced_ddos attribute isn't editable

### ISSUE THREAD

**Issue by z0rc** [terraform-providers/terraform-provider-cloudflare#243]
https://www.terraform.io/docs/providers/cloudflare/r/zone_settings_override.html#advanced_ddos probably can be dropped, as CloudFlare API doesn't allow to set it. It's tied to plan and cannot be changed in any other way. See https://api.cloudflare.com/#zone-settings-get-advanced-ddos-setting for explanation.

**Comment by jacobbednarz** [comment]
@z0rc are you interested in taking this one on? Happy to review a PR that cleaned this up.

**Comment by jacobbednarz** [comment]
Closed via #253
