### ISSUE TITLE
Add CAA to the valid DNS record types

### ISSUE THREAD

**Issue by roman-vynar** [terraform-providers/terraform-provider-cloudflare#26]
Currently, valid types are "A", "AAAA", "CNAME", "TXT", "SRV", "LOC", "MX", "NS" or "SPF".
CAA is missing.

**Comment by jasonl** [comment]
Cloudflare supports CAA records now, according to: 

https://support.cloudflare.com/hc/en-us/articles/115000310792-Configuring-CAA-Records-

However, the API documentation says that `CAA` isn't a valid record type as yet.

See https://api.cloudflare.com/#dns-records-for-a-zone-create-dns-record

I haven't been able to test if this is actually the case for the API, or whether it's just a lag in getting the documents updated.

**Comment by catsby** [comment]
Support for `CAA` was added in #29
