### ISSUE TITLE
custom_pages resource doesn't save state

### ISSUE THREAD

**Issue by mphoratiu** [terraform-providers/terraform-provider-cloudflare#260]
Hi there,

I have added for our zone in Cloudflare the custom_pages section, performed the terraform plan && terraform apply, the changes were applied in Cloudflare without any errors or issue, but on any following terraform plan, the change still shows as not applied and the resources don't show up in the state.

### Terraform Version
Terraform v0.11.13

### Affected Resource(s)
- cloudflare_custom_pages

### Terraform Configuration Files
```hcl
resource "cloudflare_custom_pages" "basic_challenge" {
  zone_id  = "${var.cloudflare_zone_id}"
  type     = "basic_challenge"
  url      = "https://valid.url.for.custom_page/basic_challenge.html"
  state    = "customized"
}
```

### Debug Output
none available, there's nothing showing that something failed

### Panic Output
n/a

### Expected Behavior
Once applied, it shouldn't show up in all following plans/applies.

### Actual Behavior
It doesn't save the state.
On `terraform plan` it shows:
```terraform
  + cloudflare_custom_pages.basic_challenge
      id:                   <computed>
      state:                "customized"
      type:                 "basic_challenge"
      url:                  "https://valid.url.for.custom_page/basic_challenge.html"
      zone_id:              "123zone_id456"
```
On `terraform apply` it shows:
```terraform
cloudflare_custom_pages.basic_challenge: Creating...
  state:   "" => "customized"
  type:    "" => "basic_challenge"
  url:     "" => "https://valid.url.for.custom_page/basic_challenge.html"
  zone_id: "" => "123zone_id456"

cloudflare_custom_pages.basic_challenge: Creation complete after 3s
```
`terraform state` doesn't show the resource:
```terraform
terraform state show cloudflare_custom_pages.basic_challenge
```
returns nothing and in list it doesn't show-up also.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a custom pages rule, similar to the one I've pasted above
2. `terraform plan`
3. `terraform apply`
4. `terraform state show cloudflare_custom_pages.basic_challenge`

### Important Factoids
The version of the cloudflare provider used is `1.12.0`.
The backend is an s3 bucket.
```hcl
terraform {
  backend "s3" {
    bucket = "bucket_name"
    region = "us-west-2"
  }
}
```

### References
n/a

**Comment by jacobbednarz** [comment]
Have managed to reproduce this when using a zone but not an account wide setting. Will take a look into this one.

**Comment by jacobbednarz** [comment]
@mphoratiu I've found the issue for this one and addressed in #270. Would you mind taking a look and testing it out on your setup to confirm it works for you before we merge it?

**Comment by mphoratiu** [comment]
I did verify, state still is not saved.

**Comment by jacobbednarz** [comment]
Can you outline the steps you took to test this? The changes aren’t tagged in a release yet so you need to build the provider.
