### ISSUE TITLE
Add support for worker KV stores 

### ISSUE THREAD

**Issue by jbergstroem** [terraform-providers/terraform-provider-cloudflare#277]
### Terraform Version
Terraform v0.11.13

### Affected Resource(s)
- cloudflare_worker_script
- cloudflare..

I'd like to express my KV stores as well as binding them to a script via terraform. Couldn't find any references to this in the issues nor in documentation.

**Comment by jbergstroem** [comment]
Relevant docs: https://developers.cloudflare.com/workers/kv/api/

**Comment by jimsorock** [comment]
Any update here?

**Comment by adam-janis** [comment]
cloudflare-go bindings support is merged
https://github.com/cloudflare/cloudflare-go/pull/363

**Comment by garrettgalow** [comment]
@patryk I think we can close this now

**Comment by danielnaab** [comment]
Given that Cloudflare is suggesting one store secrets in Workers KV, it would be nice if the Terraform provider supported adding key/value pairs into a namespace, also.

**Comment by jacobbednarz** [comment]
@danielnaab please create a new issue if this is something you’d like to have a go at submitting a PR for or if you’d like to request a new feature. Be sure to follow the template provided.
