### ISSUE TITLE
Terraform 0.12 cloudflare_access_policy error

### ISSUE THREAD

**Issue by shiftie** [terraform-providers/terraform-provider-cloudflare#278]
### Terraform Version
Terraform v0.12.0-beta1
+ provider.cloudflare v1.12.0-dev20190216h01-dev

### Affected Resource(s)
- cloudflare_access_policy

### Terraform Configuration Files
```hcl
resource "cloudflare_access_policy" "example" {
  application_id = "${cloudflare_access_application.app.id}"
  zone_id        = "${cloudflare_access_application.app.zone_id}"
  name           = "Example"
  include = {
    ip = ["8.8.8.8"]
  }
  decision       = "bypass"
}
```

### Expected Behavior
A new Cloudflare Access policy should have been created.

### Actual Behavior
Seems that `include` block is "invisible".
```
  on ../../../modules/cloudflare/access/main.tf line 21, in resource "cloudflare_access_policy" "example":
  21: resource "cloudflare_access_policy" "example" {

At least 1 "include" blocks are required.
```

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
Config war working on TF 0.11.
Cloudflare provider was taken from http://terraform-0.12.0-dev-snapshots.s3-website-us-west-2.amazonaws.com/terraform-provider-cloudflare/

**Comment by shiftie** [comment]
edit: `include seems to be a block now & not an attribute anymore :)`

**Comment by jacobbednarz** [comment]
[`terraform 0.12upgrade`](https://www.terraform.io/docs/commands/0.12upgrade.html) should have updated this. Did you use this or another method?

**Comment by shiftie** [comment]
that didn't work.
i've done it manually.

**Comment by jacobbednarz** [comment]
Have you happened to open an issue with Terraform itself? If not, I can give it a try closer to the release date and open an issue to confirm.

**Comment by shiftie** [comment]
No I didn't, wasn't sure if it was expected to be a manual process.
