### ISSUE TITLE
Unable to create PTR records

### ISSUE THREAD

**Issue by jakubgs** [terraform-providers/terraform-provider-cloudflare#283]
### Terraform Version
```
Terraform v0.11.11
+ provider.cloudflare v1.11.0
...
```
### Affected Resource
`cloudflare_record`

### Error
```
* cloudflare_record.test-ptr: 1 error(s) occurred:

* cloudflare_record.test-ptr: Error validating record type "PTR": Invalid type "PTR". Valid types are "A", "AAAA", "CNAME", "TXT", "SRV", "LOC", "MX", "NS", "SPF", "CAA", "CERT", "DNSKEY", "DS", "NAPTR", "SMIMEA", "SSHFP", "TLSA" or "URI".

```

### Expected Behavior
The Web UI allows me to create `PTR` records, but the Terraform resource doesn't.

**Comment by jacobbednarz** [comment]
@jakubgs Can you please provide an example of how you're defining the resource for a reproduction test case?

**Comment by jakubgs** [comment]
```terraform
resource "cloudflare_record" "test" {
  domain  = "example.org"
  name    = "test"
  type    = "PTR"
  proxied = false
  value   = "1.2.3.4"
}
```
I also tried using `4.3.2.1.in-addr.arpa` as the value but the error is the same.

**Comment by jacobbednarz** [comment]
Awesome, thanks. As I suspected but just wanted to be certain 😄 

Addressed in #284

**Comment by jakubgs** [comment]
So which is the correct form? The raw IP or the reversed one? Or both?

**Comment by jacobbednarz** [comment]
The purpose of a PTR record is essentially do the reverse of an A record. PTR records are IPs or IP ranges to a hostname (generally for things like email). For example `10.27/1.168.192.in-addr.arpa. 1800 PTR mail.example.com`.

However, Cloudflare doesn't support it for reverse DNS resolution but instead used for forward DNS resolution. Check out https://support.cloudflare.com/hc/en-us/articles/360019093151 for more details on this.
