### ISSUE TITLE
Add Logpush acceptance test token as TeamCity env var

### ISSUE THREAD

**Issue by zackproser** [terraform-providers/terraform-provider-cloudflare#288]
Create a Logpush ownership challenge token for the configured acceptance test zone and add it to the hashicorp TeamCity build as an env var so that the Logpush acceptance tests can run successfully.

### Affected Resource(s)
Please list the resources as a list, for example:
- resource_cloudflare_logpush_job_test.go

**Comment by zackproser** [comment]
new env vars introduced by the Logpush resource are: 

- ```CLOUDFLARE_ZONE_ID```
- ```CLOUDFLARE_LOGPUSH_OWNERSHIP_TOKEN```

**Comment by jacobbednarz** [comment]
@zackproser Are you 👌 to get this to the Hashicorp folks securely? Or would you like me to follow it up?

**Comment by zackproser** [comment]
@jacobbednarz Yes, I will take care of this. Apologies for the delay.

**Comment by jacobbednarz** [comment]
No sweat! Thanks for getting back to me.

**Comment by jacobbednarz** [comment]
This has been completed.
