### ISSUE TITLE
Update Rate Limit Docs

### ISSUE THREAD

**Issue by jamfish** [terraform-providers/terraform-provider-cloudflare#292]
Howdy Devs,

Submitting this because I just had very long issue that could've been solved with documentation note, and I can't cut a PR for this. 

Could it be updated so that https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/website/docs/r/rate_limit.html.markdown reflects:
- That there's set defaults for the 'period' argument (support noted 60, 3600, or 86400 seconds)
- The `challenge` and `challenge_js` modes for the action block (reflecting #174)?

Thanks,

Jam

**Comment by jacobbednarz** [comment]
>     * That there's set defaults for the 'period' argument (support noted 60, 3600, or 86400 seconds)

It's not this simple unfortunately. Different plans have different limits so the provider validation can only account one of them (which we've chosen as Enterprise as that is the outer limits of all). I don't know how we can better represent this in the documentation without doing something like this for all properties:

> Valid values:
>   - Enterprise: 10
>   - Paid: 5
>   - Free: 1

>     * The `challenge` and `challenge_js` modes for the action block (reflecting #174)?

I think #174 is the wrong reference here as it's for zone/zone_id changes but updating the `actions.mode` documentation is 👍.

**Comment by jacobbednarz** [comment]
PR'd the changes the second bit in #293

**Comment by jamfish** [comment]
Thanks for this @jacobbednarz! Yeah, was totally wrong as I meant #171 and #172.
