### ISSUE TITLE
Add WAF Packages to Cloudflare Terraform

### ISSUE THREAD

**Issue by mbullock1986** [terraform-providers/terraform-provider-cloudflare#325]
For WAF rules to be enabled or disabled via terraform the package needs to be enabled on Cloudflare. Packaged include for example Cloudflare Specials, Cloudflare Plone etc. 

Currently, you have to enable these rulesets via API or UI before you can apply a configuration for the WAF rules.

Each package has a package ID for example:

`{
  "result": {
    "id": "c8485e461f935bead889fa0fe87dd76e",
    "name": "Cloudflare Php",
    "description": "This ruleset should only be enabled if PHP is used for this domain. It contains additional rules that complement the technology-specific protections provided by similar rules in the OWASP ruleset.",
    "mode": "on",
    "package_id": "1e334934fd7ae32ad705667f8c1057aa",
    "rules_count": 13,
    "modified_rules_count": 13
  },
  "success": true,
  "errors": [],
  "messages": []
}`

so would imagine something like the following in the .tf file:

`resource "cloudflare_waf_rule" "identifier_org_WP_Package" {
    package_id = "1e334934fd7ae32ad705667f8c1057aa"
    zone = "domain.com"
    mode = "on"
}`

is required

**Comment by jimbobjim123** [comment]
One small terminology point. These are WAF Rule "Groups" not "Packages" - https://api.cloudflare.com/#waf-rule-groups-list-rule-groups

`resource "cloudflare_waf_rule" "identifier_org_WP_Group" { package_id = "1e334934fd7ae32ad705667f8c1057aa" zone = "domain.com" mode = "on" }`

**Comment by vincentheet** [comment]
Seems like this is getting implemented in https://github.com/terraform-providers/terraform-provider-cloudflare/pull/476
