### ISSUE TITLE
"Invalid value for zone setting, opportunistic_onion\" when destroying cloudflare_zone_settings_override

### ISSUE THREAD

**Issue by sixcorners** [terraform-providers/terraform-provider-cloudflare#346]
Hi there,

### Terraform Version
Terraform v0.11.13
+ provider.cloudflare v1.13.0

### Affected Resource(s)
- cloudflare_zone_settings_override

### Terraform Configuration Files
```hcl
resource "cloudflare_zone_settings_override" "settings" {
  name = "${var.cloudflare_zone}"

  settings {
    always_use_https    = "on"Hi there,


    browser_cache_ttl   = 0
    ssl                 = "strict"
    challenge_ttl       = 86400
    min_tls_version     = "1.2"
    tls_1_3             = "zrt"
    email_obfuscation   = "off"
    server_side_exclude = "off"
    hotlink_protection  = "off"
    tls_client_auth     = "on"

    security_header {
      enabled            = true
      max_age            = 31536000
      include_subdomains = true
      preload            = true
      nosniff            = true
    }
  }
}
# should I include all the other files too?
```

### Expected Behavior
No errors to occur.

### Actual Behavior
What actually happened?
* cloudflare_zone_settings_override.settings (destroy): 1 error(s) occurred:

* cloudflare_zone_settings_override.settings: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1007,\"message\":\"Invalid value for zone setting, opportunistic_onion\"}],\"messages\":[],\"result\":null}"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform destroy`

**Comment by jacobbednarz** [comment]
@sixcorners Are you able to edit the description to remove the parts from the pull request template that you've replaced or don't need? This looks like a mash of the template and your report.

**Comment by sixcorners** [comment]
Couldn't the template include comments that remove the parts you don't want to show in the ticket? Which parts of this stuff should stay?

**Comment by jacobbednarz** [comment]
Are you able to confirm this is still the case on the latest version provider? There have been a few improvements in this space since this was opened.
