### ISSUE TITLE
Global variables (email and token) possibly not working

### ISSUE THREAD

**Issue by markdorrill** [terraform-providers/terraform-provider-cloudflare#354]
### Terraform Version
Terraform v0.11.13
+ provider.cloudflare v1.14.0
+ provider.random v2.1.2

### Affected Resource(s)
- provider "cloudflare"

### Terraform Configuration Files
```
- Set global variables:
  - CLOUDFLARE_EMAIL="email@domain.tld"
  - CLOUDFLARE_TOKEN="<token-hash>"
```

```hcl
variable "domain" {
  default = "domain.com"
}

resource "random_id" "id" {
  byte_length = 3
}

resource "cloudflare_record" "www" {
  domain  = "${var.domain}"
  name    = "www-${random_id.id.hex}"
  value   = "203.0.113.10"
  type    = "A"
  proxied = true
}

resource "cloudflare_record" "bucket" {
  domain  = "${var.domain}"
  name    = "another-bucket-${random_id.id.hex}"
  value   = "c.storage.googleapis.com"
  type    = "CNAME"
  proxied = true
}
```

### Expected Behavior
According to the documentation the when the global variables; **CLOUDFLARE_EMAIL** & **CLOUDFLARE_TOKEN** are set, these functions should provide the required credentials (**but could be a documentation gap**).

### Actual Behavior
Terraform _plan_ and _apply_ prompts for user input (_email and token_)

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
Running on GCP Cloud Shell instance

### References
- [GH-229](https://github.com/terraform-providers/terraform-provider-cloudflare/issues/229)

**Comment by jacobbednarz** [comment]
I've taken a look at this one and unfortunately I'm unable to replicate with your proposed scenario. For posterity.

##### `example.tf`

```hcl
resource "cloudflare_record" "foobar" {
  domain = "my-domain.com"
  name   = "test"
  value  = "example.com"
  type   = "CNAME"
  ttl    = 400
}
```

#### Without environment variables

```
$ terraform plan
provider.cloudflare.email
  A registered Cloudflare email address.

  Enter a value: ^C
Interrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...

Error: Error asking for user input: 1 error(s) occurred:

* provider.cloudflare: Error configuring cloudflare: email: interrupted
```


#### With environment variables

```
$ CLOUDFLARE_EMAIL="test@example.com" CLOUDFLARE_TOKEN="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + cloudflare_record.foobar
      id:          <computed>
      created_on:  <computed>
      domain:      "my-domain.com"
      hostname:    <computed>
      metadata.%:  <computed>
      modified_on: <computed>
      name:        "test"
      proxiable:   <computed>
      proxied:     "false"
      ttl:         "400"
      type:        "CNAME"
      value:       "example.com"
      zone_id:     <computed>


Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

I would double check that your environment variables are indeed being to the Terraform process (using something like `env | grep -i cloudflare`) or pass them in as input variables using the provider configuration.

```hcl
provider "cloudflare" {
  email = "${var.cloudflare_email}"
  token = "${var.cloudflare_token}"
}

variable "cloudflare_email" {}
variable "cloudflare_token" {}

resource "cloudflare_record" "foobar" {
  domain = "my-domain.com"
  name   = "test"
  value  = "example.com"
  type   = "CNAME"
  ttl    = 400
}
```

```
terraform plan -var "cloudflare_email=blah" -var "cloudflare_token=blah"
```

**Comment by 3j0s** [comment]
Greetings!

I'm using this configuration
 ``
Terraform v0.12.16
+ provider.cloudflare v2.1.0
+ provider.gitlab v2.3.0
``
With the configuration provider as follow:
``
provider "cloudflare" {
  version    = "~> 2.0"
  email      = var._cloudflare_account_email_
  api_key    = var._cloudflare_account_token_
  account_id = var._cloudflare_account_id_
}
``

And i'm still receiving this error:

`` 
Error: Missing required argument

The argument "token" is required, but was not set.
`` 

I tried to set: CLOUDFLARE_API_KEY and renamed CLOUDFLARE_ORG_ID to CLOUDFLARE_ACCOUNT_ID environment variables but nothing.
