### ISSUE TITLE
cloudflare_ip_ranges doesn't seem to need authentication

### ISSUE THREAD

**Issue by sixcorners** [terraform-providers/terraform-provider-cloudflare#362]
It would be nice if I could use cloudflare_ip_ranges without authenticating with cloudflare.

**Comment by sixcorners** [comment]
I'm kind of not sure this is possible. I don't really want email and token to be made optional parameters to the provider.

**Comment by jacobbednarz** [comment]
There isn’t really a good way of doing this without making the credentials optional and I believe that will cause more issues than what introducing this would enable. 

I’m happy to review a PR if you have any thoughts.
