### ISSUE TITLE
cloudflare_record recreation when using any name with uppercase letters

### ISSUE THREAD

**Issue by catsby** [terraform-providers/terraform-provider-cloudflare#39]
`cloudflare_record` allows uppercase `name` values, but it seems the Cloudflare API converts it to lower case(?). As a result, using an upper case letter in a record `name` will result in future `terraform plan` runs to indicate a recreation of the resource.

### Affected Resource(s)

- cloudflare_record

### Terraform Configuration Files
```hcl
resource "cloudflare_record" "vpn" {
  domain   = "<your domain here>"
  name     = "tftestingsubV616" # note the capital V
  value    = "52.39.212.111"
  type     = "A"
  ttl      = 1
  priority = 80
  proxied  = true
}
```

### Debug Output

```
-/+ cloudflare_record.vpn (new resource required)
      id:          "5db4d077f4b071b5a276407f666495ae" => <computed> (forces new resource)
      [...]
      name:        "tftestingsubv616" => "tftestingsubV616" (forces new resource)
      [...]
```

### Expected Behavior

- Terraform should warn on upper case usage, or automatically convert to lowercase for storing in state

### Actual Behavior

- `terraform plan` wants to recreate the record

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

1. `terraform apply` the provided config
1. `terraform plan` will show a recreation

**Comment by prdonahue** [comment]
@benjvi can you please address this when you return?
