### ISSUE TITLE
page_rule.browser_cache_ttl modification fails

### ISSUE THREAD

**Issue by Caspervw** [terraform-providers/terraform-provider-cloudflare#393]
Hi there,

We're running into an issue where the string value of browser_cache_ttl is preventing us from updating our page rules. The conversion to a number, before sending it to the API, seems to be the issue. Creation worked, but modifying/updating breaks.

### Terraform Version
Terraform v0.12.3
provider.cloudflare v1.16.0

### Affected Resource(s)
Please list the resources as a list, for example:
- page_rule.browser_cache_ttl

### Terraform Configuration Files
```hcl
resource "cloudflare_page_rule" "cache_html" {
	zone = "${var.domain}"
	target = "*${var.domain}/*"

	status = "active"

	priority = 1
	actions {
                browser_cache_ttl = 3600
		cache_level = "cache_everything"
		edge_cache_ttl = 3600
		cache_by_device_type = "on"
	}
}
```
### Expected Behavior
The page rule should become active, but browser_cache_ttl as a string is preventing this.

```hcl
  ~ resource "cloudflare_page_rule" "cache_html" {
        id       = "xxx"
        priority = 1
      ~ status   = "disabled" -> "active"
        target   = "xxx"
        zone     = "xxx"
        zone_id  = "xxx"

        actions {
            always_use_https     = false
            browser_cache_ttl    = "3600"
            cache_by_device_type = "on"
            cache_level          = "cache_everything"
            disable_apps         = false
            disable_performance  = false
            disable_railgun      = false
            disable_security     = false
            edge_cache_ttl       = 3600
        }
    }
```

### Actual Behavior
```plain
Error: Failed to update Cloudflare Page Rule: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1004,\"message\":\"Page Rule validation failed: See messages for details.\"}],\"messages\":[{\"code\":1,\"message\":\".settings[2].value: TTL values must be whole numbers only\",\"type\":null}],\"result\":null}"
```

Removing the browser_cache_ttl will make it work
```hcl
~ resource "cloudflare_page_rule" "cache_html" {
	id       = "xxx"
	priority = 1
	status   = "disabled"
	target   = "xxx"
	zone     = "xxx"
	zone_id  = "xxx"

	~ actions {
		always_use_https     = false
		- browser_cache_ttl    = "3600" -> null
		cache_by_device_type = "on"
		cache_level          = "cache_everything"
		disable_apps         = false
		disable_performance  = false
		disable_railgun      = false
		disable_security     = false
		edge_cache_ttl       = 3600
	}
}
```

### Steps to Reproduce
1. Create a disabled page rule, with the above configuration
2. `terraform apply`
3. Change the status to active
4. `terraform apply`

**Comment by jacobbednarz** [comment]
Can you try using master for now? This was addressed and merged this morning however we are just confirming all bases are covered before cutting a patch release for this one.

**Comment by Caspervw** [comment]
Thanks, I'm currently occupied with the migration to Cloudflare. Will wait for the new release version to test it.
