### ISSUE TITLE
Support use of API tokens (in public beta) in addition to API Keys

### ISSUE THREAD

**Issue by AgrimPrasad** [terraform-providers/terraform-provider-cloudflare#419]
Cloudflare has very recently made API tokens available as a public beta. These are different than the previously available API keys, and allow more granular access to the Cloudflare API endpoints, e.g. to only certain websites controlled by an account, or to only certain functionality such as cache-purge.

API tokens follow the following format which is different than the one for API keys: `Authorization: Bearer <token>`

API documentation: https://api.cloudflare.com/#getting-started-requests

These are configurable at https://dash.cloudflare.com/profile/api-tokens :

<img width="898" alt="Screenshot 2019-07-18 at 11 02 33 PM" src="https://user-images.githubusercontent.com/6386887/61468744-8e678d00-a9b0-11e9-91ea-1f823851e7a5.png">

Furthermore, adding support for API token will also mean that the previously misnamed `token` in the Terraform Cloudflare provider should be corrected to `key` instead:

<img width="847" alt="Screenshot 2019-07-18 at 11 09 45 PM" src="https://user-images.githubusercontent.com/6386887/61469120-3f6e2780-a9b1-11e9-9637-09137625382f.png">

**Comment by jacobbednarz** [comment]
Thanks for this one! The foundations for this have already been merged into `cloudflare-go` via cloudflare/cloudflare-go#326 and the discussion on the naming collision have been started at #417. We’ve been running the closed beta for some time internally so once the naming is ironed out, I’ll push up that change from our fork and we’ll have support.

**Comment by jbergknoff-rival** [comment]
Any movement on this?

**Comment by patryk** [comment]
Added in #450, but we'll keep the old name for API Key for backwards compatibility. We'll do a proper cleanup in next major release.
