### ISSUE TITLE
Add Origin CA Certificate resource

### ISSUE THREAD

**Issue by snoopdouglas** [terraform-providers/terraform-provider-cloudflare#433]
As per [this comment](https://github.com/terraform-providers/terraform-provider-cloudflare/issues/224#issuecomment-509979257) on #224, I'd like to be able to provision origin certificates from Terraform. This would enable end-to-end setup for Cloudflare's 'Full' encryption offering.

As per [the API](https://api.cloudflare.com/#origin-ca-properties), I'd imagine syntax would be similar to the following:

```hcl
resource "cloudflare_origin_ca_certificate" "my_certificate" {
  zone = "${cloudflare_zone.my_site.zone}"
  hostnames = [
    "example.com",
    "*.example.com",
  ]
  requested_validity = 5475
  request_type = "origin-rsa" # optional
  csr = "-----BEGIN CERTIFICATE REQUEST----- ..." # optional
}
```

**Comment by acdha** [comment]
This would be extremely useful in conjunction with other cloud service certificate stores — in particular, the AWS ACM interface only supports looking up certificates by the domain name (i.e. the SAN names are not included) so it would be really useful to be able to have Terraform generate an origin cert with domain=x, alternate_names=[y] and deterministically populate ACM using names which are more reliable than the random ordering provided by the Cloudflare console.

**Comment by wburnett** [comment]
It looks like this was merged in a couple of weeks ago (and thank you to all who made it happen!), question on the documentation involved: https://www.terraform.io/docs/providers/cloudflare/r/origin_ca_certificate.html 

It says "This resource requires you use your Origin CA Key as the api_user_service_key." Does this mean to use the private key from the origin CA as the api_user_service_key? Or something else? I'm a little befuddled here.

**Comment by player-two** [comment]
Hi @wburnett , the Origin CA Key can be found on the same page as other api tokens.  Once logged into the dashboard, go to your profile and look in the API Tokens tab.  You should see that and the Global API Key right next to each other near the bottom.

**Comment by wburnett** [comment]
Oh, oops! Thanks for the save, I’m still getting used to Cloudflare. Have a great New Year!

**Comment by player-two** [comment]
You bet, and likewise! :100:
