### ISSUE TITLE
Support HSTS option on zones

### ISSUE THREAD

**Issue by snoopdouglas** [terraform-providers/terraform-provider-cloudflare#434]
I'd like to be able to configure Cloudflare's HSTS offering from Terraform.

<img width="890" alt="Screenshot 2019-07-31 at 10 31 41" src="https://user-images.githubusercontent.com/4892574/62201071-8cbda200-b37e-11e9-86d4-a3f49a4e3977.png">

In the web dashboard, the following options are shown:

<img width="621" alt="Screenshot 2019-07-31 at 10 31 56" src="https://user-images.githubusercontent.com/4892574/62201084-91825600-b37e-11e9-9e39-8f1bfd729c13.png">

**Comment by jacobbednarz** [comment]
This is configurable under [`zone_settings override`](https://www.terraform.io/docs/providers/cloudflare/r/zone_settings_override.html#security_header)

**Comment by yamin-oanda** [comment]
Thank you for the pointers. Just fyi the Terraform link above is broken, the new one is: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/zone_settings_override
