### ISSUE TITLE
TF plan fails - API ratelimit reached

### ISSUE THREAD

**Issue by Constantin07** [terraform-providers/terraform-provider-cloudflare#435]
### Terraform Version
0.11.14

### Affected Resource(s)
Please list the resources as a list, for example:
- cloudflare_record.txt

### Terraform Configuration Files
```hcl
resource "cloudflare_record" "txt" {
  domain  = "${var.domain}"
  name    = "${var.dns_record}"
  proxied = "false"
  type    = "TXT"
  value   = "some value"
}
```

### Expected Behavior
Records created.
It would be nice to have a retry logic - use `timeout` parameter like for AWS resources so we can define a customisable period of time, e.g. 10, 20 mins to wait/retry before failing.

### Actual Behavior
Terraform plan fails because API rate limit is reached.

### Steps to Reproduce
1. `terraform apply`
```
[2019-07-31T12:55:49.813Z] Error: Error refreshing state: 4 errors occurred:

* cloudflare_record.txt: 1 error occurred:
* cloudflare_record.txt: cloudflare_record.txt: error from makeRequest: HTTP status 429: content "{\"success\":false,\"errors\":[{\"code\":10100,\"message\":\"More than 1200 requests per 300 seconds reached. Please wait and consider throttling your request speed\"}],\"messages\":[],\"result\":null}"

* cloudflare_page_rule.https: 1 error occurred:
* cloudflare_page_rule.https: cloudflare_page_rule.https: Error finding page rule "aad28e4e88c481107d6c5e2488338754": error from makeRequest: HTTP status 429: content "{\"success\":false,\"errors\":[{\"code\":10100,\"message\":\"More than 1200 requests per 300 seconds reached. Please wait and consider throttling your request speed\"}],\"messages\":[],\"result\":null}"

* cloudflare_page_rule.host_header: 1 error occurred:
* cloudflare_page_rule.host_header: cloudflare_page_rule.host_header: Error finding page rule "024f12c8fe213b68483add266606e9dd": error from makeRequest: HTTP status 429: content "{\"success\":false,\"errors\":[{\"code\":10100,\"message\":\"More than 1200 requests per 300 seconds reached. Please wait and consider throttling your request speed\"}],\"messages\":[],\"result\":null}"

* cloudflare_record.this: 1 error occurred:
* cloudflare_record.this: cloudflare_record.this: error from makeRequest: HTTP status 429: content "{\"success\":false,\"errors\":[{\"code\":10100,\"message\":\"More than 1200 requests per 300 seconds reached. Please wait and consider throttling your request speed\"}],\"messages\":[],\"result\":null}"

```

### References
https://support.cloudflare.com/hc/en-us/articles/200171456-How-many-API-calls-can-I-make-?flash_digest=4b0bb477e8e49d49353759d9d39524011584603b

**Comment by jacobbednarz** [comment]
Avoiding the rate limiting is already possible with the Terraform provider using the [`rps`](https://www.terraform.io/docs/providers/cloudflare/#rps), [`min_backoff`](https://www.terraform.io/docs/providers/cloudflare/#min_backoff) and [`max_backoff`](https://www.terraform.io/docs/providers/cloudflare/#max_backoff) configuration options.

**Comment by jacobbednarz** [comment]
Additionally, if your hitting these rate limits because you've grouped a bunch of resources together, I'd recommend breaking them up into smaller components (dns, page rules, etc)

**Comment by Constantin07** [comment]
Thanks @jacobbednarz I've overlooked those provider settings.
