### ISSUE TITLE
Import is broken due to cloudflare-go's API token change

### ISSUE THREAD

**Issue by analytically** [terraform-providers/terraform-provider-cloudflare#444]
Getting

```Error: Error creating new Cloudflare client: invalid credentials: key & email must not be empty```

when running `terraform import cloudflare_zone.xxx <id>`

**Comment by patryk** [comment]
Could you provide information according to the template, please?
https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by jacobbednarz** [comment]
Closing due to lack of information. Please open a new ticket following the [ISSUE TEMPLATE](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/.github/ISSUE_TEMPLATE.md) should this still be an issue.
