### ISSUE TITLE
cloudflare_page_rules are added before they are deleted

### ISSUE THREAD

**Issue by sixcorners** [terraform-providers/terraform-provider-cloudflare#458]
### Terraform Version
Terraform v0.12.7
+ provider.cloudflare v1.17.1

### Affected Resource(s)
- cloudflare_page_rule

### Expected Behavior
I should have ended up with the three rules I defined in terraform.

### Actual Behavior
Error: Failed to create page rule: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1008,\"message\":\"Page Rule limit has been met\"}],\"messages\":[],\"result\":null}"

### Steps to Reproduce
1. Have a free cloudflare account
1. Add a page rule
1. Replace that page rule with three others
1. `terraform apply`

### Important Factoids
I can only have three cloudflare_page_rules at a time. It would be nice if terraform deleted cloudflare_page_rules that don't exist anymore before adding new ones so that I don't run out during the apply process.

**Comment by jacobbednarz** [comment]
This currently isn’t possible due to the way the lifecycle of a resource works (in-place updates, reordering, etc). Closing for now until such time this becomes a more requested feature and then we can spend some more investigation effort on a potential workaround.

**Comment by NiklasA** [comment]
Hi @jacobbednarz, we currently have the same issue as stated above. Is there any plan to implement that feature in the near future?

**Comment by jacobbednarz** [comment]
Nothing new. It’s the way lifecycle management is expected to work in Terraform and I’d rather not stray from the golden path without a really good use case (which we don’t have here). 

If I were you, I’d either:

- Use a two phase approach where you delete unused rules first; or
- If you’re consistently hitting the page rule limit, look at getting some more entitlements assigned to your account to alleviate the need to delete and then create.
