### ISSUE TITLE
Page Rule - Host Header Override

### ISSUE THREAD

**Issue by meirf** [terraform-providers/terraform-provider-cloudflare#46]
Many page rule options are supported, but I [don't see anything](https://www.terraform.io/docs/providers/cloudflare/r/page_rule.html) for [overriding host headers](https://support.cloudflare.com/hc/en-us/articles/206652947-Using-Page-Rules-to-Re-Write-Host-Headers).

Was is left out because of a technical reason or because it's perceived as less important than the ones that were implemented?

**Comment by prdonahue** [comment]
Wasn't intentional. We'll get added to our next for the next revision.

**Comment by nmasur** [comment]
We're also missing Bypass Cache on Cookie.

**Comment by SteveGoldthorpe-WDFC** [comment]
And Resolve Override.

**Comment by meirf** [comment]
Steve, thanks for creating a [PR](https://github.com/terraform-providers/terraform-provider-cloudflare/pull/61) for this.

Would anyone like to review it?

**Comment by simpsora** [comment]
All three of those options were fixed in https://github.com/terraform-providers/terraform-provider-cloudflare/pull/76 and merged a couple of days ago.

**Comment by SteveGoldthorpe-Work** [comment]
Yes, nice of them to merge in a brand new PR ignoring existing PRs and not fixing all the issues.

**Comment by simpsora** [comment]
It also seems to treat `host_header_override` as an OnOff field rather than a string field :(

**Comment by SteveGoldthorpe-Work** [comment]
Yip just spotted that.  Quality.

**Comment by simpsora** [comment]
Opened https://github.com/terraform-providers/terraform-provider-cloudflare/pull/83 to fix the two broken override actions.

**Comment by patryk** [comment]
Ops! Sorry about that! I recently took maintainership of the project. Will try to be more careful and not that trigger happy.
