### ISSUE TITLE
Cloudflare Access Rules Created in State via Terraform but does not exist in Cloudflare.

### ISSUE THREAD

**Issue by kevin-kim-bouqs** [terraform-providers/terraform-provider-cloudflare#466]
**Terraform Version:**
v0.11.13

**Provider Version:**
v1.18.1

**Affected Resources:**
cloudflare_access_rule

**Terraform Configuration**
```
resource "cloudflare_access_rule" "TEST" {
        configuration {
                target = "ip"
                value = "8.8.8.8"
         }
        mode = "whitelist"
        notes = "test
}
```

**Expected Behavior**
The above code creates a resource successfully - I can see it when I list state resources.
Unfortunately, there is no actual access rule created in Cloudflare - confirmed via API and GUI. A resource does get provisioned - is this a ghost resource?

Here is a note from terraform documentation: 

Note: If both zone and zone_id are empty, then access rule will be set to User's or Organization's account and apply to all their zones.

Can we decide whether the access rule will be set to User or Organization? We want this set via Organization and not just a specific zone.  Maybe this is where the issue is coming from.

**Comment by jacobbednarz** [comment]
Here is the logic for this decision

https://github.com/terraform-providers/terraform-provider-cloudflare/blob/bcee85cb5a9ab0f38cebdf5afd6ab9ad0ed33bdf/cloudflare/resource_cloudflare_access_rule.go#L91-L108

**Comment by fmalykh** [comment]
Hi,
I'm having exactly the same issue. Is there any way to get an example or non-programmatical explanation on this? :)
