### ISSUE TITLE
Support CORS settings

### ISSUE THREAD

**Issue by analytically** [terraform-providers/terraform-provider-cloudflare#473]
Currently the Terraform provider doesn't support the CORS settings for a CloudFlare Access application.

![image](https://user-images.githubusercontent.com/254434/65349916-6a375080-db99-11e9-8eb9-a9734c92dfdf.png)

**Comment by jacobbednarz** [comment]
This currently isn’t exposed via the API so we can’t add functionality until that lands. Do you mind raising a support ticket with Cloudflare requesting this?

**Comment by jacobbednarz** [comment]
I've opened 1853883 to have this looked at from the Cloudflare side.

**Comment by jacobbednarz** [comment]
CORS support has landed in the documentation today so once this is added upstream, we can add the support for it in Terraform.

**Comment by jacobbednarz** [comment]
cloudflare/cloudflare-go#485 is implementing this and then we can add Terraform support for it.
