### ISSUE TITLE
After upgrading to 2.0 getting "insufficient permissions" with Global API key

### ISSUE THREAD

**Issue by pjjohnstone** [terraform-providers/terraform-provider-cloudflare#484]
We've set the `CLOUDFLARE_API_KEY` and `CLOUDFLARE_EMAIL` env vars and are trying to run a plan and we see the following error: `Error: error listing Zone: error from makeRequest: HTTP status 403: insufficient permissions`

The API key in question is our global API key.

The resource the config is failing on is this:
```hcl
data "cloudflare_zones" "cf_zones" {
  filter {
    name = var.zone
  }
}
```

### Expected Behavior
Plan should succeed

### Actual Behavior
Plan fails with the following error: `Error: error listing Zone: error from makeRequest: HTTP status 403: insufficient permissions`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by jacobbednarz** [comment]
This isn’t an issue with the provider. To debug this, you’ll need to look at the following:

- Does your account have the correct permissions to perform the operation in question?
- Are you calling the correct URL with the correct account ID or zone ID?

You can use the `TF_LOG=DEBUG` environment variable to see the calls and perform deeper inspection.

Best of luck!

**Comment by pjjohnstone** [comment]
The same email/API key was performing all these operations just fine before we upgraded the provider.

**Comment by garrettgalow** [comment]
Review this: https://www.terraform.io/docs/providers/cloudflare/guides/version-2-upgrade.html My hunch is one of the other changes like how you specify which account to use is probably leading to the issue.
