### ISSUE TITLE
cloudflare_load_balancer `zone` param required even when `zone_id` param set

### ISSUE THREAD

**Issue by sdickhoven** [terraform-providers/terraform-provider-cloudflare#487]
### Terraform Version
terraform 0.11.14

### Affected Resource(s)
- cloudflare_load_balancer

### Terraform Configuration Files
```hcl
resource "cloudflare_load_balancer" "myzone_com__my_app" {
  zone_id = "${module.myzone_com.zone["id"]}"
  zone    = "${module.myzone_com.zone["domain"]}"
  name    = "my-app.${module.myzone_com.zone["domain"]}"

  default_pool_ids = [
    "${cloudflare_load_balancer_pool.my_app.id}",
  ]

  fallback_pool_id = "${cloudflare_load_balancer_pool.my_app.id}"
  steering_policy  = "geo"

  region_pools {
    region = "EEU"

    pool_ids = [
      "${cloudflare_load_balancer_pool.gdpr_my_app.id}",
    ]
  }

  region_pools {
    region = "WEU"

    pool_ids = [
      "${cloudflare_load_balancer_pool.gdpr_my_app.id}",
    ]
  }

  proxied = false
}
```

### Debug Output
```
Warning: cloudflare_load_balancer.myzone_com__my_app: "zone": [DEPRECATED] `zone` is deprecated in favour of explicit `zone_id` and will be removed in the next major release
```

### Panic Output
n/a

### Expected Behavior
If I remove the `zone` param I will stop getting the above deprecation warning.

### Actual Behavior
When removing the `zone` param, the provider complains that the required `zone` parameter is missing. So I can choose between an error and a deprecation warning. The provider should be satisfied with _just_ the `zone_id` parameter but it is not.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Nothing out of the ordinary. I'm using a module to create the zone but that has no bearing on this situation. The `cloudflare_load_balancer` resource seems to require the `zone` param and treat `zone_id` as optional. It _should_ require _either_ `zone` (which is deprecated) _or_ `zone_id`.

### References
n/a

**Comment by jacobbednarz** [comment]
What provider version are you using?

**Comment by sdickhoven** [comment]
my bad...
```
$ terraform version
Terraform v0.11.14
+ provider.cloudflare v1.18.1
+ provider.external v1.2.0
+ provider.null v1.0.0
```

**Comment by jacobbednarz** [comment]
Can you please try upgrading to 2.0.0 for the Cloudflare provider?

**Comment by sdickhoven** [comment]
hi @jacobbednarz. i can try that in our staging environment in the coming days. given the error message, i assume it will work in `2.0.0`. :)
