### ISSUE TITLE
provider ignores pending zone config

### ISSUE THREAD

**Issue by sdickhoven** [terraform-providers/terraform-provider-cloudflare#488]
### Terraform Version
```
Terraform v0.11.14
+ provider.cloudflare v1.18.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- cloudflare_zone

### Terraform Configuration Files
```hcl
resource "cloudflare_zone" "myzone_com" {
  zone   = "myzone.com"
  plan   = "enterprise"
}
```

### Debug Output
```
  ~ cloudflare_zone.myzone_com
      plan:       "free" => "enterprise"
```

### Panic Output
n/a

### Expected Behavior
When a zone has been set to `plan = "enterprise"` (or, presumably, anything other than "free"), the provider should recognize that (based on "pending changes" returned by the API) even **when the zone has not been activated yet**.

### Actual Behavior
When configuring a zone via Terraform, the provider doesn't return the correct state (based on pending zone changes) to Terraform **when the zone has not been activated yet**. As a result, Terraform will want to make the above change (see debug output) over and over... until the zone is activated.

When a zone has not been activated yet, changing the plan will be reflected under "pending changes" (rather than "plan") in the API. However, the provider does not seem to look at pending changes when computing the state of the zone resource and will keep returning `plan = "free"` to Terraform. Terraform then correctly concludes that a change has to be made (even though that change has already been made and is in the "pending" state on the Cloudflare side).

### Steps to Reproduce
1. Create Cloudflare zone (via terraform or by hand and then import into terraform)
2. Do **not** update the registrar with Cloudflare's auth NS servers for the newly created zone
3. Set `plan = "enterprise"` (or, most likely, anything other than "free")
4. Run `terraform apply` multiple times (and actually _apply_ changes)

Terraform will want to make the same change over and over.

### Important Factoids
You obviously need an Enterprise account (or Pro or some other pay-for account) in order to replicate this.

### References
n/a

**Comment by jacobbednarz** [comment]
This looks like an interesting one! Here is the payload for a new domain that is going to be an Enterprise domain but is stuck in that Free section you mention.

```json
{
  "id":"a5c8dbde66a2a37730a59b9c2231c3a4",
  "name":"example.com",
  "status":"initializing",
  "paused":false,
  "type":"full",
  "development_mode":0,
  "name_servers":[
    "abby.ns.cloudflare.com",
    "noel.ns.cloudflare.com"
  ],
  "original_name_servers":[
    "amy.ns.cloudflare.com",
    "mark.ns.cloudflare.com"
  ],
  "original_registrar":"cloudflare, inc. (id: 1910)",
  "original_dnshost":null,
  "modified_on":"2019-10-08T00:34:59.445216Z",
  "created_on":"2019-10-08T00:34:51.299296Z",
  "activated_on":null,
  "meta":{
    "step":2,
    "wildcard_proxiable":false,
    "custom_certificate_quota":0,
    "page_rule_quota":3,
    "phishing_detected":false,
    "multiple_railguns_allowed":false
  },
  "owner":{
    "id":"d6676f3c1fb69caffc045d9cfb671de7",
    "type":"organization",
    "name":"Example Org"
  },
  "account":{
    "id":"d6676f3c1fb69caffc045d9cfb671de7",
    "name":"Example Org"
  },
  "permissions":[
    "#access:edit",
    "#access:read",
    "#analytics:read",
    "#app:edit",
    "#auditlogs:read",
    "#billing:edit",
    "#billing:read",
    "#cache_purge:edit",
    "#dns_records:edit",
    "#dns_records:read",
    "#lb:edit",
    "#lb:read",
    "#legal:edit",
    "#legal:read",
    "#logs:edit",
    "#logs:read",
    "#member:edit",
    "#member:read",
    "#organization:edit",
    "#organization:read",
    "#ssl:edit",
    "#ssl:read",
    "#stream:edit",
    "#stream:read",
    "#subscription:edit",
    "#subscription:read",
    "#waf:edit",
    "#waf:read",
    "#webhooks:edit",
    "#webhooks:read",
    "#worker:edit",
    "#worker:read",
    "#zone:edit",
    "#zone:read",
    "#zone_settings:edit",
    "#zone_settings:read"
  ],
  "plan":{
    "id":"0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
    "name":"Free Website",
    "price":0,
    "currency":"USD",
    "frequency":"",
    "is_subscribed":true,
    "can_subscribe":false,
    "legacy_id":"free",
    "legacy_discount":false,
    "externally_managed":false
  }
}
```

Do you mean the `plan_pending` section? I don't see it in my response but it is in the [docs](https://api.cloudflare.com/#zone-create-zone). Would you be able to provide that for me?

In terms of the logic, in the `Read` method, we can check if the `plan_pending` is set and if it is, use those values instead of the current `plan` values. How does that sound?

**Comment by garrettgalow** [comment]
If the zone is in pending (or initializing) then yes unfortunately for now checking plan_pending is the best course of action. We are working on getting rid of that behavior but is not a quick fix.

Just a note: the initializing state only occurs if a zone is signed up via the dashboard. Any zone created via the API (or terraform) will start in pending state.

**Comment by jacobbednarz** [comment]
@sdickhoven do you want to take a pass at this? If not, I can take a look later this week.

**Comment by inge4pres** [comment]
@jacobbednarz here's another test payload from API of an Enterprise zone that is pending activation

```
{
  "id": "65a1988a4385a0c864edac52591d4ebc",
  "name": "foo.xyz",
  "status": "pending",
  "paused": false,
  "type": "partial",
  "development_mode": 0,
  "verification_key": "418731636-185913529",
  "original_name_servers": [
    "todd.ns.cloudflare.com",
    "leah.ns.cloudflare.com"
  ],
  "original_registrar": null,
  "original_dnshost": null,
  "modified_on": "2019-10-11T07:37:52.648019Z",
  "created_on": "2019-10-11T07:37:52.648019Z",
  "activated_on": null,
  "meta": {
    "step": 4,
    "wildcard_proxiable": false,
    "custom_certificate_quota": 0,
    "page_rule_quota": 3,
    "phishing_detected": false,
    "multiple_railguns_allowed": false
  },
  "owner": {
    "id": "3eeaf6cb282856ffec14088da033827f",
    "type": "organization",
    "name": "Lastminute Test"
  },
  "account": {
    "id": "3eeaf6cb282856ffec14088da033827f",
    "name": "Lastminute Test"
  },
  "permissions": [
    "#access:edit",
    "#access:read",
    "#analytics:read",
    "#app:edit",
    "#auditlogs:read",
    "#billing:edit",
    "#billing:read",
    "#cache_purge:edit",
    "#dns_records:edit",
    "#dns_records:read",
    "#lb:edit",
    "#lb:read",
    "#legal:edit",
    "#legal:read",
    "#logs:edit",
    "#logs:read",
    "#member:edit",
    "#member:read",
    "#organization:edit",
    "#organization:read",
    "#ssl:edit",
    "#ssl:read",
    "#stream:edit",
    "#stream:read",
    "#subscription:edit",
    "#subscription:read",
    "#waf:edit",
    "#waf:read",
    "#webhooks:edit",
    "#webhooks:read",
    "#worker:edit",
    "#worker:read",
    "#zone:edit",
    "#zone:read",
    "#zone_settings:edit",
    "#zone_settings:read"
  ],
  "plan": {
    "id": "0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
    "name": "Free Website",
    "price": 0,
    "currency": "USD",
    "frequency": "",
    "is_subscribed": true,
    "can_subscribe": false,
    "legacy_id": "free",
    "legacy_discount": false,
    "externally_managed": false
  }
}
```

**Comment by jacobbednarz** [comment]
Thanks! I’m hoping to tackle this next week (if someone doesn’t beat me to
it).

**Comment by jacobbednarz** [comment]
@sdickhoven can you please build and try this out on master? the support for pending zones should be working now.
