### ISSUE TITLE
Origins missing weight property in cloudflare_load_balancer_pool and LBs missing session_affinity in cloudflare_load_balancer

### ISSUE THREAD

**Issue by prdonahue** [terraform-providers/terraform-provider-cloudflare#49]
Origin weights and session affinity were added to cloudflare-go here: https://github.com/cloudflare/cloudflare-go/commit/667a72333f4e362f45844ea90caef0e49ff8f97c.

Should be able to do something like this for weights:
```
resource "cloudflare_load_balancer_pool" "example-servers" {
  ...
  origins {
    name = "www-us"
    address = "203.0.113.10"
    weight = 0.5
  }
  origins {
    name = "www-asia"
    address = "198.51.100.15"
    weight = 0.5
  }
```

And session persistence:
```
resource "cloudflare_load_balancer" "example-lb" {
  ...
  session_affinity = "cookie"
}
```

**Comment by lawrencejones** [comment]
Hey @prdonahue, origin weights should be implemented in https://github.com/terraform-providers/terraform-provider-cloudflare/pull/57

**Comment by lawrencejones** [comment]
In fact, while I'm at it I'll add the session affinity.

**Comment by lawrencejones** [comment]
That's now done. #57 should add both session affinity and origin weights.

**Comment by l13t** [comment]
To not open new ticket - it's also not possible to force CF disable certificate check in LB monitor if https is enabled.

**Comment by jacobbednarz** [comment]
@patryk I think this one is good to close now and both of these have landed.

**Comment by l13t** [comment]
@jacobbednarz do i need to open another issue to add option `ignore certificate`?

**Comment by jacobbednarz** [comment]
Yep, it's not related to this change and it would be great for you to submit it using the issue template provided so we can take a look.
