### ISSUE TITLE
Getting: Unrecognized zone setting name when try to use h2_prioritization setting

### ISSUE THREAD

**Issue by jakshi** [terraform-providers/terraform-provider-cloudflare#496]
when I use h2_prioritization setting in cloudflare_zone_settings_override resource I'm getting:

Error: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1006,\"message\":\"Unrecognized zone setting name\"}],\"messages\":[],\"result\":null}"

According to https://www.terraform.io/docs/providers/cloudflare/r/zone_settings_override.html#h2_prioritization

it's a valid setting.

kostiantyn@zugluft:1:~/ddproperty/git-repos/terraform/cloudflare/environments/staging/staging.commercialguru.com.sg:kostiantyn/enable_safe_cloudflare_optimizations$ terraform --version
Terraform v0.12.9
+ provider.aws v2.30.0
+ provider.cloudflare v2.0.0
+ provider.template v2.1.2

**Comment by jacobbednarz** [comment]
Some work has been done specifically with this endpoint via #493. Can you please build against master and let me know if you're still experiencing the issue?

**Comment by jakshi** [comment]
After upgrading cloudflare terraform provider to 2.0.1 the issue disappeared.
So I'm closing the issue.
