### ISSUE TITLE
When creating new repo, adding a zone settings override configuraion gives: "An unknown error has occurred"

### ISSUE THREAD

**Issue by eliasdorneles** [terraform-providers/terraform-provider-cloudflare#497]
I'm refactoring our TF Cloudflare configuration, moving it into a dedicated repo and upgrading to the recent version of the CF provider (2.0).

I've successfully imported all resources, except the zone settings override -- which are not importable and are being marked to be updated (even though I haven't changed any setting, the original code was output of the `cf-terraforming` script).

The problem is that this update is failing with the following error:

```
Error: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1016,\"message\":\"An unknown error has occurred\"}],\"messages\":[],\"result\":null}"
```

### Terraform Version

v0.12.9

### Affected Resource(s)

Please list the resources as a list, for example:

- cloudflare_zone_settings_override

### Terraform Configuration Files
```hcl
resource "cloudflare_zone" "ourdomain" {
  zone = "ourdomain.com"

  plan = "business"
}

resource "cloudflare_zone_settings_override" "ourdomain_zone_setting" {
  zone_id = cloudflare_zone.ourdomain.id

  settings {
    always_online            = "on"
    always_use_https         = "off"
    automatic_https_rewrites = "off"
    brotli                   = "off"
    browser_cache_ttl        = 14400
    browser_check            = "on"
    cache_level              = "aggressive"
    challenge_ttl            = 1800
    cname_flattening         = "flatten_at_root"
    development_mode         = "off"
    edge_cache_ttl           = 7200
    email_obfuscation        = "on"
    hotlink_protection       = "off"
    http2                    = "on"
    ip_geolocation           = "on"
    ipv6                     = "on"
    max_upload               = 100
    min_tls_version          = "1.0"

    minify {
      css  = "on"
      html = "on"
      js   = "on"
    }

    mirage = "off"

    mobile_redirect {
      mobile_subdomain = ""
      status           = "off"
      strip_uri        = false
    }

    opportunistic_encryption = "off"
    opportunistic_onion      = "on"
    polish                   = "lossless"
    privacy_pass             = "on"
    pseudo_ipv4              = "off"
    rocket_loader            = "off"

    security_header {
      enabled            = false
      include_subdomains = false
      max_age            = 0
      nosniff            = false
      preload            = false
    }

    security_level      = "medium"
    server_side_exclude = "on"
    ssl                 = "full"
    tls_1_3             = "on"
    tls_client_auth     = "off"
    waf                 = "on"
    webp                = "off"
    websockets          = "on"
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior

The zone settings override to be updated/overwritten and `terraform apply` finishes successfully.

### Actual Behavior

The `terraform apply` command fail with an error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids

We started having these problems after upgrading to the recent version of the provider (2.0).

The first problems we got, it was because we had `response_buffering = "off"` in the settings, which is a read-only thing for us (it's writable only on Enterprise plan, we're on Cloudflare's plan Business). Once we removed that from the settings, we got this new error "unknown error".

**Comment by jacobbednarz** [comment]
We also hit this however it wasn’t specific to 2.0. The trigger was actually attempting to set the value of a directive to it’s default value via an update. 

We have a ticket open with Cloudflare Support to investigate it however this isn’t something we need to address in the provider based on what we’ve found. 

The zone override resource should only be used when you’re overriding the default value, not all of them. I’d recommend only setting those which you alter from the defaults to avoid the issue with non-accessible features based on your plan _and_ the issue I outlined above. 

Going to close this off for now and will reopen if Cloudflare need us to change anything.

**Comment by eliasdorneles** [comment]
Thanks for the prompt answer, I'm going to review our config and remove the directives setting the default value.

Is there a place where the default values are documented?
I was looking here: https://www.terraform.io/docs/providers/cloudflare/r/zone_settings_override.html

**Comment by eliasdorneles** [comment]
Nvm, I found the [CF docs for those](https://api.cloudflare.com/#zone-settings-properties), here is a PR to update the documentation on this side: https://github.com/terraform-providers/terraform-provider-cloudflare/pull/498
