### ISSUE TITLE
MX records always show changes due to capitalization

### ISSUE THREAD

**Issue by heydonovan** [terraform-providers/terraform-provider-cloudflare#529]
```
$ terraform version
Terraform v0.12.12
+ provider.aws v2.33.0
+ provider.cloudflare v2.0.1
```

```
resource "cloudflare_record" "mx-email-company-com-alt1" {
  zone_id  = cloudflare_zone.main.id
  name     = "email.company.com"
  value    = "ASPMX.L.GOOGLE.COM"
  priority = 1
  type     = "MX"
  ttl      = 300
}
```

```
  # cloudflare_record.mx-email-company-com-alt1 will be updated in-place
  ~ resource "cloudflare_record" "mx-email-company-com-alt1" {
        created_on  = "2019-10-30T21:48:38.509878Z"
        data        = {}
        hostname    = "email.company.com"
        id          = "a74dafb2dcb80b0971913b62f590a54d"
        metadata    = {
            "auto_added"             = "false"
            "managed_by_apps"        = "false"
            "managed_by_argo_tunnel" = "false"
        }
        modified_on = "2019-10-30T21:48:38.509878Z"
        name        = "email.company.com"
        priority    = 1
        proxiable   = false
        proxied     = false
        ttl         = 300
        type        = "MX"
      ~ value       = "aspmx.l.google.com" -> "ASPMX.L.GOOGLE.COM"
        zone_id     = "bd14181cf363074370344d0aa784ce70"
    }
```

I'm seeing that once it propagates to Cloudflare's side, it is lowercase. So is the solution here to just change my code to be lowercase? Or should Terraform support both? :)

We are seeing similar when we create a simple CNAME record with a trailing period, since the period never shows up in the Cloudflare UI. Terraform wants to update it each time, even though it's technically a FQDN. Not sure how to handle that either, I've just removed them for now.

**Comment by jacobbednarz** [comment]
> We are seeing similar when we create a simple CNAME record with a trailing period

There was a discussion in #154 about this and my view hasn't changed on our approach. Happy to reconsider it if you have new ideas/thoughts on it.

> So is the solution here to just change my code to be lowercase? Or should Terraform support both? :)

Option C, both 😄 I would update your code to use the correct case now to prevent the flapping but we can definitely consider support for both. For majority of DNS records, the value is case insensitive. However, SPF and TXT are case sensitive. I'm happy to see a PR that would perform a custom `DiffSuppressFunc` but it would need to take into account the DNS record type. If it was TXT or SPF, include case sensitive changes, otherwise it's fine to lowercase it all.

**Comment by heydonovan** [comment]
Thanks for the quick response! :) - I'll just lowercase it for now, the simplest solution is often best.

**Comment by bechampion** [comment]
Hi guys . I'm having a similar issue ,  but for me we have base64 encoded stuff in TXT records , which i can't really tolower() as it wouldn't validate with providers etc.
Is there a workaround?

**Comment by jacobbednarz** [comment]
@bechampion use the correct case to prevent it flapping.

**Comment by bechampion** [comment]
@jacobbednarz thanks for gettiing back to me ,  I am using the correct casing (which is a combination of upper/lower case strings ) , but at the moment of "planning" it transforms whatever is in the `value` of the TXT record to lowercase

**Comment by jacobbednarz** [comment]
> @jacobbednarz <https://github.com/jacobbednarz> thanks for gettiing back 
> to me , I am using the correct casing (which is a combination of 
> upper/lower case strings ) , but at the moment of "planning" it 
> transforms whatever is in the |value| of the TXT record to lowercase
Using the following configuration, I am unable to reproduce.

     provider "cloudflare" {
       version = "~> 2.0"
     }

     resource "cloudflare_record" "example" {
       zone_id = "redacted"
       name    = "example"
       value   = "dGVzdA=="
       type    = "TXT"
       ttl     = 1
     }

Here is the apply output and state following the apply.

     $ CLOUDFLARE_EMAIL="$CF_EMAIL" CLOUDFLARE_API_KEY="$CF_API_KEY" 
terraform apply

     An execution plan has been generated and is shown below.
     Resource actions are indicated with the following symbols:
       + create

     Terraform will perform the following actions:

       + cloudflare_record.example
           id:          <computed>
           created_on:  <computed>
           hostname:    <computed>
           metadata.%:  <computed>
           modified_on: <computed>
           name:        "example"
           proxiable:   <computed>
           proxied:     "false"
           ttl:         "1"
           type:        "TXT"
           value:       "dGVzdA=="
           zone_id:     "redacted"


     Plan: 1 to add, 0 to change, 0 to destroy.

     Do you want to perform these actions?
       Terraform will perform the actions described above.
       Only 'yes' will be accepted to approve.

       Enter a value: yes

     cloudflare_record.example: Creating...
       created_on:  "" => "<computed>"
       hostname:    "" => "<computed>"
       metadata.%:  "" => "<computed>"
       modified_on: "" => "<computed>"
       name:        "" => "example"
       proxiable:   "" => "<computed>"
       proxied:     "" => "false"
       ttl:         "" => "1"
       type:        "" => "TXT"
       value:       "" => "dGVzdA=="
       zone_id:     "" => "redacted"
     cloudflare_record.example: Creation complete after 1s (ID: 
581fdecd71cf25f4bf5ed44177e35062)

     Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

     $ CLOUDFLARE_EMAIL="$CF_EMAIL" CLOUDFLARE_API_KEY="$CF_API_KEY" 
terraform apply
     cloudflare_record.example: Refreshing state... (ID: 
581fdecd71cf25f4bf5ed44177e35062)

     $ terraform state show cloudflare_record.example
     id                              = 581fdecd71cf25f4bf5ed44177e35062
     created_on                      = 2019-12-08T19:57:23.275862Z
     data.%                          = 0
     hostname                        = example.domain.net
     metadata.%                      = 3
     metadata.auto_added             = false
     metadata.managed_by_apps        = false
     metadata.managed_by_argo_tunnel = false
     modified_on                     = 2019-12-08T19:57:23.275862Z
     name                            = example
     priority                        = 0
     proxiable                       = false
     proxied                         = false
     ttl                             = 1
     type                            = TXT
     value                           = dGVzdA==
     zone_id                         = redacted

If you are still having issues, I'd recommend debugging your 
installation as the provider and API seem to be working as expected.
