### ISSUE TITLE
Support for Zone Lockdowns

### ISSUE THREAD

**Issue by SteveGoldthorpe-Work** [terraform-providers/terraform-provider-cloudflare#53]
Support Cloudflare Zone lockdowns:
https://api.cloudflare.com/#zone-lockdown-properties

Potential resource could be of form:
```
resource "cloudflare_zone_lockdown" "foobar" {
  zone        = "${var.cloudflare_domain}"
  paused      = "false"
  description = "lockdown rule for api.mysite.com"

  urls = [
    "api.mysite.com/some/endpoint*",
  ]

  configurations = [
    {
      target = "ip"
      value  = "1.2.3.4"
    },
    {
      target = "ip_range"
      value  = "5.6.7.8/24"
    },
  ]
}
```
Where paused is optional (defaults to false) and description is optional.

**Comment by mwarkentin** [comment]
We would love this!

**Comment by DH-Mike** [comment]
Subscribing to this,
This would be incredibly useful for us!

**Comment by prdonahue** [comment]
Thanks for the feedback. We've added this to the list of features to be added in our next iteration.

**Comment by AshleyPoole** [comment]
+1 As well as using Cloudflare Access too!

**Comment by SteveGoldthorpe-Work** [comment]
I'm preparing a PR, but it will require a bug fix in the cloudflare-go library I've submitted.
https://github.com/cloudflare/cloudflare-go/issues/227

**Comment by SteveGoldthorpe-Work** [comment]
PR created:
https://github.com/terraform-providers/terraform-provider-cloudflare/pull/115
