### ISSUE TITLE
Adding double-quotes to TXT records

### ISSUE THREAD

**Issue by heydonovan** [terraform-providers/terraform-provider-cloudflare#530]
This is less of a bug report, and more of a general question (let me know if there is a better spot to ask these specific questions). So the RFC states that a TXT record must be surrounded in double-quotes if there are spaces in it. How are folks doing this? Escaping quotes? I didn't see any examples anywhere, so just want to make sure I've got this down.

```
resource "cloudflare_record" "txt-company-com-alt1" {
  zone_id = cloudflare_zone.main.id
  name    = "company.com"
  value   = "\"google-site-verification=Aa4kOdcBuOpShjcQSddCu7n4j2uLfoduTLX0a0gao7E\""
  type    = "TXT"
  ttl     = 300
}
```

With `aws_route53_record`, the value would accept an array of strings, which means quotes can be used, and one doesn't need to mess around with escaping or formatting:

```
resource "aws_route53_record" "txt-v-include-geteventstore-com" {
    zone_id = "${aws_route53_zone.foo.id}"
    name    = "geteventstore.com"
    type    = "TXT"
    records = ["v=spf1", "include:spf.protection.outlook.com -all", "MS=ms18260796"]
    ttl     = "900"
}
```

**Comment by jacobbednarz** [comment]
Cloudflare seem to handle this without the need for explicit quotes in the data you send it. Sending `google-site-verification=Aa4kOdcBuOpShjcQSddCu7n4j2uLfoduTLX0a0gao7E\` as the payload results in `"google-site-verification=Aa4kOdcBuOpShjcQSddCu7n4j2uLfoduTLX0a0gao7E\"` when you query it via `dig`.
