### ISSUE TITLE
Destroy errors out on read-only resources

### ISSUE THREAD

**Issue by inge4pres** [terraform-providers/terraform-provider-cloudflare#531]
Hello,

this is a report of an error occurred during the destroy phase for a zone.
We're testing migration to v2 provider by creating/destroying a test zone.

### Terraform Version
terraform 0.11.14
terraform-provider-cloudflare 2.0.1

### Affected Resource(s)
Please list the resources as a list, for example:
- cloudflare_zone
- cloudflare_zone_settings_override

### Terraform Configuration Files
```hcl
## previously managed by mjolnir
resource "cloudflare_zone" "zone" {
  type = "partial"
  plan = "enterprise"
  zone = "${var.zone}"
}

resource "cloudflare_zone_settings_override" "zone-setting" {
  zone_id = "${cloudflare_zone.zone.id}"

  settings {
    tls_1_3 = "on"
    min_tls_version = "1.1"
    ssl = "${var.ssl_mode}"
    // => readonly in Free, have it Enterprise
    http2 = "${var.enable_http2}"
    opportunistic_encryption = "off"
    brotli = "on"
    automatic_https_rewrites = "${var.automatic_https_rewrites}"
    security_level = "medium"
    waf = "on"
    polish = "lossless"
    mirage = "off"
    rocket_loader = "off"
    minify {
      css = "on"
      js = "on"
      html = "on"
    }
  }
}
```

### Expected Behavior
No error in destroying the resources

### Actual Behavior
This error shows up:
```
Error: Error applying plan:

1 error occurred:
        * module.zone-name.cloudflare_zone_settings_override.zone-setting (destroy): 1 error occurred:
        * cloudflare_zone_settings_override.zone-setting: invalid zone setting "image_resizing" (value: ) found - cannot be set as it is read only
```
Looks like the destroy cycle tries to set an attribute to the zone before destroying...

### Steps to Reproduce
1. Create a zone and its custom configs, running `terraform apply`
2. Destroy the zone `terraform destroy`

**Comment by jacobbednarz** [comment]
What I suspect is happening here is that the zone is created but it hasn't been converted to an Enterprise zone when the resource is destroyed, it still doesn't have access to it. I don't think we can do anything in the provider at this stage to cleanly account for this.

If the above is indeed what is happening, the advice I have been giving to people is to do it in two steps. Create the zone and get it setup as an Enterprise zone in your account and then try to applying changes to it. Also, if you're not using those settings, just omit them to leave them as the defaults.

**Comment by jacobbednarz** [comment]
#599 is mentioned to have addressed this. @inge4pres would you mind checking out master and confirming this is the case for you?

**Comment by jacobbednarz** [comment]
Closing this off as #599 mentions a potential fix. Can reopen if we needed to explore further.

**Comment by simonpainter** [comment]
Not convinced this has been fixed.

Following error when trying to destroy  customer settings.
"Error: invalid zone setting "image_resizing" (value: ) found - cannot be set as it is read only"

terraform-provider-cloudflare_v2.7.0_x4
Terraform v0.12.26
