### ISSUE TITLE
Priority >1 for single page rule causes changing

### ISSUE THREAD

**Issue by okgolove** [terraform-providers/terraform-provider-cloudflare#537]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
Terraform v0.12.13

### Affected Resource(s)
Please list the resources as a list, for example:
- cloudflare_page_rule

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "cloudflare_page_rule" "cache_bypass" {
  for_each = toset([for k,v in var.domains : k if v["bypass_cache"]])

  zone_id  = cloudflare_zone.domain[each.key].id
  target   = format("*%s/*", each.key)
  priority = 1
  status   = "active"

  actions {
    cache_level = "bypass"
  }
}

resource "cloudflare_page_rule" "www_redirect" {
  for_each = toset([for k,v in var.domains : k if v["www_redirect"]])

  zone_id  = cloudflare_zone.domain[each.key].id
  target   = format("*www.%s/", each.key)
  priority = 2
  status   = "active"

  actions {
    forwarding_url {
      url         = "https://${each.key}"
      status_code = 301
    }
  }
}
```

### Expected Behavior
What should have happened?
No changes were caused by apply.

### Actual Behavior
What actually happened?
In case of bypass_cache for a domain is set `false` terraform changes rule's priority every run:
```
  ~ resource "cloudflare_page_rule" "www_redirect" {
        id       = "123012391283"
      ~ priority = 1 -> 2
        status   = "active"
        target   = "*www.test.eu/"
        zone_id  = "12312312312"

        actions {
            always_use_https    = false
            disable_apps        = false
            disable_performance = false
            disable_railgun     = false
            disable_security    = false
            edge_cache_ttl      = 0

            forwarding_url {
                status_code = 301
                url         = "https://test.eu"
            }
        }
    }
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by jacobbednarz** [comment]
Have you seen #187? If there is flapping priority it could be the same root cause (there is a workaround listed in the issue). If it's not, can you please provide a reproduction case without the looping functionality? As it's a 0.12 feature, I haven't delved into it much and unsure if it's a factor here.

**Comment by okgolove** [comment]
It seems I missed that issue.
I guess this is the same problem.
This workaround works but looks complicated.

**Comment by jacobbednarz** [comment]
It's not pretty but it has enabled us (and others) to prevent the flapping priorities. Open to hearing other workarounds if you have other approaches.

**Comment by bechampion** [comment]
its been a long time and this still an issue ... @cloudflare are you gonna fix?
