### ISSUE TITLE
Cloudflare zone lockdown configurations, multiple IP(ranges) per configuration.

### ISSUE THREAD

**Issue by Henk-JanVanHasselaar** [terraform-providers/terraform-provider-cloudflare#540]
This is kind of a feature request but could also be considered a bug?
In issue #406 the documentation was changed to allow only one entry in the `configurations` property of a cloudflare zone lockdown resource.

_disclaimer: I've just started with terraform so if I miss anything please let me know!_ 

### Affected Resource
- resource_cloudflare_zone_lockdown

### Expected behaviour
According to the cloudflare api [documentation](https://support.cloudflare.com/hc/en-us/articles/115001595131-Locking-down-URLs-in-Cloudflare) one is allows to send an array of configurations. e.g:

```
$ curl -X POST -H "X-Auth-Email: $MYEMAIL" -H "X-Auth-Key: $MYAPIKEY" -H "Content-Type: application/json" https://api.cloudflare.com/client/v4/zones/$MYZONETAG/firewall/lockdowns --data \
‘{
  "description": "Block all traffic to the staging and wiki unless coming from corporate headquarters or a branch office",
  "urls": [
    "staging.example.com/*",
    "example.com/wiki/*"
  ],
  "configurations": [
    {
      "target": "ip_range",
      "value": "192.0.2.0/24"
    },
    {
      "target": "ip_range",
      "value": "2001:DB8::/64"
    },
    {
      "target": "ip",
      "value": "203.0.133.1"
    }
  ]
}’
```
Reading the docs the following terraform configuration would make sense to me. 
```
resource "cloudflare_zone_lockdown" "endpoint_lockdown" {
  zone        = "api.mysite.com"
  paused      = "false"
  description = "Block all traffic to the staging and wiki unless coming from corporate headquarters or a branch office"
  urls = [
      "staging.example.com/*",
      "example.com/wiki/*"
  ]
  configurations = [
    {
      target = "ip_range"
      value = "192.0.2.0/24"
    },{
      target = "ip_range"
      value = "2001:DB8::/64"
    },{
      target = "ip"
      value = "203.0.133.1"
    }
  ]
}
```
This was also the way it was stated in the documentation before issue #406 was resolved. 

### Actual behaviour
in the current version of the terraform `cloudflare_zone_lockdown`  an array of configurations is not supported. so implementing the above example would look like this: 
```
resource "cloudflare_zone_lockdown" "endpoint_lockdown1" {
  zone        = "api.mysite.com"
  paused      = "false"
  description = "Block all traffic to the staging and wiki unless coming from corporate headquarters or a branch office"
  urls = [
      "staging.example.com/*",
      "example.com/wiki/*"
  ]
  configurations {
      target = "ip_range"
      value = "192.0.2.0/24"
    }
}

resource "cloudflare_zone_lockdown" "endpoint_lockdown2" {
  zone        = "api.mysite.com"
  paused      = "false"
  description = "Block all traffic to the staging and wiki unless coming from corporate headquarters or a branch office"
  urls = [
      "staging.example.com/*",
      "example.com/wiki/*"
  ]
  configurations {
      target = "ip_range"
      value = "2001:DB8::/64"
    }
}

resource "cloudflare_zone_lockdown" "endpoint_lockdown3" {
  zone        = "api.mysite.com"
  paused      = "false"
  description = "Block all traffic to the staging and wiki unless coming from corporate headquarters or a branch office"
  urls = [
      "staging.example.com/*",
      "example.com/wiki/*"
  ]
  configurations {
      target = "ip"
      value = "203.0.133.1"
    }
}
```
This results in quite a lot of duplication. 

### Additional info
While searching through the source I see the [resource](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/cloudflare/resource_cloudflare_zone_lockdown.go#L225) actually converts the configurations to an array. Which makes sense because that matches the api documentation. 

#### References
issue: #406
cloudflare api reference: https://support.cloudflare.com/hc/en-us/articles/115001595131-Locking-down-URLs-in-Cloudflare

**Comment by jacobbednarz** [comment]
I'm happy to review a PR for this however I would personally be pushing to use the [Filter based Firewall instead](https://developers.cloudflare.com/firewall/cf-firewall-rules/) due to the ease of management and rule creation. Most of the firewall functionality (use agent blocks, zone lockdown, custom rules, etc) can all be replaced with the filter based firewall in a more efficient manner with the exception of rate limiting.

Here is the Terraform code for the example above. 

```hcl
resource "cloudflare_filter" "internal_access" {
  zone_id = "abc123"
  description = "Internal access only"
  expression = "(http.host eq \"staging.example.com\") or (http.request.full_uri matches \"example\\.com/wiki/.+\" and not ip.src in {2001:DB8::/64 192.0.2.0/24 203.0.133.1/32})"
}

resource "cloudflare_firewall_rule" "wordpress" {
  zone_id = "abc123"
  description = "Restrict access to internal staff only"
  filter_id = cloudflare_filter.internal_access.id
  action = "block"
}
```

Aside to this, I'd also make two recommendations:

- Look into [Cloudflare Access](https://www.cloudflare.com/products/cloudflare-access/) for internal applications if you want to do away with IP restrictions and instead gate your apps with easy authentication from a number of providers. 
- Related to the first point, I'd remove "special IPs" where possible. It isn't a great approach to securing systems as if you update these IPs and they end up recycled without you also updating the firewall rules, you're potentially allowing non-authorised traffic to your system.

**Comment by Henk-JanVanHasselaar** [comment]
Thanks for taking the time to make some recommendations! The cloudflare Access is a goal to work towards for us. I'll take a look at the Filter based firewall for our initial migration to cloudflare. 
Feel free to close this issue if it's not something worth implementing. 

Thanks again!

**Comment by jacobbednarz** [comment]
Does the following work by any chance?

```
resource "cloudflare_zone_lockdown" "endpoint_lockdown2" {
  zone        = "api.mysite.com"
  paused      = "false"
  description = "Block all traffic to the staging and wiki unless coming from corporate headquarters or a branch office"
  urls = [
      "staging.example.com/*",
      "example.com/wiki/*"
  ]
  configurations {
      target = "ip_range"
      value = "2001:DB8::/64"
    }

  configurations {
      target = "ip"
      value = "127.0.0.1"
    }
}
```

**Comment by pc-mreeves** [comment]
@jacobbednarz I verified this does in fact work! Thanks for the suggestion!

**Comment by jacobbednarz** [comment]
Closing as this already possible.
