### ISSUE TITLE
Error: error listing Zone: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":6003,\"message\":\"Invalid request headers\",\"error_chain\":[{\"code\":6103,\"message\":\"Invalid format for X-Auth-Key header\"}]}],\"messages\":[],\"result\":null}"

### ISSUE THREAD

**Issue by jbunce** [terraform-providers/terraform-provider-cloudflare#546]
### Terraform Version
Terraform v0.12.16
+ provider.cloudflare v2.1.0

### Affected Resource(s)
Please list the resources as a list, for example:
- cloudflare_record

### Terraform Configuration Files
```hcl
provider "cloudflare" {
  version = "~> 2.0"
  email   = "${var.email}"
  api_key = "${var.api_key}"
}

variable "domain" {
  default = "foo.bar"
}

locals {
  recordsets = { for rs in var.recordsets : rs.type => rs... }

  a_recordsets = lookup(local.recordsets, "A", [])

  a_records = flatten([
    for rs in local.a_recordsets : [
      for r in rs.records : {
        name = rs.name
        type = rs.type
        ttl  = rs.ttl
        data = r
      }
    ]
  ])

  supported_record_types = {
    A = true
  }

  check_supported_types = [
    for rs in var.recordsets : local.supported_record_types[rs.type]
  ]
}

data "cloudflare_zones" "main" {
  filter {
    name = "${var.zone_id}"
  }
}

resource "cloudflare_record" "a" {
  for_each = {
    for r in local.a_records : "${r.name} ${r.type} ${r.data}" => r
  }
  name    = coalesce(each.value.name, "@")
  type    = "A"
  proxied = true
  zone_id = "${var.zone_id}"
}
```

### Panic Output
```
Error: error listing Zone: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":6003,\"message\":\"Invalid request headers\",\"error_chain\":[{\"code\":6103,\"message\":\"Invalid format for X-Auth-Key header\"}]}],\"messages\":[],\"result\":null}"

  on ../../modules/cloudflare/0.0.1/main.tf line 36, in data "cloudflare_zones" "main":
  36: data "cloudflare_zones" "main" {
```

### Steps to Reproduce
`terraform plan`

**Comment by jbunce** [comment]
Derp, spelt the e-mail address incorrectly. User error.

**Comment by msirovy** [comment]
I don't think it is fixed

I tested it this way:

config.tf
provider "cloudflare" {
    version = "~> 2.0"
    email   = "mXXXXX@XXXmail.com"
    api_key = "c152XXXXXXXXXXXXXXXXXXXXXXXXd7"
    account_id = "85XXXXXXXXXXXXXXXXXXXXXX68"
}


terraform import cloudflare_zone.pokus_com c1528e5c9d484157a049c02d6834d887

Error: Error finding Zone "c1528e5c9d484157a049c02d6834d887": error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":6003,\"message\":\"Invalid request headers\",\"error_chain\":[{\"code\":6103,\"message\":\"Invalid format for X-Auth-Key header\"}]}],\"messages\":[],\"result\":null}"


In code I have see this:
terraform-provider-cloudflare/vendor/github.com/cloudflare/cloudflare-go/cloudflare.go

    if authType&AuthKeyEmail != 0 {
        req.Header.Set("X-Auth-Key", api.APIKey)
        req.Header.Set("X-Auth-Email", api.APIEmail)
    }
    if authType&AuthUserService != 0 {
        req.Header.Set("X-Auth-User-Service-Key", api.APIUserServiceKey)
    }
    if authType&AuthToken != 0 {
        req.Header.Set("Authorization", "Bearer "+api.APIToken)
    }

    if api.UserAgent != "" {
        req.Header.Set("User-Agent", api.UserAgent)
    }

    if req.Header.Get("Content-Type") == "" {
        req.Header.Set("Content-Type", "application/json")
    }


Curl below works for me, so I think it is not a problem with rights or something like this. Please try it

**Comment by goluzdravi-penzioner** [comment]
Encountered the same issue:
`Terraform v0.12.24
+ provider.cloudflare v2.5.1`

`provider "cloudflare" {
  version = "~> 2.0"
  email   = var.cloudflare_email
  api_key = var.cloudflare_api_key
}

data "cloudflare_zones" "dns_zone" {
  filter {
    name   = "XXX.XX"
    status = "active"
    paused = false
  }
}

output "zone_id" {
  value = data.cloudflare_zones.dns_zone.id
}
`
`terraform apply
data.cloudflare_zones.dns_zone: Refreshing state...

Error: error listing Zone: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":6003,\"message\":\"Invalid request headers\",\"error_chain\":[{\"code\":6103,\"message\":\"Invalid format for X-Auth-Key header\"}]}],\"messages\":[],\"result\":null}"

  on dns-records.tf line 1, in data "cloudflare_zones" "dns_zone":
   1: data "cloudflare_zones" "dns_zone" {`

**Comment by jacobbednarz** [comment]
Please open a new issue specific to your issue and following the issue template, don’t piggyback on an existing closed one.
