### ISSUE TITLE
ipv6_cidr_blocks returns IPv4 addresses

### ISSUE THREAD

**Issue by koitsu** [terraform-providers/terraform-provider-cloudflare#55]
While trying to integrate fetching CloudFlare IPs for use in an AWS security group used with an ELB, I found that cidr_blocks returned both IPv4 and IPv6 addresses (great), ipv4_cidr_blocks returned IPv4 addresses (great), and ipv6_cidr_blocks returned IPv4 addresses (what?!).

I thought I was going out of my mind at first, but I discovered #6 which lead me to #27 and then #28.  This forced me to look at the code.  I speak several PLs (assembly, C, Perl, PHP, etc.) but not Go.  Yet, this is what I found:

https://github.com/terraform-providers/terraform-provider-cloudflare/blob/0b67bf2d55bccd24275f30e2112756abd27a070f/cloudflare/data_source_ip_ranges.go#L73

This looks like a copy-paste typo that happens to be quite severe.

**Comment by koitsu** [comment]
I'd also like to add that the tests in cloudflare/data_source_ip_ranges_test.go don't really appear to test anything but (in effect) cidr_blocks; there is no ipv4_cidr_block vs. ipv6_cidr_block separation, which I would guess would be why tests never caught it.

**Comment by beeceej** [comment]
It looks like Pull https://github.com/terraform-providers/terraform-provider-cloudflare/pull/51/files is handling this

**Comment by patryk** [comment]
I've merged #51. Thanks guys!
