### ISSUE TITLE
Support WAF Overrides

### ISSUE THREAD

**Issue by Evesy** [terraform-providers/terraform-provider-cloudflare#554]
[WAF Overrides](https://api.cloudflare.com/#waf-overrides-properties) allow differing behaviour of WAF rules based on the requested URI.

It would be good to support this as a Terraform resource, e.g.:

```
resource "cloudflare_waf_override" "some-example" {
  urls = ["example.com/*", "example.net/foobar"]

  rules = {
    "100015": "disable"
  }
  description = "Disable 100015"
}
```

**Comment by jacobbednarz** [comment]
This looks fairly recent so needs to be added upstream in cloudflare-go first.

**Comment by jacobbednarz** [comment]
This is now unblocked as the `cloudflare/cloudflare-go` changes landed in this repository.

**Comment by danielmotaleite** [comment]
Any info when this may show up in terraform? few months? lot of months? years?

**Comment by jacobbednarz** [comment]
If this is functionality you would like to see in the provider, please, 
open a PR with the proposed changes and I'll gladly review it.

It's not on the top of my to-do list at the moment but I'm happy to 
review the changes and get it over the line if you need it.
