### ISSUE TITLE
Required field evaluated on count 0 

### ISSUE THREAD

**Issue by rolandg** [terraform-providers/terraform-provider-cloudflare#558]
### Terraform Version

```
Terraform v0.12.17
+ provider.cloudflare v2.2.0
```

### Affected Resource(s)
- cloudflare_load_balancer_pool

### Terraform Configuration Files
```hcl
provider "cloudflare" {
  version = "~> 2.0"
  email   = local.cloudflare_email
  api_key = local.cloudflare_api_key
}

locals {
  cloudflare_email = "a"
  cloudflare_api_key = "b"
}

resource "cloudflare_load_balancer_pool" "test" {
  name    = "test"
  monitor = "sth"

  count = 0

  dynamic "origins" {
    for_each = []

    content {
      name = origins.value
      address = "${origins.value}.example.com"
      enabled = true
    }
  }
}
```

### Expected Behavior
terraform should not check if there is a origin block if count is 0

### Actual Behavior
```
Error: "origins": required field is not set

  on test.tf line 13, in resource "cloudflare_load_balancer_pool" "test":
  13: resource "cloudflare_load_balancer_pool" "test" {
```

### Steps to Reproduce
```
terraform plan
```

**Comment by jacobbednarz** [comment]
I haven't used dynamics much but don't you need something to use as the `for_each` iterator? If that's empty, it seems to make sense that the error is telling you the `origins` is missing.

**Comment by rolandg** [comment]
Hi
this is just an example. The content of the for_each property is generated dynamically depending on the number of nodes in the cluster. If there is only one nodes it generates an empty array here and it sets the count to 0.

**Comment by jacobbednarz** [comment]
My apologies, I'm still not seeing the issue here. Let me outline my current understanding.

You're attempting to create `cloudflare_load_balancer_pool` resource which has a required argument of `origins`. However, you're using a dynamic which evaluates to being empty. In essence, what you're doing is this (due to the dynamic):

```hcl
resource "cloudflare_load_balancer_pool" "test" {
  name    = "test"
  monitor = "sth"
}
```

Which matches what I would expect to error as you've shown as `origins` isn't present. For this to not error, `for_each` needs to be enumerable.

**Comment by jacobbednarz** [comment]
Closing due to lack of information and follow up. Feel free to either open a new issue with more specifics or respond here if there is new information to further the debugging.

**Comment by rolandg** [comment]
I worked around this using a empty fallback origin when count is 0.
