### ISSUE TITLE
cloudflare_zones returns a list instead of a map

### ISSUE THREAD

**Issue by jakubgs** [terraform-providers/terraform-provider-cloudflare#569]
In `2.3.0` version of provider `cloudflare_zones` data source returns a list of maps, rather than a map.

It's much less useful to return a list because You'd have to search through it to find what I want. What I'd expect is an easily searchable map:
```tf
data "cloudflare_zones" "active" {
  filter { status = "active" }
}

resource "cloudflare_record" "test" {
  zone_id = lookup(data.cloudflare_zones.active.zones, "example.org")
  name    = "name"
  value   = "1.2.3.4"
}
```

**Comment by jacobbednarz** [comment]
This looks to be intentional for the use case provided in #168. Is there a reason that the outline there doesn’t work for your particular use case?

**Comment by jakubgs** [comment]
I guess this would have been a bigger issue before Terraform 0.12, now I can just do:
```tf
data "cloudflare_zones" "active" {
  filter { status = "active" }
}

locals {
  zones = {
    for zone in data.cloudflare_zones.active.zones:
      zone.name => zone.id
  }
}
```
Cheers!
