### ISSUE TITLE
Incorrect sample in IP ranges data source docs

### ISSUE THREAD

**Issue by cooperbenson-qz** [terraform-providers/terraform-provider-cloudflare#574]
The [doc example](https://www.terraform.io/docs/providers/cloudflare/d/ip_ranges.html) for using the `cloudflare_ip_ranges` data source is incorrect. It should be passed directly to `source_ranges` since it's a list of strings, instead of being templated into a string.

```
source_ranges = ["${data.cloudflare_ip_ranges.cloudflare.ipv4_cidr_blocks}"]
```
should be 
```
 source_ranges = data.cloudflare_ip_ranges.cloudflare.ipv4_cidr_blocks
```
### Terraform Version
N/A

### Affected Resource(s)
- cloudflare_ip_ranges

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
N/A

### Important Factoids
N/A

### References
Output schema definition [source](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/cloudflare/data_source_ip_ranges.go#L25)

**Comment by jacobbednarz** [comment]
This just hasn’t been updated for 0.12 (works as expected in 0.11). 

Happy to review a PR to get this updated.
