### ISSUE TITLE
Feature request: Please support the at sign

### ISSUE THREAD

**Issue by sixcorners** [terraform-providers/terraform-provider-cloudflare#600]
### Terraform Version
Terraform v0.12.16
+ provider.cloudflare v2.3.0

### Affected Resource(s)
Please list the resources as a list, for example:
- cloudflare_record
- might be other things

### Terraform Configuration Files
```hcl
resource "cloudflare_record" "root" {
  zone_id = var.cloudflare_zone_id
  type    = "CNAME"
  name    = var.name
  value   = "cloudflare-ipfs.com"
}

resource "cloudflare_record" "dnslink" {
  zone_id = var.cloudflare_zone_id
  type    = "TXT"
  name    = "_dnslink.${var.name}"
  value   = "dnslink=${var.dnslink}"
}
```
```hcl
module "root" {
  source             = "../dnslink"
  cloudflare_zone    = var.cloudflare_zone
  cloudflare_zone_id = var.cloudflare_zone_id
  name               = "@"
  dnslink            = "/ipfs/something"
}
```

### Actual Behavior
Error: Failed to create record: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1004,\"message\":\"DNS Validation Error\",\"error_chain\":[{\"code\":9000,\"message\":\"invalid or missing name\"}]}],\"messages\":[],\"result\":null}"

### Important Factoids
It would be nice if @ was interpreted to mean the current domain even not the only character. That's how the web UI handles it. It would make my dnslink module work with the root domain without any weird stuff.

It would actually be nice if the API itself was improved to handle this. Is there a place I can submit suggestions for that?

**Comment by sixcorners** [comment]
For now I'm doing this in the module:
```hcl
  name    = var.name == "@" ? "_dnslink" : "_dnslink.${var.name}"
```

**Comment by jacobbednarz** [comment]
> It would be nice if @ was interpreted to mean the current domain even not the only character. 

This is unfortunately a violation of [rfc1035](https://tools.ietf.org/html/rfc1035) as only a freestanding `@` symbol is considered to be usable for the current domain. `www.@` shouldn't work in any case. 

The way you're doing it now, is the preferred and supported way - using variables.

For all Cloudflare support enquiries, you should [contact support](https://support.cloudflare.com/hc/en-us) or your CSM/TAM. In this case, I wouldn't hold my breathe as the change is not only violating a IETF specification but also giving a special meaning to a character that overlaps with other functionality.

**Comment by jficz** [comment]
This is unfortunate. RFC1035 doesn't support `@` except freestanding but on the other hand a record without `.` at the end is (or at least should be) equal to `<record>.@`, which is, however, apparently not supported by Cloudflare.

What's funny is that you actually can type `@` to Cloudflare Web UI when creating record (to the target field) and it gets applied, rewriting the `@` symbol by the root domain name but it isn't possible to add a freestanding `<record>` not ending by `.` which should by interpreted as `<record>.root.domain.`

So this module exposes UX inconsistency between the Web UI and API. Not sure there's anything to fix in this module except maybe doing some value validation and adding the root domain automatically when there's no `. ` at the end but I'm not sure if the root domain name is even available at the time.

It's bad UX but this is a problem on Cloudflare API and DNS interpretation.
