### ISSUE TITLE
Feature request: allow zone lookup on token constrainted to a specific zone

### ISSUE THREAD

**Issue by sixcorners** [terraform-providers/terraform-provider-cloudflare#601]
### Terraform Version
Terraform v0.12.20
+ provider.cloudflare v2.3.0

### Affected Resource(s)
Please list the resources as a list, for example:
- cloudflare_zones

### Terraform Configuration Files
```hcl
provider "cloudflare" {
  api_token = "something"
}

data "cloudflare_zones" "domains" {
  filter {}
}

output "text" {
	value = data.cloudflare_zones.domains
}
```

### Actual Behavior
Error: error listing Zone: error from makeRequest: HTTP status 403: insufficient permissions

### Important Factoids
I would be nice if we could look up the zone information even if we had a token that has a restriction to only a specific zone.

This is more a request for a change to the cloudflare API.

**Comment by jacobbednarz** [comment]
This isn't something that can be resolved in the provider and will need to be lodged with Cloudflare support to route to the correct team to investigate. 

Before doing so, I'd recommend you read double check the [API tokens documentation](https://support.cloudflare.com/hc/en-us/articles/200167836-Managing-API-Tokens-and-Keys#12345680) and ensure you've triple checked it's not a misconfiguration of the policy itself as it's an easy thing to do if you're not familiar with the ins and outs of it. Perhaps start with an open policy and continue shrinking it's access until you pinpoint the issue.
