### ISSUE TITLE
Error while import workers to tfstate.

### ISSUE THREAD

**Issue by ahamed-atypon** [terraform-providers/terraform-provider-cloudflare#604]
### Terraform Version

```
terraform --version
Terraform v0.12.21
```

### Terraform Configuration Files

```hcl
resource "cloudflare_worker_route" "worker_route_*****_org0" {
	zone_id = "d4ebf2**********"
	pattern = "******.org/*"
	script_name = "cloudflare-workers-*****"
	

}

resource "cloudflare_worker_script"  "worker_script_*****_org0" {
	name = "*****_org"
	content = file("${path.module}/*****_org.js")
}
```

### Debug Output

GET /client/v4/accounts/*******/workers/scripts/worker_script_*****_org0 HTTP/1.1
Host: api.cloudflare.com
User-Agent: HashiCorp Terraform/0.12.21 (+https://www.terraform.io) Terraform Plugin SDK/1.4.1 terraform-provider-cloudflare/2

Content-Type: application/json
X-Auth-Email: *******
X-Auth-Key: ********
Accept-Encoding: gzip

-----------------------------------------------------
2020/02/26 19:22:15 [DEBUG] Cloudflare API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 404 Not Found
Cf-Cache-Status: DYNAMIC
Cf-Ray: *****-ZDM
Content-Type: application/json; charset=UTF-8
Date: Wed, 26 Feb 2020 17:22:15 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Served-In-Seconds: 0.071
Server: cloudflare
Set-Cookie: __cfduid=*********; expires=Fri, 27-Mar-20 17:22:14 GMT; path=/; domain=.api.clo

Strict-Transport-Security: max-age=31536000
Vary: Accept-Encoding
X-Envoy-Upstream-Service-Time: 11

{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10007,
      "message": "workers.api.error.not_found"
    }
  ],
  "messages": []
}

### Crash Output

```
module.*****_org.cloudflare_worker_script.worker_script_*****_org0: Importing from ID "worker_route_*****_org0"...

Error: nil entry in ImportState results. This is always a bug with
the resource that is being imported. Please report this as
a bug to Terraform.
```
### Expected Behavior

Import exist worker to state file

### Actual Behavior

Error raise.

```
module.*****_org.cloudflare_worker_script.worker_script_*****_org0: Importing from ID "worker_route_*****_org0"...

Error: nil entry in ImportState results. This is always a bug with
the resource that is being imported. Please report this as
a bug to Terraform.
```
### Steps to Reproduce

1. `terrafomr import module.*****_org.cloudflare_worker_route.worker_route_******_org0
`
2. `terraform import module.*****_org.cloudflare_worker_script.worker_script_*****_org0 worker_script_*****_org0 ` 
### Additional Context

From debug output seems that the provider trying to get the worker script using invalid URL:

We have the same result using curl:

```
curl -X GET "https://api.Cloudflare.com/client/v4/accounts/*******/workers/scripts/worker_script_*****_org0" -H "X-Auth-Key: ******" -H "X-Auth-Email:*****"  -H "Content-Type: application/json" 

{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10007,
      "message": "workers.api.error.not_found"
    }
  ],
  "messages": []
}


```

**Comment by jacobbednarz** [comment]
The URL structure is correct and the error you’re getting back is that the script doesn’t exist. I’d recommend checking the data you’re providing it such as account ID, script name and permissions as this doesn’t look to be a provider bug.

**Comment by morgoved** [comment]
i have the same problem

c```
url -X GET "https://api.Cloudflare.com/client/v4/accounts/XXXXXXXXXXXXXXX/workers/scripts/adhoc_url_rewrites" -H "X-Auth-Key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX" -H "X-Auth-Email:XXXXX@XXXX.com"  -H "Content-Type: application/json"
{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10007,
      "message": "workers.api.error.script_not_found"
    }
  ],
  "messages": []
}
```
but in web interface i can see this worker
