### ISSUE TITLE
Can't deploy cloudflare_worker_script resource - Enterprise only request

### ISSUE THREAD

**Issue by WheelsVT** [terraform-providers/terraform-provider-cloudflare#607]
### Terraform Version
0.12.20

### Affected Resource(s)
cloudflare_worker_script

### Expected Behavior
Worker created with random name linked to a given cloudflare_worker_route.

### Actual Behavior
On "terraform apply" it throws an error "Error: error creating worker script: account ID required for enterprise only request" then references the definition "resource "cloudflare_worker_script" "worker_script" {"

### Steps to Reproduce
Create a .tf file:
resource "cloudflare_worker_route" "worker_request" {
    pattern = "patterntomatch"
    zone_id = "****"
    script_name = "myworkerscript"
}
resource "cloudflare_worker_script" "worker_script" {
	name  = "myworkerscript"
	content = "test"
}

Run `terraform apply`

**Comment by patryk** [comment]
The underlying API requires you to provide Account ID, but the error message indicated the API to be Enterprise-only, which is not true any more. We forgot to change that message. Sorry!

**Comment by WheelsVT** [comment]
Thanks @patryk !
I have my Account ID configured as an environment variable under `CLOUDFLARE_ACCT_ID`, but I still get that (now updated) error message kicked back from Terraform. Wrangler deployment via web requests work just fine.

**Comment by patryk** [comment]
Did you misspell `CLOUDFLARE_ACCOUNT_ID` maybe?

**Comment by WheelsVT** [comment]
Yes. I was going off of the [CloudFlare Blog post](https://blog.cloudflare.com/introducing-cf-terraform/) on Cf-terraforming where they use `CLOUDFLARE_ACCT_ID`. Switched to `CLOUDFLARE_ACCOUNT_ID` and it's working now. Thanks!
