### ISSUE TITLE
data "cloudflare_zones" "example" output id it's a timestamp

### ISSUE THREAD

**Issue by carboniluca** [terraform-providers/terraform-provider-cloudflare#609]
Retrieving the id of the zones from the data "cloudflare_zones" I'm receiving two different results: 

- if I create an output using the  **id** I receive as a result a timestamp. 
- if I create an output using the **zones** I receive the right id of the zone, parsable in this way: data.cloudflare_zones.example.zones[0]["id"]

### Terraform Version
terraform version 0.12.18 and also 0.12.21
plugin version 2.3

### Affected Resource(s)
- data.cloudflare_zones

### Expected Behavior
to receive the correct id of the zone using the the "id" output reference or the "zones[0]["id"] output reference

### Actual Behavior
the output "id" reference is a timestamp of the request, the output "zones[0]["id"] seems to be correct. 

### Steps to Reproduce
`
provider "cloudflare" {
  version = "~> 2.3"
}
data "cloudflare_zones" "example" {
  filter {
    name   = "example.com"
    status = "active"
    paused = false
  }
}

output "zone_id" {
  value = data.cloudflare_zones.example.id
}

output "zone_names" {
  value = data.cloudflare_zones.example.zones[0]["id"]
}`

1. terraform init
2. terraform apply

**Comment by joel-g** [comment]
Hi @carboniluca,

Using the "filter" in the data block returns an array of zones. The ID is the timestamp of when the filter was applied. This is intended. To get the ID of the zones you must iterate over the array or call on a particular zone by it's index as you demonstrated.

**Comment by rafilkmp3** [comment]
how this could be possible intended?
