### ISSUE TITLE
Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by lvnilesh** [terraform-providers/terraform-provider-cloudflare#613]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
 terraform -v
Terraform v0.12.23
+ provider.cloudflare v1.18.1
+ provider.digitalocean v1.14.0
+ provider.external v1.2.0
+ provider.helm v1.0.0
+ provider.kubernetes v1.11.1
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.template v2.1.2
```
### Affected Resource(s)
Please list the resources as a list, for example:
- cloudflare_record.wildcard

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "null_resource" "ingressnginxip" {
  depends_on = [helm_release.ng]

  provisioner "local-exec" {
    command = "kubectl --namespace default get services -o wide ng-nginx-ingress-controller |grep LoadBalancer |awk '{print $4}' > ./ingressnginxip"
  }
}

# Add a record to the domain
resource "cloudflare_record" "wildcard" {
  depends_on = [null_resource.ingressnginxip]
  domain     = var.cloudflare_zone
  name       = "*"

  // delete     = "false"
  value = chomp(file("./ingressnginxip"))
  type  = "A"
  ttl   = 120
}

```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

```

Error: Provider produced inconsistent final plan

When expanding the plan for cloudflare_record.wildcard to include new values
learned so far during apply, provider "registry.terraform.io/-/cloudflare"
produced an invalid new value for .value: was cty.StringVal("157.230.198.72"),
but now cty.StringVal("157.230.198.76").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

success

### Actual Behavior
What actually happened?

failure

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

`terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

none

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? 

none

**Comment by jacobbednarz** [comment]
Thanks for raising this one @lvnilesh. Stripping this down to just the Cloudflare resources, I'm unable to replicate given the following configuration.

```
resource "cloudflare_record" "wildcard" {
  domain     = var.cloudflare_zone
  name       = "*"

  value = "1.2.3.4"
  type  = "A"
  ttl   = 120
}
```

I'd recommend you update to the latest version of the provider (as there improvements and bug fixes included that might help you) and isolate each of these components separately to work out which one is misbehaving and giving you the inconsistent result your seeing here. Do let me know if there is something I've missed in the test case above.

**Comment by lvnilesh** [comment]
Thanks. I understand. Is there a tf resource to PATCH that wildcard record?

**Comment by lvnilesh** [comment]
like this.

```
export loadbalancerip="$(kubectl --namespace default get services -o wide ng-nginx-ingress-controller |grep LoadBalancer |awk '{print $4}')"

curl -X PATCH "https://api.cloudflare.com/client/v4/zones/zoneid/dns_records/recordid" \
  -H "X-Auth-Email: email@address" \
  -H "X-Auth-Key: key" \
  -H "Content-Type: application/json" \
  --data '{"type":"A","name":"*.domain.com","content": "'"$loadbalancerip"'", "ttl":120,"proxied":false}' | jq
```

**Comment by jacobbednarz** [comment]
Under the hood, Terraform already handles the update for you using the PATCH endpoint via [`resourceCloudflareRecordUpdate`](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/cloudflare/resource_cloudflare_record.go#L19) on the resource when a change is proposed.

**Comment by jacobbednarz** [comment]
Your issue looks like you've got another source updating this outside of Terraform which is causing the inconsistent state. Anything you manage in Terraform shouldn't be touched outside of Terraform otherwise you're going to have a bad time with keeping the state up to date.

**Comment by lvnilesh** [comment]
my intent with using PATCH was to have just one unique IP address assigned to wildcard.

I see multiple records for wildcard, when I use terraform like this, 

```
resource "cloudflare_record" "wildcard" {
  depends_on  = [helm_release.ng]

  provisioner "local-exec" {
    command = "rm -rf ./ingressnginxip"
  }
  provisioner "local-exec" {
    command = "echo $(kubectl --namespace default get services -o wide ng-nginx-ingress-controller |grep LoadBalancer |awk '{print $4}') > ./ingressnginxip "
  }

  domain      = var.cloudflare_zone
  name        = "*"
  value       = chomp(file("./ingressnginxip"))
  type        = "A"
  ttl         = 120
  proxied     = false
}
```


How do I use terraform so it overwrites the old entry and puts new IP address entry in place of the old?

Appreciate your help. Thanks.
