### ISSUE TITLE
Include Tenant API calls

### ISSUE THREAD

**Issue by Camilia** [terraform-providers/terraform-provider-cloudflare#627]
Some of Cloudflare partners are using Terraform and would make sense to include Tenant API calls which are listed here: https://developers.cloudflare.com/tenant/tutorial/
- User Account creation/deletion, adding additional user account
- Zone(Domain) creation/deletion
- Subscription creation/deletion

Many thanks, 
Camilia

**Comment by jacobbednarz** [comment]
Please see the documentation site at https://www.terraform.io/docs/providers/cloudflare/ as it looks like these are already covered. 

If you find one that is missing, please follow the issue template by filling out the required sections when raising requests.
