### ISSUE TITLE
datasource id attribute is returning wrong data

### ISSUE THREAD

**Issue by rafilkmp3** [terraform-providers/terraform-provider-cloudflare#634]
### Terraform Version
```
terraform -v
Terraform v0.12.24
+ provider.aws v2.54.0
+ provider.cloudflare v2.4.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- cloudflare_zones

### Terraform Configuration Files
```hcl
data "cloudflare_zones" "selected_zone" {
  filter {
   name   = var.domain_name
  }
}
output "zones" {
  value = data.cloudflare_zones.selected_zone.*
}
```

### Debug Output
```
zones = [
  {
    "filter" = [
      {
        "name" = "example.com"
        "paused" = false
        "status" = ""
      },
    ]
    "id" = "2020-03-25 14:59:32.994945 +0000 UTC"
    "zones" = [
      {
        "id" = "17685e579210ac0XXXXXXXX"
        "name" = "example.com"
      },
    ]
  },
]
```

### Expected Behavior
id attribute must be have the zone_id 

`"id" = "17685e579210ac0XXXXXXXX"`

### Actual Behavior
id attribute have the date from api

` "id" = "2020-03-25 14:59:32.994945 +0000 UTC"`

### Steps to Reproduce
Please list the steps required to reproduce the issue:
1. `terraform apply`

### Important Factoids
this makes impossible to use datasource to filter from domain

### References
https://www.gitmemory.com/issue/terraform-providers/terraform-provider-cloudflare/211/480733485

### Workarround 

`lookup(data.cloudflare_zones.selected_zone.zones[0], "id")`

https://github.com/rafilkmp3/terraform-aws-acm-cloudflare/blob/6fddd84f213a31a4a873c98b454f3851a0c40bef/main.tf#L2

**Comment by jacobbednarz** [comment]
#609 explains this and how to use the data correctly.
