### ISSUE TITLE
Reversed 'priority' Order on 'cloudflare_page_rule'

### ISSUE THREAD

**Issue by anton-yurchenko** [terraform-providers/terraform-provider-cloudflare#638]
It looks like an issue with CloudFlare API, raising here for others to be aware of that:

### Terraform Version
Terraform v0.12.13

### Affected Resource(s)
- cloudflare_page_rule

### Terraform Configuration Files
```hcl
resource "cloudflare_page_rule" "alias" {
  zone_id = var.cloudflare_zone_ids[local.domain]
  target  = "${local.alias}.${local.domain}/*"
  status  = "active"
  priority = 1

  actions {
    cache_level = "bypass"
  }
}
```

### Expected Behavior
As per [provider](https://www.terraform.io/docs/providers/cloudflare/r/page_rule.html#priority) and [CloudFlare API](https://api.cloudflare.com/#page-rules-for-a-zone-create-page-rule) documentation:
- rule with `priority=1` should be created as rule number 1.
- rule with `priority=2` should be created as rule number 2.

### Actual Behavior
In practice, the order is reversed. For example, in my case:
- `priority=1` results in rule number 12 (last).
- `priority=2` results in rule number 11.

### Steps to Reproduce
Create a **cloudflare_page_rule**.

---

### CloudFlare API
Executing the following results in exactly the same behavior like in Terraform, which proves that there is an issue with CloudFlare API:
```bash
curl -X POST "https://api.cloudflare.com/client/v4/zones/023e105f4ecef8ad9ca31a8372d0c353/pagerules" \
     -H "X-Auth-Email: user@example.com" \
     -H "X-Auth-Key: c2547eb745079dac9320b638f5e225cf483cc5cfdda41" \
     -H "Content-Type: application/json" \
     --data '{"targets":[{"target":"url","constraint":{"operator":"matches","value":"test.example.com"}}],"actions":[{"id":"cache_level","value":"bypass"}],"priority":1,"status":"active"}'
```

---

## References
Raised that issue to CloudFlare via its Go module.
- [cloudflare-go issue](https://github.com/cloudflare/cloudflare-go/issues/436)

**Comment by jacobbednarz** [comment]
Please see #187 for an explanation and workaround.

**Comment by anton-yurchenko** [comment]
I have a slightly different case where multiple Terraform projects are creating Page Rules on a single CloudFlare zone. 
Anyway, I just wanted to raise that issue for others to be aware of :blush:
Thank you @jacobbednarz

**Comment by jacobbednarz** [comment]
Sounds like a recipe for inconsistency and disaster. You will need to use the approach mentioned in the linked issue and have the source code depending on one another or you’re going to end up with incorrect or partial ordering changes.

**Comment by anton-yurchenko** [comment]
got it, will do. thank you!
