### ISSUE TITLE
Feature request: Please add resource for standalone healthchecks

### ISSUE THREAD

**Issue by dlavrichev** [terraform-providers/terraform-provider-cloudflare#645]
Hi there,

Can you please add a resource for standalone healthchecks?
Something similar to your API: https://api.cloudflare.com/#health-checks-create-health-check

**Comment by cehrig** [comment]
@jacobbednarz @patryk anyone of you already working on this? If not I'd pick this up.

**Comment by jacobbednarz** [comment]
Nothing from me. Happy if you want to take a pass at it.

**Comment by jacobbednarz** [comment]
Closed via #680
