### ISSUE TITLE
Cannot create a cloudflare_zone with  a subdomain

### ISSUE THREAD

**Issue by eyeezzi** [terraform-providers/terraform-provider-cloudflare#655]
### Terraform Version

```
Terraform v0.12.20
```

### Affected Resource(s)
- cloudflare_zone

### Terraform Configuration Files
```hcl
resource "cloudflare_zone" "samplesite-com" {
  zone = "samplesite.com"
  type = "partial"
}

resource "cloudflare_zone" "api-samplesite-com" {
  zone = "api.samplesite.com"
}

resource "cloudflare_record" "staging-api-samplesite-com" {
  domain = cloudflare_zone.api-samplesite-com.zone
  name   = "*.staging"
  value  = "<dns address of my staging k8s cluster>"
  type   = "CNAME"
  ttl    = 300
}
```

### Debug Output
https://gist.github.com/eyeezzi/438a2fcfec4ef373c571017176a7c92d

### Panic Output
n/a

### Expected Behavior
A site named `api.samplesite.com` should be created, and visible in the Cloudflare console.

### Actual `Behavior`
Creating the site fails, with an error requesting that the site name NOT be a subdomain.

### Steps to Reproduce
1. Create a `cloudflare_zone` based on a naked domain: eg `samplesite.com`
2. Try creating another `cloudflare_zone` based on a subdomain of an existing zone: eg `api.samplesite.com`

### Important Factoids
I can accomplish this exact goal using the Cloudflare Console: i.e I encounter no errors when creating a Site named `api.samplesite.com`.

### References
n/a

**Comment by jacobbednarz** [comment]
The exception you've raised in your gist is a HTTP error from the Cloudflare API itself, not the provider.

```json
{
  "success": false,
  "errors": [
    {
      "code": 1116,
      "message": "Please ensure you are providing the root domain and not any subdomains (e.g., example.com, not subdomain.example.com)"
    }
  ],
  "messages": [],
  "result": null
}
```

Are you able to enable debugging (prefix your terraform apply with `TF_LOG=DEBUG`) and compare it with the console HTTP API calls when you add the new site there?

**Comment by patryk** [comment]
This is expected when you don't have Subdomain Support enabled on your account. Please contact support to verify it.
Plus, don't mix partial and full zones, this setup is not supported and can result in unpredictable behaviour.
