### ISSUE TITLE
Enabling log retention (Logpull API)

### ISSUE THREAD

**Issue by binc75** [terraform-providers/terraform-provider-cloudflare#665]
Hello,

it would be nice to be able to activate/deactivate the **log retention** for the **Logpull API** via terraform provider.

Here a link to the documentation:
https://developers.cloudflare.com/logs/logpull-api/enabling-log-retention/

At a glance, there are two endpoints for managing log retention:
```
GET /logs/control/retention/flag - returns whether retention is on
POST /logs/control/retention/flag - turns retention on or off
```
Thank you for your great work!
Best regards!
  Nicola

**Comment by jacobbednarz** [comment]
Seems straight forward enough! We'll need to get this added to the `cloudflare-go` library and we can then add a new resource along the following lines:

```hcl
resource "cloudflare_logpull_retention" "example" {
  enabled = true
}
```

**Comment by jacobbednarz** [comment]
Add support for this upstream at cloudflare/cloudflare-go#448
