### ISSUE TITLE
Creating Access Policy with non_identity and Specified service_token Fails To Create

### ISSUE THREAD

**Issue by BrysonR** [terraform-providers/terraform-provider-cloudflare#676]
### Terraform Version
v0.12.24

### Affected Resource(s)
- cloudflare_access_policy

### Terraform Configuration Files
```hcl
provider "cloudflare" {
  version = "~> 2.0"
  email   = "<email>"
  api_key = "<global-api-key>"
}
```

### Debug Output
[terraform apply debug log](https://gist.github.com/BrysonR/cd5e115424d67443ab59d3339ed95d74)

### Expected Behavior
```hcl
resource "cloudflare_access_policy" "web_service_tokens_policy" {
  ...
  decision       = "non_identity"

  include {
    service_token = [cloudflare_access_service_token.app_service_token.id]
  }
}
```
should create a resource that attaches the specified `app_service_token` to the defined policy as decision type `non_identity`

### Actual Behavior
This actually produces an `invalid_policy` error seen in the [linked gist](https://gist.github.com/BrysonR/fd3e1a295c2bbe800587872c04ce79fe)

### Steps to Reproduce
1. `terraform apply`

### References
The following PR is where this feature was added
- [Support service_token for cloudflare_access_policy](https://github.com/terraform-providers/terraform-provider-cloudflare/pull/612)

**Comment by jacobbednarz** [comment]
The linked gist isn’t working, are you able to dump it in here being sure to include the whole log with redacted sensitive information?

**Comment by BrysonR** [comment]
I deleted the old gist as i'd missed a few sensitive items. the link should work now. Let me know if you need me to post more from the log in there.

**Comment by jacobbednarz** [comment]
Yes please. The whole log would be ideal as we need things like the setup, requests and responses leading up to and including the errors.

**Comment by BrysonR** [comment]
Updated the gist.

**Comment by jacobbednarz** [comment]
Your payloads are missing an [`application_id`](https://www.terraform.io/docs/providers/cloudflare/r/access_policy.html#application_id). Are you able to confirm that is present in your configuration?

**Comment by jacobbednarz** [comment]
I can't reproduce given the following test case.

Terraform: 0.12.24
Provider: 2.6.0
```hcl
provider "cloudflare" {
  email   = var.cloudflare_email
  api_key = var.cloudflare_token
}

variable "cloudflare_email" {}

variable "cloudflare_token" {}

variable "zone_id" {
  default = "71fd296567c77203b944cb20cac79620"
}

variable "account_id" {
  default = "5875f8bba80a6ca22db0c2f219b2e67f"
}

resource "cloudflare_access_application" "example_app" {
  zone_id = var.zone_id
  name    = "sub.example.com"
  domain  = "sub.example.com"
}

resource "cloudflare_access_service_token" "example_service_token" {
  account_id = var.account_id
  name       = "Example token"
}

resource "cloudflare_access_policy" "example_policy" {
  application_id = cloudflare_access_application.example_app.id
  zone_id        = cloudflare_access_application.example_app.zone_id
  name           = "Example"
  precedence     = "1"
  decision       = "non_identity"

  include {
    service_token = [cloudflare_access_service_token.example_service_token.id]
  }
}
```

Suggesting that the issue is with your local configuration or usage of the resources.

**Comment by BrysonR** [comment]
Seems that I imported an already existing token with the client_id, no the id. Works as expected when creating a new token via terraform and then referencing it. Thanks for clearing up.
