### ISSUE TITLE
Access policy gsuite, okta providers fail to handle `identity_provider_id` update

### ISSUE THREAD

**Issue by wolfmd** [terraform-providers/terraform-provider-cloudflare#682]
In the process of importing existing Cloudflare access policies to a tfstate, an issue occurred when importing gsuite or okta. When the `identity_provider_id` value is set per https://www.terraform.io/docs/providers/cloudflare/r/access_group.html#gsuite
```
resource "cloudflare_access_policy" "app_foo_policy" {
  application_id = cloudflare_access_application.app.id
  zone_id        = var.zone_id
  name           = "foo policy"
  decision       = "allow"
  precedence     = 2

  include {
    gsuite {
      name                 = "<gsuite-email>"
      identity_provider_id = cloudflare_access_identity_provider.gsuite.id
    }
  }
}
```
the object returned from the api changes from 
```
          {
            "gsuite": {
              "id": "<id>",
              "email": "<email>",
              "connection_id": "<connection_id>"
            }
          },
```
to
```
          {
            "gsuite": {
              "id": "<id>",
              "email": "<email>",
              "identity_provider_id": "<connection_id>"
            }
          },
```
When this is applied to the gsuite or okta include block, I'm no longer able to log in via these connections.

The same issue occurs when trying to add a new access policy that wasn't previously imported from terraform or when tainting and recreating the access policy

Investigation in the UI provides the following error message when trying to update the access policy
![Screen Shot 2020-05-11 at 2 31 37 PM](https://user-images.githubusercontent.com/8314397/81614938-a3753880-9395-11ea-82bd-89fa6333cd07.png)
 which perhaps implies that the gsuite and okta provider don't support the `identity_provider_id`. This may not be a bug with the terraform module, but I would like to report it in case the behavior of renaming the `connection_id` value to `identity_provider_id` is unintended

**Comment by wolfmd** [comment]
Updated since my ability to login via okta previously seemed to be a fluke

**Comment by wolfmd** [comment]
I hacked together a local struct with ConnectionID instead of IdentityProviderID. Running it against my staging zone it seems to clear this issue up. I'll put together a proper PR for this tomorrow assuming my fix seems correct.

**Comment by analytically** [comment]
Also hitting this issue.

**Comment by Justin-Holmes** [comment]
As stated here https://github.com/cloudflare/cloudflare-go/pull/471, the Access team is deprecating `connection_id` in favor of `identity_provider_id`. The UI has been fixed to allow the `identity_provider_id` field and should no longer show the errors!

**Comment by jacobbednarz** [comment]
I've gone through and re-tested this one with a live resource and I can't replicate with either GSuite or Okta. Here is my reproduction for Okta.

```hcl
variable "cf_email" {}
variable "cf_api_key" {}
variable "cf_account_id" {} 

provider "cloudflare" {
  version = "~> 2.0"
  email   = var.cf_email
  api_key = var.cf_api_key
}

resource "cloudflare_access_identity_provider" "okta_test" {
  account_id = var.cf_account_id
  name       = "Okta testing"
  type       = "okta"
  config {
    okta_account  = "https://jacobterraformtest.okta.com"
    client_id     = "REDACTED"
    client_secret = "REDACTED"
  }
}
```

Which resulted in a successful creation

```
terraform -var "cf_email=$CF_EMAIL" -var "cf_api_key=$CF_API_KEY" -var "cf_account_id=$CF_ACC_ID" apply 

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # cloudflare_access_identity_provider.okta_test will be created
  + resource "cloudflare_access_identity_provider" "okta_test" {
      + account_id = "f037e56e89293a057740de681ac9abbe"
      + id         = (known after apply)
      + name       = "Okta testing"
      + type       = "okta"

      + config {
          + client_id     = "0oae5fmfuNkpfGnVL4x6"
          + client_secret = "**********************************"
          + okta_account  = "https://jacobterraformtest.okta.com"
          + redirect_url  = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudflare_access_identity_provider.okta_test: Creating...
cloudflare_access_identity_provider.okta_test: Creation complete after 1s [id=43fd3a36-96e7-4492-95ca-096378aab0b5]
```

I'm going to close this one off unless we can get a full reproduction test case which I can dig into.
