### ISSUE TITLE
Failure creating cloudflare_access_policy

### ISSUE THREAD

**Issue by groodt** [terraform-providers/terraform-provider-cloudflare#683]
### Terraform Version
Terraform v0.12.9
+ provider.cloudflare v2.6.0

### Affected Resource(s)
cloudflare_access_policy

### Terraform Configuration Files
```hcl
resource "cloudflare_access_policy" "datahub" {
  application_id = "appid"
  zone_id        = "zoneid"
  name           = "Name"
  precedence     = "1"
  decision       = "allow"

  include {
    group = [
      "Group",
    ]
  }
}
```

### Expected Behavior
The resource should be successfully created.

### Actual Behavior
An error occurs
```
Error: error creating Access Policy for ID "": error from makeRequest: HTTP status 500: content "{\n  \"result\": null,\n  \"success\": false,\n  \"errors\": [\n    {\n      \"code\": 10001,\n      \"message\": \"access.api.error.internal_server_error\"\n    }\n  ],\n  \"messages\": []\n}\n"
```

**Comment by wolfmd** [comment]
Is the "Group" string you're using here the name of the group or the id for the group? For instance, when you hit the api endpoint `https://api.cloudflare.com/client/v4/accounts/<account>/access/groups is this the `id` or `uid` field or the `name` field of the group object?

**Comment by groodt** [comment]
> Is the "Group" string you're using here the name of the group or the id for the group? For instance, when you hit the api endpoint `https://api.cloudflare.com/client/v4/accounts/<account>/access/groups is this the `id`or`uid`field or the`name` field of the group object?

I've been using the literal String name of an Okta Group here, similar to the examples here show using `email` https://www.terraform.io/docs/providers/cloudflare/r/access_policy.html

Do I first need to create a `cloudflare_access_group` resource (that includes my Okta Group) and *then* reference this `cloudflare_access_group` instead?

**Comment by wolfmd** [comment]
The `group` include refers to Cloudflare Access Groups rather than Okta groups. While an Okta group can be included in an Access Group, it can also be referenced directly by a policy using this syntax defined in the access group https://www.terraform.io/docs/providers/cloudflare/r/access_group.html#conditions 

So basically in stead of 
```
  include {
    group = [
      "Group",
    ]
  }
```
you'd want
```
  include {
    okta {
      name = "<okta_name>"
      identity_provider_id = "<okta_idp_id>"
    }
  }
```

However, I believe (at least in my testing) the Okta include is currently broken, see https://github.com/terraform-providers/terraform-provider-cloudflare/issues/682 I expect a fix pretty soon though.

**Comment by groodt** [comment]
Thanks, I've tried this.

Almost works. I get the same error as you are getting in #682 when attempting to login.

**Comment by groodt** [comment]
@wolfmd any chance you know what the syntax would be for multiple groups?

```
  include {
    okta {
      name = "A"
      identity_provider_id = "idp"
    }
  }
  include {
    okta {
      name = "B"
      identity_provider_id = "idp"
    }
  }
  include {
    okta {
      name = "C"
      identity_provider_id = "idp"
    }
  }
  include {
    okta {
      name = "D"
      identity_provider_id = "idp"
    }
  }
```

This seems to only add `D` in Cloudflare.

**Comment by wolfmd** [comment]
You only want a single include per policy resource. The include would look like 
```
  include {
    okta {
        connection_id = cloudflare_access_identity_provider.my_okta_provider.id
        name = "A"
    }
    okta {
        connection_id = cloudflare_access_identity_provider.my_okta_provider.id
        name = "B"
    }
  }
```
assuming you defined the identity provider in terraform as a resource with the id `my_okta_provider` or you could do
```
  include {
    okta {
        connection_id = <provider_id>
        name = "A"
    }
    okta {
        connection_id = <provider_id>
        name = "B"
    }
  }
```
where `<provider_id>` is a uuid string that is the `id` or `uid` field from your okta provider when you look it up via https://api.cloudflare.com/client/v4/accounts/<account_id>/access/identity_providers
