### ISSUE TITLE
Unable to create PTR records using Terraform

### ISSUE THREAD

**Issue by satya-toyota** [terraform-providers/terraform-provider-cloudflare#688]
Hi there,

I am unable to create Cloudflare PTR records using Terraform. From the issue [here](https://github.com/terraform-providers/terraform-provider-cloudflare/issues/283), looks like this is fixed, but still facing the same error. 

### Terraform Version
`Terraform v0.12.21`

### Affected Resource(s)
Please list the resources as a list, for example:
- cloudflare_record

### Terraform Configuration Files
```hcl
provider "cloudflare" {
  version = "~> 2.0"
  email   = "<EMAIL>"
  api_key = "<API_KEY>"
}

resource "cloudflare_record" "this" {
  zone_id = "blabla"
  name    = "1.2.3.4"
  type    = "PTR"
  value   = "cf-ptr-test-rec1"
  proxied = true
}
```

### Output
```
Terraform v0.12.21
Configuring remote state backend...
Initializing Terraform configuration...
2020/05/19 19:00:26 [DEBUG] Using modified User-Agent: Terraform/0.12.21 TFE/v202003-1

Error: expected type to be one of [A AAAA CAA CNAME TXT SRV LOC MX NS SPF CERT DNSKEY DS NAPTR SMIMEA SSHFP TLSA URI], got PTR 
```

### Expected Behavior
Cloudflare PTR records should be created

### Actual Behavior
Error message unable to detect `PTR` record type

### Steps to Reproduce
`terraform apply`

### References
https://github.com/terraform-providers/terraform-provider-cloudflare/issues/283

**Comment by jacobbednarz** [comment]
What version of the provider are you using?

**Comment by satya-toyota** [comment]
@jacobbednarz I am using the recent one with this construct. 
`version = "~> 2.0"`

**Comment by jacobbednarz** [comment]
Exact version please. That operator doesn’t mean the latest, just a version within the 2.0 to 3.0 range.

**Comment by satya-toyota** [comment]
Looks like its picking `2.6.0`

**Comment by jacobbednarz** [comment]
One issue I see here is that you're attempting to proxy a PTR record (which isn't possible in Cloudflare https://support.cloudflare.com/hc/en-us/articles/360019093151). I'm checking whether that is interfering here as we have additional validation around that.

**Comment by satya-toyota** [comment]
@jacobbednarz I removed the proxy option but still failing at the `plan` stage itself.

**Comment by jacobbednarz** [comment]
This works on master (your content was still invalid)

```hcl
resource "cloudflare_record" "ptr_repro" {
  zone_id = "ZONE_ID"
  name    = "@"
  type    = "PTR"
  value   = "mail.example.com"
}
```

However trying this on 2.6.0 doesn't which is odd as nothing as changed for records on master vs 2.6.0.

**Comment by satya-toyota** [comment]
@jacobbednarz Which version is master using?

**Comment by jacobbednarz** [comment]
`master` is it's own version; currently 9a8fd43. Which looking at now, @patryk has already fixed this 4 days ago and I am missing his last commit 🤦 

This should be addressed in the next release.

**Comment by satya-toyota** [comment]
Oh ok, will wait for the next release and validate again then. Thanks!
