### ISSUE TITLE
Value of "0" not recognized as value for "browser_cache_ttl"

### ISSUE THREAD

**Issue by tomwassenberg** [terraform-providers/terraform-provider-cloudflare#69]
### Terraform Version
```
Terraform v0.11.7
+ provider.cloudflare v1.0.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `cloudflare_zone_settings_override`

### Terraform Configuration Files
```hcl
resource "cloudflare_zone_settings_override" "example" {
    name = "example.com"
    settings {
      browser_cache_ttl = "0"
    }
}
```

### Expected Behavior
When I entered "0" as a value for the `browser_cache_ttl`, which means "Respect Existing Headers", this should have been accepted as a valid value. This value is missing from Cloudflare's API docs, which I just reported to them and has been acknowledged. In my support ticket they replied "The value you need to use in this case is 0."

### Actual Behavior
Terraform failed with the following output:
```
Error: cloudflare_zone_settings_override.example: expected "settings.0.bro
wser_cache_ttl" to be one of [30 60 300 1200 1800 3600 7200 10800 14400 18000 28
800 43200 57600 72000 86400 172800 259200 345600 432000 691200 1382400 2073600 2
678400 5356800 16070400 31536000], got 0

Command `terraform plan` failed. Exiting.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by jacobbednarz** [comment]
I've updated the validation for `browser_cache_ttl` to include 0 as an acceptable value in #71. Feel free to give it a run and make sure it fixes your issue.

**Comment by patryk** [comment]
Thanks Tom for report!

**Comment by moneyit** [comment]
I got cloudflare page rule config not apply with '0'

**Comment by jacobbednarz** [comment]
@moneyit if you are experiencing issues despite this being addressed already, please open a new issue following the template provided and we'll take a look.
