### ISSUE TITLE
import multiple access rules (more 1600 rules)

### ISSUE THREAD

**Issue by morgoved** [terraform-providers/terraform-provider-cloudflare#694]
Terraform v0.12.23
+ provider.cloudflare v2.7.0

cloudflare_access_rule

i have module 

```
resource "cloudflare_access_rule" "access_rule" {
  count = length(var.PARAMS)
  notes = element(var.PARAMS[count.index], 0)
  mode = "${element(var.PARAMS[count.index], 1)}"
  configuration = {
    target = "${element(var.PARAMS[count.index], 2)}"
    value = "${element(var.PARAMS[count.index], 3)}"
  }
  zone_id = var.ZONE_ID
}
```
and i try run import for examlple first element  
` terraform import  module.access_rules.cloudflare_access_rule.access_rule[0] zone/XXXX_ZONE_ID_XXXX/ID_ACCESS_RULES`

i took all id via cf-terraforming.

and i have as result 

```
Error: nil entry in ImportState results. This is always a bug with
the resource that is being imported. Please report this as
a bug to Terraform.
```
P.S. parts in locals.ft main.tf and variable.tf for a reproduce this problem.
locals.ft 
```
locals {

  ACCESS_RULES = [
    ["Monitor", "challenge", "ip", "111.111.222.123"],
    ["Monitor", "challenge", "ip", "111.111.222.122"],
]
}
```

main.tf
```
module "access_rules" {
  source = "../../modules/access_rule"
  PARAMS = local.ACCESS_RULES
  ZONE_ID = var.ZONE_ID
}
```
variable.tf

`variable ZONE_ID {}`

variable.tfvar
`ZONE_ID = "XXXXXXXXXXXXXXXXXX"`

How i can import data? maybe i do something incorrect or it's a bug?

**Comment by jacobbednarz** [comment]
I'm not sure sorry. Have you tried importing a single rule not using the Terraform loops or modules? To confirm you're set up correctly?

**Comment by morgoved** [comment]
> I'm not sure sorry. Have you tried importing a single rule not using the Terraform loops or modules? To confirm you're set up correctly?

The same result.

**Comment by morgoved** [comment]
Also at now moment access token have only read only right's for to cloudflate. I can get all resources via cf-terraforming.

**Comment by morgoved** [comment]
Solved - using by account_id and it's works.

**Comment by jacobbednarz** [comment]
There are multiple levels of the Access Rules (user, account, zone) and you need to use the correct format for the type of rules you're importing. See the details of this at https://www.terraform.io/docs/providers/cloudflare/r/access_rule.html#import

**Comment by jacobbednarz** [comment]
FWIW, the following works and imports successfully.

```hcl
# repro.tf

variable "cloudflare_email" {}
variable "cloudflare_api_key" {}
variable "zone_id" {}

provider "cloudflare" {
  version = "~> 2.0"
  email   = var.cloudflare_email
  api_key = var.cloudflare_api_key
}

resource "cloudflare_access_rule" "reproduction_rule" {
  notes = "test"
  mode  = "whitelist"
  configuration = {
    target = "ip"
    value  = "101.191.45.38" # my latest IP
  }
  zone_id = var.zone_id
}
```

Running the import

```
$ terraform import cloudflare_access_rule.reproduction_rule \
  -var "cloudflare_api_key=$CF_API_KEY" \
  -var "cloudflare_email=$CF_EMAIL" \
  -var "zone_id=$CF_ZONE_ID" \
  zone/$CF_ZONE_ID/d22aa9e7aa3e4386b056658d6b128440

cloudflare_access_rule.reproduction_rule: Importing from ID "zone/0da42c8d2132a9ddaf714f9e7c920711/d22aa9e7aa3e4386b056658d6b128440"...
cloudflare_access_rule.reproduction_rule: Import prepared!
  Prepared cloudflare_access_rule for import
cloudflare_access_rule.reproduction_rule: Refreshing state... [id=d22aa9e7aa3e4386b056658d6b128440]
```

The state shows the resource as correct.

```
$ terraform state show cloudflare_access_rule.reproduction_rule
# cloudflare_access_rule.reproduction_rule:
resource "cloudflare_access_rule" "reproduction_rule" {
    configuration = {
        "target" = "ip"
        "value"  = "101.191.45.38"
    }
    id            = "d22aa9e7aa3e4386b056658d6b128440"
    mode          = "block"
    notes         = "test"
    zone_id       = "0da42c8d2132a9ddaf714f9e7c920711"
```
