### ISSUE TITLE
Clean up for Cloudflare_zones Data Provider

### ISSUE THREAD

**Issue by beaudryj** [terraform-providers/terraform-provider-cloudflare#696]
Hi there,

I went to use 

```
data "cloudflare_zones" "myzone" {
  filter {
    name   = "myzone.domain.tld"
    status = "active"
    paused = false
  }
}
```

and Referenced as 

```
${data.cloudflare_zones.myzone.id} 
```

I am just very curious as to why it returns a UTC timestamp. I did go back to the docs and cleaned up using the lookup block you have in the documentation, but very curious as to why I need to have to do that, vs just constructing the object appropriately

**Comment by jacobbednarz** [comment]
https://github.com/terraform-providers/terraform-provider-cloudflare/issues/609#issuecomment-594674769 has an explanation of why there is a timestamp and how to work with it.
