### ISSUE TITLE
Unable to import 'cloudflare_access_rule'

### ISSUE THREAD

**Issue by cucxabong** [terraform-providers/terraform-provider-cloudflare#697]
### Terraform Version
Terraform v0.12.26
provider.cloudflare v2.7.0

### Affected Resource(s)
Unable to import `cloudflare_access_rule` resources

### Terraform Configuration Files

```hcl
resource "cloudflare_access_rule" "test" {
  zone_id = "[ZONE_ID]"
  mode = "whitelist"
  notes = "API User"
  configuration = {
    target = "ip"
    value = "1.2.3.4"
  }
}
```

### Debug Output
```
https://gist.github.com/cucxabong/5c07f7f3a196f763d7c9299413c9a59e
```

### Expected Behavior
Import sucessfully

### Actual Behavior
Failed with error (above)

### Steps to Reproduce
Running: terraform import cloudflare_access_rule.test zone/[ZONE_ID]/[ACCESS_RULE_ID]

**Comment by jacobbednarz** [comment]
The rule you’re attempting to import doesn’t exist. 

This functionality works so you’ll need to double check all of the IDs you are referencing. 

My recent notes at https://github.com/terraform-providers/terraform-provider-cloudflare/issues/694#issuecomment-633803040 might help you out.

**Comment by cucxabong** [comment]
I think that is not the problem, because of I got ID from listing rules from API. I think the problem come from the Cloudflare API itself.

**Listing Access Rule in a zone**
```
curl -X GET "https://api.cloudflare.com/client/v4/zones/[ZONE_ID]/firewall/access_rules/rules" \
    -H "Authorization: Bearer [ACCESS_TOKEN]" \
    -H "Content-Type: application/json" | jq '.result[]'
{
  "id": "[RULE_ID]",
  "paused": false,
  "modified_on": "2018-09-10T11:14:55.700591Z",
  "allowed_modes": [
    "whitelist",
    "block",
    "challenge",
    "js_challenge"
  ],
  "mode": "whitelist",
  "notes": "API user",
  "configuration": {
    "target": "ip",
    "value": "1.1.1.1"
  },
  "scope": {
    "id": "xxxxxxxxxx",
    "type": "organization"
  },
  "created_on": "2018-09-10T11:14:55.72708939Z"
}
```
**Getting rule details (ID from above command output)**
```
curl -X GET "https://api.cloudflare.com/client/v4/zones/[ZONE_ID]/firewall/access_rules/rules/[RULE_ID]" \
    -H "Authorization: Bearer [ACCESS_TOKEN]" \
    -H "Content-Type: application/json"
{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10001,
      "message": "firewallaccessrules.api.not_found"
    }
  ],
  "messages": []
}
```

**Comment by jacobbednarz** [comment]
Are you trying to import a zone or account level firewall access rule?

**Comment by cucxabong** [comment]
It's zone rules

**Comment by cucxabong** [comment]
My mistake, those rule is organization level. Thank you for your support
