### ISSUE TITLE
Move to server side filtering

### ISSUE THREAD

**Issue by mrtristan** [terraform-providers/terraform-provider-cloudflare#707]
CF has per-zone access control granularity when setting up tokens. an api token that's limited to specific zones (as they ideally should be in trying to follow minimum-required access control practices) does not work with the provider due to some actions being performed on client side instead of allowing CF to filter on the server side. this can be readily seen with the zones data source as illustrated below:

when doing:
```
data "cloudflare_zones" "XXXXXXX" {
  filter {
    name   = "xxxx.com"
    # status = "active"
    # paused = false
  }
}
```

fiddler captured:
```
GET https://api.cloudflare.com/client/v4/zones?per_page=50 HTTP/1.1
Host: api.cloudflare.com
User-Agent: HashiCorp Terraform/0.12.26 (+https://www.terraform.io) Terraform Plugin SDK/1.13.0 terraform-provider-cloudflare/2.7.0
Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Content-Type: application/json
Accept-Encoding: gzip
```

which yields a 403. It seems that the api calls are too generic when the api token only has a subset of access.

a curl like this works with the same token:
```
curl -X GET "https://api.cloudflare.com/client/v4/zones?name=xxxx.com" -H "Authorization: Bearer XXXXXXXXXXXXXXXXXXX" -H "Content-Type:application/json"
```

not familiar with all available provider functions, but please be open minded to the approach potentially applying to other CF integration points

**Comment by jacobbednarz** [comment]
Leading over from the other thread, the reason we do the sorting in the provider and as a part of the API request is that [we accept a regex for the `name` value](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/cloudflare/data_source_zones.go#L112). The Cloudflare API doesn't allow this which would break existing clients.

**Comment by jacobbednarz** [comment]
Digging around, I've found we can do substring matches but not regex. I _think_ this is what @ewilde was originally thinking with the introduction of this data source but would be good to confirm so we can push the lot to server side.

**Comment by jacobbednarz** [comment]
I've opened cloudflare/cloudflare-go#478 and I'll PR the changes to Terraform to support this where we can then discuss any extra feedback on the implementation itself.

**Comment by mrtristan** [comment]
@jacobbednarz - I appreciate the quick responses

**Comment by jacobbednarz** [comment]
@mrtristan #708 is adding this functionality if you’d like to check it out and make sure it covers your use case here.
