### ISSUE TITLE
Crash when trying to create rate limit rules

### ISSUE THREAD

**Issue by Workshop2** [terraform-providers/terraform-provider-cloudflare#717]
### Terraform Version
- Terraform 0.12.26
- Cloudflare 2.7.0

### Affected Resource(s)
- cloudflare_rate_limit

### Terraform Configuration Files
```hcl
resource "cloudflare_rate_limit" "resource_name" {
  zone_id     = var.zone_id
  description = "Name"
  disabled    = false
  threshold   = 10
  period      = 60

  match {
    request {
      url_pattern = "${var.zone_base_domain}/pages/payment/credit-card/*"
      schemes     = ["_ALL_"]
      methods     = ["_ALL_"]
    }
  }

  action {
    mode    = "simulate"
    timeout = 60
  }

  correlate {}
}
```

### Debug Output
https://www.dropbox.com/s/zwpkboh3aqgf5pa/debug.log.encrypted.saltpack?dl=0

### Panic Output
https://www.dropbox.com/s/i91bq8lxny90wqr/crash.log.encrypted.saltpack?dl=0

### Expected Behavior
Create new rate limit rule(s)

### Actual Behavior
Terraform crashed.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
I have tried downgrading the Cloudflare provider down to v2.1.0 but it still occurs. Some parts of a changes were persisted to state so I am unable to downgrade terraform.

### References
n/a

**Comment by jacobbednarz** [comment]
Can you try it without the `correlate {}`? That isn't valid as is since it [requires a `by` directive](https://www.terraform.io/docs/providers/cloudflare/r/rate_limit.html#by) if it is set.

**Comment by Workshop2** [comment]
@jacobbednarz thanks, that fixed it
