### ISSUE TITLE
page_rule priorities are applied inconsistently with larger numbers of page rules

### ISSUE THREAD

**Issue by tuturiffic** [terraform-providers/terraform-provider-cloudflare#718]
### Terraform Version
```
% terraform -v
Terraform v0.12.26
+ provider.cloudflare v2.7.0
%
```

### Affected Resource(s)
cloudflare_page_rule -> `priority`

### Terraform Configuration Files
```hcl
provider "cloudflare" {
  version = "~> 2.0"
  email = "tuturiffic@example.com"
  api_token = "<API token>"
  account_id = "<account id>"
}

variable zone {
  type = map
  default = {
    "example.com" = "<zone id>"
  }
}

terraform {
  backend "azurerm" {
    subscription_id = "<subscription id>"
    tenant_id = "<tenant id>"
    resource_group_name = "eg-terraform-rg"
    storage_account_name = "egterraformsa"
    container_name = "tfstate"
    key = "production"
  }
}

resource "cloudflare_page_rule" "redirect_foo_to_bar" {
    zone_id = var.zone["example.com"]

    target = "example.com/path/foo*"

    priority = 65
    status = "active"
    actions {
        forwarding_url {
            status_code = 301
            url = "https://example.com/bar$1"
        }
    }
}
```

### Debug Output
No debug output at this time.

### Panic Output
No panic is produced.

### Expected Behavior
A page rule should be created, redirecting `example.com/path/foo*` to `https://example.com/bar$1`, with a priority of 65.

### Actual Behavior
If this plan is submitted as-is, the page rule is created appropriately and as expected.

If an additional 10 (or so) cloudflare_page_rules are defined, some of the priorities will be correct, and others will be incorrect. All the redirects will be in place, it will just be their priorities that are inconsistent.

### Steps to Reproduce
Reproducing has been somewhat challenging, as the page rule priorities seem to be fine with low quantities of cloudflare_page_rule resources, but get wonky with high quantities of them.

1. Generate a set of 15+ cloudflare_page_rule resources.
2. Run `terraform plan` to see that all resources will be created.
3. Run `terraform apply` to create all the resources. They will be created without error.
4. Run `terraform plan` to see that some of the page rule resources in Cloudflare have priorities that do not match the defined resource in Terraform.
5. Run `terraform apply` to update all resources. The update will complete without error.
6. Run `terraform plan` to see that some resources still have the wrong priorities.

I have been able to coax a reproduction with as few as 9 page rules. There does not seem to be an upper bound.

### Important Factoids
1. We use a pipeline in Azure DevOps to validate, test, and apply our Terraform configuration.
2. This issue only seems to manifest when there is more than one page rule being created/modified -- I have seen the incorrect state be created with as few as 9 page rules being created/modified.
3. Our backend is being stored in an Azure storage account.
4. We've seen this happen across multiple versions of Terraform (0.12.2-0.12.6) as well as the Cloudflare provider (2.5.0-2.7.0)
5. All our defined cloudflare_page_rule priorities are contiguous, starting at 1

### References
N/A

**Comment by jacobbednarz** [comment]
I suspect the underlying issue here is explained in #187. It includes a workaround in there which has been working for us internally for the better portion of 3 years with some zones using 100-120 page rules.

**Comment by tuturiffic** [comment]
Gah, I searched for `page_rule`, not `PageRule`. Thanks, that perfectly covers this.
