### ISSUE TITLE
Add support for `auto_redirect_to_identity` feature on Cloudflare Access

### ISSUE THREAD

**Issue by xens** [terraform-providers/terraform-provider-cloudflare#721]
Goal of this issue is to track the implementation of this missing feature `auto_redirect_to_identity` inside the Cloudflare Terraform provider - Access Application resource.

For now this feature is not yet supported inside the cloudflare-go library (WIP -> cloudflare/cloudflare-go#483). When it'll be done we'll be able to work on the Cloudflare Terraform provider implementation.

Ref:
* https://api.cloudflare.com/#access-applications-properties

**Comment by xens** [comment]
@jacobbednarz I saw that https://github.com/cloudflare/cloudflare-go/issues/483 was merged lately. I'm not super familiar with the whole process, I guess that I should be able to pull the master branch of cloudflare-go and start working on it locally right ?

**Comment by jacobbednarz** [comment]
I would wait until a release is cut and it is automatically pulled into this repository. You can start locally if you want but we'll still be blocked until it lands in a release.

**Comment by xens** [comment]
Ok I'll wait then and check from time to time the new cloudflare-go releases.

**Comment by jacobbednarz** [comment]
Closed by #730
