### ISSUE TITLE
cloudflare_worker_route -- "enabled" parameter missing

### ISSUE THREAD

**Issue by binc75** [terraform-providers/terraform-provider-cloudflare#722]
### Terraform Version
Terraform v0.12.26
provider.cloudflare v2.5.1

### Affected Resource(s)
*cloudflare_worker_route*

### Terraform Configuration Files
```hcl
resource "cloudflare_worker_route" "catch_all" {
  zone_id  = var.cloudflare_zone_id
  pattern = "mydomain.com/test/*"
  enable = false
  script_name = cloudflare_worker_script.ondemand_maintenance_page_script.name
}

resource "cloudflare_worker_script" "ondemand_maintenance_page_script" {
  name = "ondemand-maintenance-page-worker-dev"
  content = file("worker-scripts/ondemand-maintenance-page.js")
}
```

### Debug Output
```
Error: Unsupported argument

  on cloudflare.tf line 4339, in resource "cloudflare_worker_route" "catch_all":
4339:   enabled = false

An argument named "enabled" is not expected here.
```

### Expected Behavior
Following this tutorial it looks like it's (or it was) possible to deploy a worker route in disabled mode.
https://blog.cloudflare.com/deploy-workers-using-terraform/

```
The enabled parameter specifies that requests that match the pattern should run the worker. 
Alternatively, you can set enabled to false which would mean that any requests that match the pattern should not run the worker. 
You can create multiple route patterns, and more-specific route patterns apply before less-specific route patterns. 
For example, you could create one route pattern like example.com/assets/* and set enabled = false then create another pattern like *example.com* and set enabled = true. 
This would enable the worker for all traffic except for requests that match example.com/assets/*.
```
Apparently in the documentation there is no reference to that anymore:
https://www.terraform.io/docs/providers/cloudflare/r/worker_route.html

Is this gone lost?
It would be really useful to deploy a worker in a disabled state.

Cheers
  Nicola

**Comment by jacobbednarz** [comment]
Thanks for raising this one @binc75. Unfortunately, yes, that blog post is from a time when the `enable` property was apart of the API.

Looking through the [API](https://api.cloudflare.com/#worker-routes-properties) [sources](https://developers.cloudflare.com/workers/tooling/api/routes/), this property is no longer accessible (which means we can't define/set functionality based on it). Instead, it looks like the approach to "disable" a worker is to remove the route corresponding with the worker script which won't match the incoming request and not be executed.
