### ISSUE TITLE
cloudflare_logpush_ownership_challenge creates resource on unccessful API call

### ISSUE THREAD

**Issue by trjstewart** [terraform-providers/terraform-provider-cloudflare#726]
When creating a Logpush Ownership Challenge using the resource `cloudflare_logpush_ownership_challenge` it will create the resource and persist it to state even when the ownership API call returns an unsuccessful response with a status of 200.

According to the [documentation](https://api.cloudflare.com/#logpush-jobs-get-ownership-challenge) it looks like we should be taking a look at the value returned in `result.valid`. Specifically if it's false I think we should throw an error with the value of `result.message`.

I may not get the time to test this out and submit a PR so wanted to raise an issue in case someone else wants to take a look, should be pretty easy to validate and remediate.

**Comment by jacobbednarz** [comment]
This is probably better addressed in `cloudflare/cloudflare-go` within the [`GetLogpushOwnershipChallenge`](https://github.com/cloudflare/cloudflare-go/blob/246f2f7879452475ec188afc4e9749bdd0c4aab4/logpush.go#L215) as non-Terraform clients will also be impacted by this.

Have transferred the issue to cloudflare/cloudflare-go#499
