### ISSUE TITLE
Unable to execute 'terraform show -json'

### ISSUE THREAD

**Issue by alor** [terraform-providers/terraform-provider-cloudflare#737]
the command `terraform show -json` is not able to complete. it complains about an unsupported 'edge_cache_ttl' attribute.
the `terraform show` command complete correctly.

### Terraform Version
Terraform v0.12.28
+ provider.cloudflare v2.8.0
+ provider.digitalocean v1.20.0

### Expected Behavior
show data in json format

### Actual Behavior
`Failed to marshal state to json: unsupported attribute "edge_cache_ttl"`

### Steps to Reproduce
`terraform show -json`

### Important Factoids
I've recently upgraded the cloudflare provider to version 2.8.0, it was working with my older version.

**Comment by alor** [comment]
I've seen https://github.com/terraform-providers/terraform-provider-cloudflare/pull/654 
should I manually remove the "edge_cache_ttl" attribute from my state file?

**Comment by jacobbednarz** [comment]
Yep, pull your terraform state file locally and delete it and you'll be set to go.
