### ISSUE TITLE
Create SRV record fails in weight as not valid integer

### ISSUE THREAD

**Issue by xabim** [terraform-providers/terraform-provider-cloudflare#80]
Hi, I'm trying to use cloudflare records with terraform but I'm having a issue with SRV records in weight

### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
- cloudflare_record (SRV)

### Terraform Configuration Files
```hcl
resource "cloudflare_record" "_sipfederationtls_tcp_SRV" {
  domain = "${var.cloudflare_domain}"
  name   = "_sipfederationtls._tcp.${var.cloudflare_domain}"
  type   = "SRV"


  data = {
    service  = "_sipfederationtls"
    proto    = "_tcp"
    name     = "${var.cloudflare_domain}."
    priority = 100
    weight   = 1
    port     = 443
    target   = "sipfed.online.lync.com."
  }
}
```
### Debug Output
The thing is that I'm getting a error validating the DNS, the response from the cloudflare API:

https://gist.github.com/xabim/807230a41aaceb2699d426d1f9b8e88a

### Expected Behavior
Create SRV records

### Actual Behavior
It doesn't create the record

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply`

**Comment by xabim** [comment]
It seems now the port/priority/weight has to be an integer, I've seen terraform map are only for strings so, it sends **"priority":"100"** but cloudflare API expects **"priority":100**

**Comment by jem-Solytica** [comment]
I am also experiencing the same issue.

**Comment by king601** [comment]
Also experiencing this exact same issue.

**Comment by patryk** [comment]
Thanks for report.
