### ISSUE TITLE
host_header_override and resolve_override treated as OnOff

### ISSUE THREAD

**Issue by simpsora** [terraform-providers/terraform-provider-cloudflare#82]
`host_header_override` and `resolve_override` actions are both treated as OnOff values, meaning the provider will only allow values of `on` or `off` for them.  These should allow arbitrary string values instead.

### Terraform Version
```
$ terraform -v
Terraform v0.11.7
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `cloudflare_page_rule`

### Terraform Configuration Files
```hcl
resource "cloudflare_page_rule" "f86f9059911714b0d9f5bf7b1ca4b4e0" {
  zone = "${var.domain}"
  priority = 119
  target = "shopfront.${var.domain}/homepage/*"
  status = "active"

  actions = {
    resolve_override = "${var.origin}"
    host_header_override = "${var.domain}"
  }
}
```

### Expected Behavior
The values for `host_header_override` and `resolve_override` actions should be accepted.

### Actual Behavior
```
Error: cloudflare_page_rule.f86f9059911714b0d9f5bf7b1ca4b4e0: expected actions.0.host_header_override to be one of [on off], got foo.net
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
N/A

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- Added in https://github.com/terraform-providers/terraform-provider-cloudflare/pull/76
- Mentioned in https://github.com/terraform-providers/terraform-provider-cloudflare/issues/46

**Comment by patryk** [comment]
Ops! Sorry about that!
