### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by gmsantos** [terraform-providers/terraform-provider-cloudflare#89]
Is there a new release planned to this module?

I'm asking that because @brunopadz and I want to use the updates from https://github.com/terraform-providers/terraform-provider-cloudflare/pull/83 but when we run `terraform init` we get the same release from April 6 (https://github.com/terraform-providers/terraform-provider-cloudflare/releases/tag/v1.0.0)

**Comment by patryk** [comment]
We're checking out with Terraform what's the proper procedure for making a release. Please bear with us.

**Comment by simpsora** [comment]
:+1: -- beyond getting the current crop of merged PRs released, I'd love to hear what the plan is for releases going forward.

**Comment by patryk** [comment]
We have an internal list of most requested features and intend to implement them in order. Won't promise we'll hit 100% of API coverage, but we'll try to be as close as possible.

**Comment by patryk** [comment]
Unfortunately not, we're still eagerly waiting for response. I do hope we'll make a release early next week.

**Comment by garrettgalow** [comment]
We are working with Hashicorp on this now. Hopefully should have a new release cut soon. Thanks for your patience.

**Comment by patryk** [comment]
Hello everyone, the release is out!
https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/CHANGELOG.md#110-july-25-2018
