### ISSUE TITLE
Validate contents of TXT record

### ISSUE THREAD

**Issue by jleclanche** [terraform-providers/terraform-provider-cloudflare#9]
Feature request: Validation of `TXT` contents.

Reproduce an error with, eg. creating  the following cloudflare record:

```hcl
resource "cloudflare_record" "bad_txt_record" {
	domain = "example.com"
	name = "example"
	type = "TXT"
	value = "\n"
}
```

You will get the error:

```
Failed to create record: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1004,\"message\":\"DNS Validation Error\",\"error_chain\":[{\"code\":9051,\"message\":\"Invalid TXT record. Record may only contain printable ASCII!\"}]}],\"messages\":[],\"result\":null}" 
```

**Comment by thomasbiddle** [comment]
This seems normal, no? You're adding a new line character as a value; I'm very certain you wouldn't be able to do that either in the console or via API - not to mention, it's just plain not a valid DNS entry.

**Comment by jleclanche** [comment]
It should be validated at plan time rather than letting it error.
