### ISSUE TITLE
Unable to create CAA record

### ISSUE THREAD

**Issue by graemer957** [terraform-providers/terraform-provider-cloudflare#91]
### Terraform Version
Terraform v0.11.7
+ provider.aws v1.27.0
+ provider.cloudflare v1.0.0

### Affected Resource(s)
- cloudflare_record

### Terraform Configuration Files
```hcl
resource "cloudflare_record" "caa" {
  domain  = "mydomain.com"
  name    = "mydomain.com"
  data    = {
    flags = "0"
    tag   = "issue"
    value = "letsencrypt.org"
  }
  type    = "CAA"
  ttl     = 1
}
```

### Debug Output
[gist of debug output](https://gist.github.com/graemer957/a73d706a8c0f0739744fedd5227e3f59)

### Expected Behavior
CAA record is created

### Actual Behavior
Error from CloudFlare API

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Interestingly, if I manually create the CAA record using the Dashboard and then:
1. `terraform import`
2. `terraform apply`
...there are no changes to be applied, telling me the configuration looks correct.

### References
- #26 
- #29

**Comment by maetthu** [comment]
To add to that, this error also occurs when changing an existing, manually imported record - both creating a new record and updating an existing one fail. I can confirm that refreshing the state for CAA records work fine and are reported to be in sync if it's matches with the actual state, it just can't apply the diff.

**Comment by patryk** [comment]
Thanks for report.

**Comment by graemer957** [comment]
Thanks @patryk, just updated to `provider.cloudflare: version = "~> 1.1"` and tested creating, updating and deleting CAA record. All worked great 👍🏻
