### ISSUE TITLE
Value "off_enterprise" not recognized as value for "security_level"

### ISSUE THREAD

**Issue by OffEnterprise** [terraform-providers/terraform-provider-cloudflare#99]
### Terraform Version
```
Terraform v0.11.7
+ provider.cloudflare v1.1.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `cloudflare_zone_settings_override`

### Terraform Configuration Files
```
resource "cloudflare_zone_settings_override" "flexible_ssl" {
  name = "${var.zone}"

  settings {
    ssl = "flexible"
    security_level = "off_enterprise"
  }
}
```

### Expected Behavior
When I enter "off_enterprise" as a value for security_level, which is available for enterprise accounts, this should be accepted as a valid value.

### Actual Behavior
Terraform failed with the following output:
```
Error: cloudflare_zone_settings_override.flexible_ssl: expected settings.0.security_level to be one of [essentially_off low medium high under_attack], got off_enterprise
``` 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
The account in question is an Enterprise account.

**Comment by patryk** [comment]
Hello, thanks for report. The correct setting value is `off`, which I have just added and will be released with next version.
